export const lang = {
	'GREEN_BG': {
		'en': 'Green Background',
		'zh-CN': '绿色背景',
		'zh-TW': '綠色背景',
		'fr': 'Fond vert',
		'de': 'Grüner Hintergrund',
		'it': 'Sfondo verde',
		'ko': '녹색 배경',
		'ja': '緑の背景',
		'pt': 'Fundo verde',
		'pt-br': 'Fundo verde',
		'es': 'Fondo verde',
		'ru': 'Зеленый фон',
		'tr': 'Yeşil arka plan',
	},
	'DEFAULT_BG': {
		'en': 'Default Background',
		'zh-CN': '默认背景',
		'zh-TW': '默認背景',
		'fr': 'Contexte par défaut',
		'de': 'Standardhintergrund',
		'it': 'Sfondo predefinito',
		'ko': '기본 배경',
		'ja': 'デフォルトの背景',
		'pt': 'Fundo padrão',
		'pt-br': 'Fundo padrão',
		'es': 'Antecedentes predeterminados',
		'ru': 'Фон по умолчанию',
		'tr': 'Varsayılan arka plan',
	},
	'YELLOW_BG': {
		'en': 'Yellow Background',
		'zh-CN': '黄色背景',
		'zh-TW': '黃色背景',
		'fr': 'Fond jaune',
		'de': 'Gelber Hintergrund',
		'it': 'Sfondo giallo',
		'ko': '노란색 배경',
		'ja': '黄色の背景',
		'pt': 'Fundo amarelo',
		'pt-br': 'Fundo amarelo',
		'es': 'Fondo amarillo',
		'ru': 'Желтый фон',
		'tr': 'Sarı arka plan',
	},
	'RED_BG': {
		'en': 'Red Background',
		'zh-CN': '红色背景',
		'zh-TW': '紅色背景',
		'fr': 'Fond rouge',
		'de': 'Roter Hintergrund',
		'it': 'Sfondo rosso',
		'ko': '빨간 배경',
		'ja': '赤い背景',
		'pt': 'Fundo vermelho',
		'pt-br': 'Fundo vermelho',
		'es': 'Fondo rojo',
		'ru': 'Красный фон',
		'tr': 'Kırmızı arka plan',
	},
	'YELLOW_PB': {
		'en': 'Yellow Pillbox',
		'zh-CN': '黄色药盒',
		'zh-TW': '黃色藥盒',
		'fr': 'Pilule jaune',
		'de': 'Gelbe Pillbox',
		'it': 'Pillbox gialla',
		'ko': '옐로우 필 박스',
		'ja': '黄色のピルボックス',
		'pt': 'Caixa de comprimidos amarela',
		'pt-br': 'Caixa de comprimidos amarela',
		'es': 'Pastillero amarillo',
		'ru': 'Желтая коробка таблеток',
		'tr': 'Sarı hap kutusu',
	},
	'RED_PB': {
		'en': 'Red Pillbox',
		'zh-CN': '红色药盒',
		'zh-TW': '紅色藥盒',
		'fr': 'Caisse de pilule rouge',
		'de': 'Rote Pillbox',
		'it': 'PILBOX ROSSO',
		'ko': '빨간 필 박스',
		'ja': '赤いピルボックス',
		'pt': 'Caixa de pílulas vermelhas',
		'pt-br': 'Caixa de pílulas vermelhas',
		'es': 'Pastillero rojo',
		'ru': 'Красная коробка таблеток',
		'tr': 'Kırmızı hap kutusu',
	},
	'ITEM_DESC_1': {
		'en': 'Item is currently Equipped',
		'zh-CN': '物品当前配备了',
		'zh-TW': '物品當前配備了',
		'fr': 'L\'article est actuellement équipé',
		'de': 'Der Artikel ist derzeit ausgestattet',
		'it': 'L\'oggetto è attualmente attrezzato',
		'ko': '항목은 현재 장착되어 있습니다',
		'ja': 'アイテムは現在装備されています',
		'pt': 'Item está atualmente equipado',
		'pt-br': 'Item está atualmente equipado',
		'es': 'El artículo está actualmente equipado',
		'ru': 'Товар в настоящее время оборудован',
		'tr': 'Öğe şu anda donanımlı',
	},
	'ITEM_DESC_2': {
		'en': 'At least 1 item exists in the bank',
		'zh-CN': '银行中至少有1个项目',
		'zh-TW': '銀行中至少有1個項目',
		'fr': 'Au moins 1 article existe dans la banque',
		'de': 'Mindestens 1 Artikel existiert in der Bank',
		'it': 'Esistono almeno 1 articolo in banca',
		'ko': '은행에 최소 1 개의 품목이 존재합니다',
		'ja': '銀行には少なくとも1つのアイテムが存在します',
		'pt': 'Existe pelo menos 1 item no banco',
		'pt-br': 'Existe pelo menos 1 item no banco',
		'es': 'Existe al menos 1 artículo en el banco',
		'ru': 'По крайней мере 1 пункт существует в банке',
		'tr': 'Bankada en az 1 madde var',
	},
	'ITEM_DESC_3': {
		'en': 'Item is in a different Equipment set',
		'zh-CN': '物品在不同的设备集中',
		'zh-TW': '物品在不同的設備集中',
		'fr': 'L\'article est dans un ensemble d\'équipements différent',
		'de': 'Der Artikel befindet sich in einem anderen Gerätset',
		'it': 'L\'articolo si trova in un set di attrezzature diverso',
		'ko': '품목은 다른 장비 세트에 있습니다',
		'ja': 'アイテムは別の機器セットにあります',
		'pt': 'O item está em um conjunto de equipamentos diferente',
		'pt-br': 'O item está em um conjunto de equipamentos diferente',
		'es': 'El artículo está en un conjunto de equipos diferente',
		'ru': 'Товар находится в другом наборе оборудования',
		'tr': 'Öğe farklı bir ekipman setinde',
	},
	'ITEM_DESC_4': {
		'en': 'You do not own this item',
		'zh-CN': '您不拥有此项目',
		'zh-TW': '您不擁有此項目',
		'fr': 'Vous ne possédez pas cet article',
		'de': 'Sie besitzen diesen Artikel nicht',
		'it': 'Non possiedi questo articolo',
		'ko': '이 항목을 소유하지 않습니다',
		'ja': 'あなたはこのアイテムを所有していません',
		'pt': 'Você não possui este item',
		'pt-br': 'Você não possui este item',
		'es': 'No tienes este artículo',
		'ru': 'У вас нет этого предмета',
		'tr': 'Bu öğeye sahip değilsin',
	},
	'ITEM_DESC_5': {
		'en': '(Consumable) You have more of this in the Bank',
		'zh-CN': '（消耗）您在银行中有更多的',
		'zh-TW': '（消耗）您在銀行中有更多的',
		'fr': '(Consommable) Vous en avez plus à la banque',
		'de': '(Verbrauchsler) Sie haben mehr davon auf der Bank',
		'it': '(Consumibile) Ne hai più in banca',
		'ko': '(소모품) 은행에 더 많은 것을 가지고 있습니다.',
		'ja': '（消耗品）あなたは銀行にこれをもっと持っています',
		'pt': '(Consumível) Você tem mais disso no banco',
		'pt-br': '(Consumível) Você tem mais disso no banco',
		'es': '(Consumible) Tienes más de esto en el banco',
		'ru': '(Потребляемый) У вас есть больше этого в банке',
		'tr': '(Sarf malzemesi) Bankada daha fazlasına sahipsiniz',
	},
	'ITEM_DESC_6': {
		'en': 'Clicking on icons will Equip the Item',
		'zh-CN': '点击图标将装备物品',
		'zh-TW': '點擊圖標將裝備物品',
		'fr': 'Cliquer sur les icônes équipera l\'élément',
		'de': 'Wenn Sie auf Symbole klicken, werden Sie den Artikel ausrüsten',
		'it': 'Facendo clic sulle icone equipaggerà l\'articolo',
		'ko': '아이콘을 클릭하면 항목이 장착됩니다',
		'ja': 'アイコンをクリックすると、アイテムが装備されます',
		'pt': 'Clicar em ícones equipará o item',
		'pt-br': 'Clicar em ícones equipará o item',
		'es': 'Hacer clic en los iconos equipará el artículo',
		'ru': 'Нажатие на значки оснастит элемент',
		'tr': 'Simgelere tıklamak öğeyi donatır',
	},
	'ITEM_DESC_7': {
		'en': 'Right Clicking on Icons (Long Hold on Mobile) will Equip them into the Passive Slot',
		'zh-CN': '右键点击图标（在手机上长按）可将其装备到被动插槽中',
		'zh-TW': '右鍵單擊圖標（長時間持有移動設備）將把它們裝備到被動插槽中',
		'fr': 'Un clic droit sur les icônes (maintien prolongé sur mobile) permet de les équiper dans l\'emplacement passif',
		'de': 'Ein Rechtsklick auf die Symbole (auf dem Handy lang halten) rüstet sie in den passiven Slot aus',
		'it': 'Facendo clic con il tasto destro del mouse sulle icone (tenendo premuto a lungo su cellulare), le equipaggerete nello slot passivo',
		'ko': '아이콘을 우클릭(모바일에서는 길게 누르기)하면 패시브 슬롯에 장착됩니다',
		'ja': 'アイコンを右クリック（モバイルでは長押し）すると、パッシブスロットに装備されます',
		'pt': 'Clicar com o botão direito do rato nos ícones (manter premido no telemóvel) irá equipá-los na ranhura passiva',
		'pt-br': 'Clicar com o botão direito do mouse nos ícones (manter pressionado no celular) os equipará no slot passivo',
		'es': 'Si haces clic con el botón derecho del ratón en los iconos (si lo mantienes pulsado en el móvil), los equiparás en la ranura pasiva',
		'ru': 'Щелчок правой кнопкой мыши на иконках (длительное удержание на мобильных устройствах) позволит экипировать их в пассивный слот',
		'tr': 'Simgelere Sağ Tıklamak (Mobil Cihazlarda Uzun Tutmak) onları Pasif Yuvasına Donatır',
	},
	'POI_INFO': {
		'en': 'Points of Interest',
		'zh-CN': '兴趣点',
		'zh-TW': '興趣點',
		'fr': 'Points d\'interêts',
		'de': 'Sehenswürdigkeiten',
		'it': 'Punti di interesse',
		'ko': '가볼만한 곳',
		'ja': '興味がある点',
		'pt': 'Pontos de interesse',
		'pt-br': 'Pontos de interesse',
		'es': 'Puntos de interés',
		'ru': 'Точки интереса',
		'tr': 'İlgi noktaları',
	},
	'POI_DESC_1': {
		'en': 'You are currently standing here',
		'zh-CN': '您目前站在这里',
		'zh-TW': '您目前站在這裡',
		'fr': 'Vous êtes actuellement debout ici',
		'de': 'Sie stehen derzeit hier',
		'it': 'Attualmente sei qui',
		'ko': '당신은 현재 여기 서 있습니다',
		'ja': 'あなたは現在ここに立っています',
		'pt': 'Você está atualmente de pé aqui',
		'pt-br': 'Você está atualmente de pé aqui',
		'es': 'Actualmente estás parado aquí',
		'ru': 'Вы сейчас стоите здесь',
		'tr': 'Şu anda burada duruyorsun',
	},
	'POI_DESC_2': {
		'en': 'You meet all the requirements to move here',
		'zh-CN': '您满足搬到这里的所有要求',
		'zh-TW': '您滿足搬到這裡的所有要求',
		'fr': 'Vous répondez à toutes les exigences pour déplacer ici',
		'de': 'Sie erfüllen alle Anforderungen, um hierher zu ziehen',
		'it': 'Soddisfi tutti i requisiti per trasferirsi qui',
		'ko': '여기로 이동하려면 모든 요구 사항을 충족합니다',
		'ja': 'ここに移動するためのすべての要件を満たしています',
		'pt': 'Você atende a todos os requisitos para se mover aqui',
		'pt-br': 'Você atende a todos os requisitos para se mover aqui',
		'es': 'Cumple con todos los requisitos para mudarse aquí',
		'ru': 'Вы выполняете все требования, чтобы переехать сюда',
		'tr': 'Buraya taşınmak için tüm gereksinimleri karşılıyorsunuz',
	},
	'POI_DESC_3': {
		'en': 'You can\'t afford to move here',
		'zh-CN': '你负担不起搬到这里',
		'zh-TW': '你負擔不起搬到這裡',
		'fr': 'Vous ne pouvez pas vous permettre de déménager ici',
		'de': 'Sie können es sich nicht leisten, hierher zu ziehen',
		'it': 'Non puoi permetterti di trasferirti qui',
		'ko': '당신은 여기로 이사 할 여유가 없습니다',
		'ja': 'ここに移動する余裕はありません',
		'pt': 'Você não pode se dar ao luxo de se mudar para cá',
		'pt-br': 'Você não pode se dar ao luxo de se mudar para cá',
		'es': 'No puedes permitirte mudarte aquí',
		'ru': 'Вы не можете позволить себе переехать сюда',
		'tr': 'Buraya taşınmayı göze alamazsın',
	},
	'POI_DESC_4': {
		'en': 'This has not been Discovered',
		'zh-CN': '这尚未发现',
		'zh-TW': '這尚未發現',
		'fr': 'Cela n\'a pas été découvert',
		'de': 'Dies wurde nicht entdeckt',
		'it': 'Questo non è stato scoperto',
		'ko': '이것은 발견되지 않았습니다',
		'ja': 'これは発見されていません',
		'pt': 'Isso não foi descoberto',
		'pt-br': 'Isso não foi descoberto',
		'es': 'Esto no ha sido descubierto',
		'ru': 'Это не было обнаружено',
		'tr': 'Bu keşfedilmedi',
	},
	'POI_DESC_5': {
		'en': 'This is not in the current Map',
		'zh-CN': '这不在当前地图中',
		'zh-TW': '這不在當前地圖中',
		'fr': 'Ce n\'est pas dans la carte actuelle',
		'de': 'Dies liegt nicht in der aktuellen Karte',
		'it': 'Questo non è nella mappa corrente',
		'ko': '이것은 현재지도에 없습니다',
		'ja': 'これは現在のマップにはありません',
		'pt': 'Isso não está no mapa atual',
		'pt-br': 'Isso não está no mapa atual',
		'es': 'Esto no está en el mapa actual',
		'ru': 'Этого не в текущей карте',
		'tr': 'Bu mevcut haritada değil',
	},
	'POI_DESC_6': {
		'en': 'Clicking on the Icon will move you here',
		'zh-CN': '单击图标将使您在这里移动',
		'zh-TW': '單擊圖標將使您在這裡移動',
		'fr': 'Cliquer sur l\'icône vous déplacera ici',
		'de': 'Wenn Sie auf das Symbol klicken, verschieben Sie hier',
		'it': 'Fare clic sull\'icona ti sposterà qui',
		'ko': '아이콘을 클릭하면 여기로 이동합니다',
		'ja': 'アイコンをクリックすると、ここに移動します',
		'pt': 'Clicar no ícone irá movê -lo aqui',
		'pt-br': 'Clicar no ícone irá movê -lo aqui',
		'es': 'Hacer clic en el icono lo moverá aquí',
		'ru': 'Нажатие на значок переместит вас здесь',
		'tr': 'Simgeye tıklamak sizi buraya taşıyacak',
	},
	'OBSTACLE_DESC_1': {
		'en': 'This is currently built',
		'zh-CN': '这是当前建造的',
		'zh-TW': '這是當前建造的',
		'fr': 'Ceci est actuellement construit',
		'de': 'Dies wird derzeit gebaut',
		'it': 'Questo è attualmente costruito',
		'ko': '이것은 현재 제작되었습니다',
		'ja': 'これは現在構築されています',
		'pt': 'Isso está atualmente construído',
		'pt-br': 'Isso está atualmente construído',
		'es': 'Esto está construido actualmente',
		'ru': 'Это в настоящее время построено',
		'tr': 'Bu şu anda inşa edildi',
	},
	'OBSTACLE_DESC_2': {
		'en': 'You meet all the requirements to build this',
		'zh-CN': '您符合建立这个的所有要求',
		'zh-TW': '您符合建立這個的所有要求',
		'fr': 'Vous répondez à toutes les exigences pour construire ce',
		'de': 'Sie erfüllen alle Anforderungen, um dies zu bauen',
		'it': 'Soddisfi tutti i requisiti per costruire questo',
		'ko': '이를 구축하기위한 모든 요구 사항을 충족합니다',
		'ja': 'これを構築するためのすべての要件を満たしています',
		'pt': 'Você atende a todos os requisitos para construir isso',
		'pt-br': 'Você atende a todos os requisitos para construir isso',
		'es': 'Cumple con todos los requisitos para construir esto',
		'ru': 'Вы отвечаете всем требованиям, чтобы построить это',
		'tr': 'Bunu oluşturmak için tüm gereksinimleri karşılıyorsunuz',
	},
	'OBSTACLE_DESC_3': {
		'en': 'You meet all of the requirements but you can\'t afford this',
		'zh-CN': '您符合所有要求，但您负担不起',
		'zh-TW': '您符合所有要求，但您負擔不起',
		'fr': 'Vous répondez à toutes les exigences mais vous ne pouvez pas vous permettre',
		'de': 'Sie erfüllen alle Anforderungen, können sich dies jedoch nicht leisten',
		'it': 'Soddisfi tutti i requisiti ma non puoi permetterti',
		'ko': '당신은 모든 요구 사항을 충족하지만 이것을 감당할 수는 없습니다.',
		'ja': 'あなたはすべての要件を満たしていますが、あなたはこれを買う余裕はありません',
		'pt': 'Você atende a todos os requisitos, mas não pode pagar isso',
		'pt-br': 'Você atende a todos os requisitos, mas não pode pagar isso',
		'es': 'Usted cumple con todos los requisitos pero no puede pagar esto',
		'ru': 'Вы выполняете все требования, но вы не можете себе это позволить',
		'tr': 'Tüm gereksinimleri karşılıyorsunuz ama bunu karşılayamazsınız',
	},
	'OBSTACLE_DESC_4': {
		'en': 'You do not meet the level requirements',
		'zh-CN': '您不符合水平要求',
		'zh-TW': '您不符合水平要求',
		'fr': 'Vous ne répondez pas aux exigences de niveau',
		'de': 'Sie erfüllen die Level -Anforderungen nicht',
		'it': 'Non soddisfi i requisiti di livello',
		'ko': '레벨 요구 사항을 충족하지 않습니다',
		'ja': 'レベルの要件を満たしていません',
		'pt': 'Você não atende aos requisitos de nível',
		'pt-br': 'Você não atende aos requisitos de nível',
		'es': 'No cumple con los requisitos de nivel',
		'ru': 'Вы не соответствуете требованиям уровня',
		'tr': 'Seviye gereksinimlerini karşılamıyorsunuz',
	},
	'OBSTACLE_DESC_5': {
		'en': 'Clicking the Icon will open up a build menu',
		'zh-CN': '单击图标将打开构建菜单',
		'zh-TW': '單擊圖標將打開構建菜單',
		'fr': 'Cliquer sur l\'icône ouvrira un menu de construction',
		'de': 'Wenn Sie auf das Symbol klicken, wird ein Build -Menü geöffnet',
		'it': 'Facendo clic sull\'icona aprirà un menu di build',
		'ko': '아이콘을 클릭하면 빌드 메뉴가 열립니다',
		'ja': 'アイコンをクリックすると、ビルドメニューが開きます',
		'pt': 'Clicar no ícone abrirá um menu de construção',
		'pt-br': 'Clicar no ícone abrirá um menu de construção',
		'es': 'Haga clic en el icono abrirá un menú de compilación',
		'ru': 'Нажатие на значок откроет меню сборки',
		'tr': 'Simgeye tıklamak bir derleme menüsü açacaktır',
	},
	'OTHER_DESC_1': {
		'en': 'You do not own this',
		'zh-CN': '你不拥有这个',
		'zh-TW': '你不擁有這個',
		'fr': 'Vous ne possédez pas ceci',
		'de': 'Sie besitzen das nicht',
		'it': 'Non lo possiedi',
		'ko': '당신은 이것을 소유하지 않습니다',
		'ja': 'あなたはこれを所有していません',
		'pt': 'Você não possui isso',
		'pt-br': 'Você não possui isso',
		'es': 'No tienes esto',
		'ru': 'У тебя это не владеешь',
		'tr': 'Buna sahip değilsin',
	},
	'PURCHASE_DESC_1': {
		'en': 'You meet all the requirements to purchase this',
		'zh-CN': '您满足购买此产品的所有要求',
		'zh-TW': '您滿足購買此產品的所有要求',
		'fr': 'Vous répondez à toutes les exigences pour acheter ce',
		'de': 'Sie erfüllen alle Anforderungen, um dies zu kaufen',
		'it': 'Soddisfi tutti i requisiti per acquistarlo',
		'ko': '이를 구매하기위한 모든 요구 사항을 충족합니다',
		'ja': 'これを購入するためのすべての要件を満たしています',
		'pt': 'Você atende a todos os requisitos para comprar isso',
		'pt-br': 'Você atende a todos os requisitos para comprar isso',
		'es': 'Usted cumple con todos los requisitos para comprar esto',
		'ru': 'Вы выполняете все требования для покупки этого',
		'tr': 'Bunu satın almak için tüm gereksinimleri karşılıyorsunuz',
	},
	'PURCHASE_DESC_3': {
		'en': 'Click the Icon to Purchase',
		'zh-CN': '点击图标购买',
		'zh-TW': '點擊圖標購買',
		'fr': 'Cliquez sur l\'icône pour acheter',
		'de': 'Klicken Sie auf das Kaufsymbol',
		'it': 'Fai clic sull\'icona per acquistare',
		'ko': '구매하려면 아이콘을 클릭하십시오',
		'ja': 'アイコンをクリックして購入します',
		'pt': 'Clique no ícone para comprar',
		'pt-br': 'Clique no ícone para comprar',
		'es': 'Haga clic en el icono para comprar',
		'ru': 'Нажмите на значок, чтобы купить',
		'tr': 'Satın almak için simgeye tıklayın',
	},
	'FILTERING_DESC_1': {
		'en': 'Click on an Icon to Filter!',
		'zh-CN': '单击图标进行过滤！',
		'zh-TW': '單擊圖標進行過濾！',
		'fr': 'Cliquez sur une icône pour filtrer!',
		'de': 'Klicken Sie auf ein Symbol, um zu filtern!',
		'it': 'Fai clic su un\'icona per filtrare!',
		'ko': '아이콘을 클릭하여 필터링하십시오!',
		'ja': 'フィルタリングするアイコンをクリックしてください！',
		'pt': 'Clique em um ícone para filtrar!',
		'pt-br': 'Clique em um ícone para filtrar!',
		'es': '¡Haga clic en un icono para filtrar!',
		'ru': 'Нажмите на значок, чтобы фильтровать!',
		'tr': 'Filtre etmek için bir simgeye tıklayın!',
	},
	'FILTERING_DESC_2': {
		'en': 'Mass Filtering will filter that icon everywhere.',
		'zh-CN': '质量过滤将到处过滤该图标。',
		'zh-TW': '質量過濾將到處過濾該圖標。',
		'fr': 'Le filtrage de masse filtrera cette icône partout.',
		'de': 'Die Massenfilterung filtert dieses Symbol überall.',
		'it': 'Il filtraggio di massa filtrerà quell\'icona ovunque.',
		'ko': '질량 필터링은 그 아이콘을 어디에서나 필터링합니다.',
		'ja': 'マスフィルタリングは、どこでもそのアイコンをフィルタリングします。',
		'pt': 'A filtragem em massa filtra esse ícone em todos os lugares.',
		'pt-br': 'A filtragem em massa filtra esse ícone em todos os lugares.',
		'es': 'El filtrado de masa filtrará ese icono en todas partes.',
		'ru': 'Массовая фильтрация будет фильтровать этот значок повсюду.',
		'tr': 'Kütle filtreleme bu simgeyi her yerde filtreleyecektir.',
	},
	'SETTING_MENU_STATE': {
		'en': 'State of the Menus after loading a save',
		'zh-CN': '加载保存后的菜单状态',
		'zh-TW': '加載保存後的菜單狀態',
		'fr': 'État des menus après avoir chargé une sauvegarde',
		'de': 'Zustand der Menüs nach dem Laden eines Speicherns',
		'it': 'Stato dei menu dopo aver caricato un salvataggio',
		'ko': '저장을로드 한 후 메뉴 상태',
		'ja': '保存をロードした後のメニューの状態',
		'pt': 'Estado dos menus depois de carregar uma defesa',
		'pt-br': 'Estado dos menus depois de carregar uma defesa',
		'es': 'Estado de los menús después de cargar un salvamento',
		'ru': 'Состояние меню после загрузки сохранения',
		'tr': 'Bir kaydetme yükledikten sonra menülerin durumu',
	},
	'SETTING_FILTER': {
		'en': 'Mass filter by ID',
		'zh-CN': '质量过滤',
		'zh-TW': '質量過濾',
		'fr': 'Filtre de masse par id',
		'de': 'Massenfilter durch ID',
		'it': 'Filtro di massa per ID',
		'ko': 'ID에 의한 질량 필터',
		'ja': 'IDによる質量フィルター',
		'pt': 'Filtro de massa por id',
		'pt-br': 'Filtro de massa por id',
		'es': 'Filtro de masa por ID',
		'ru': 'Массовый фильтр от ID',
		'tr': 'Kimliğe göre kütle filtresi',
	},
	'SETTING_FILTER_DESC': {
		'en': 'Effects everything this mod checks for. Requires a restart to take effect.',
		'zh-CN': '影响此Mod检查的所有内容。需要重新启动才能生效。',
		'zh-TW': '影響此Mod檢查的所有內容。需要重新啟動才能生效。',
		'fr': 'Effectue tout ce que ce mod vérifie. Nécessite un redémarrage pour prendre effet.',
		'de': 'Wirkt sich alles aus, auf diese Mod überprüft. Erfordert einen Neustart, um wirksam zu werden.',
		'it': 'Effetti tutto ciò che questo mod controlla. Richiede un riavvio per avere effetto.',
		'ko': '이 모드가 확인하는 모든 것에 영향을 미칩니다. 발효하려면 다시 시작해야합니다.',
		'ja': 'このmodがチェックするすべての影響を与えます。有効にするには再起動が必要です。',
		'pt': 'Efeitos tudo o que este mod verifica. Requer uma reinicialização para entrar em vigor.',
		'pt-br': 'Efeitos tudo o que este mod verifica. Requer uma reinicialização para entrar em vigor.',
		'es': 'Efecta todo lo que este mod verifica. Requiere un reinicio para entrar en vigencia.',
		'ru': 'Влияет на все, на что проверяет этот мод. Требуется перезапуск, чтобы вступить в силу.',
		'tr': 'Bu modun kontrol ettiği her şeyi etkiler. Bir yeniden başlatma gerektirir.',
	},
	'SETTING_RESET_DATA': {
		'en': 'Reset all Filtered Items?',
		'zh-CN': '重置所有过滤项目？',
		'zh-TW': '重置所有過濾項目？',
		'fr': 'Réinitialiser tous les articles filtrés?',
		'de': 'Alle gefilterten Elemente zurücksetzen?',
		'it': 'Ripristina tutti gli elementi filtrati?',
		'ko': '필터링 된 모든 항목을 재설정 하시겠습니까?',
		'ja': 'すべてのフィルタリングされたアイテムをリセットしますか？',
		'pt': 'Redefinir todos os itens filtrados?',
		'pt-br': 'Redefinir todos os itens filtrados?',
		'es': 'Restablecer todos los elementos filtrados?',
		'ru': 'Сбросить все фильтрованные предметы?',
		'tr': 'Tüm filtrelenmiş öğeleri sıfırlayın?',
	},
	'RESET': {
		'en': 'Reset',
		'zh-CN': '重置',
		'zh-TW': '重置',
		'fr': 'Réinitialiser',
		'de': 'Zurücksetzen',
		'it': 'Ripristina',
		'ko': '초기화',
		'ja': 'リセット',
		'pt': 'Reiniciar',
		'pt-br': 'Reiniciar',
		'es': 'Reiniciar',
		'ru': 'Перезагрузить',
		'tr': 'Sıfırla',
	},
	'SETTING_MENU_STATE_1': {
		'en': 'Remember Previous State',
		'zh-CN': '记住以前的状态',
		'zh-TW': '記住以前的狀態',
		'fr': 'Rappelez-vous l\'état précédent',
		'de': 'Erinnere dich an den vorherigen Staat',
		'it': 'Ricorda lo stato precedente',
		'ko': '이전 상태를 기억하십시오',
		'ja': '前の状態を覚えておいてください',
		'pt': 'Lembre -se do estado anterior',
		'pt-br': 'Lembre -se do estado anterior',
		'es': 'Recuerda el estado anterior',
		'ru': 'Помните предыдущее состояние',
		'tr': 'Önceki durumu hatırla',
	},
	'SETTING_MENU_STATE_2': {
		'en': 'Always Start Closed',
		'zh-CN': '总是开始关闭',
		'zh-TW': '總是開始關閉',
		'fr': 'Commencez toujours fermer',
		'de': 'Fangen Sie immer geschlossen',
		'it': 'Inizia sempre chiusa',
		'ko': '항상 닫기 시작하십시오',
		'ja': '常に閉じ始めてください',
		'pt': 'Sempre comece fechado',
		'pt-br': 'Sempre comece fechado',
		'es': 'Siempre comienza cerrado',
		'ru': 'Всегда начинайте закрыться',
		'tr': 'Her zaman kapalı başlayın',
	},
	'SETTING_MENU_STATE_3': {
		'en': 'Always Start Opened',
		'zh-CN': '总是开始打开',
		'zh-TW': '總是開始打開',
		'fr': 'Commencez toujours à ouvrir',
		'de': 'Immer anfangen geöffnet',
		'it': 'Inizia sempre aperta',
		'ko': '항상 열기 시작하십시오',
		'ja': '常に開始します',
		'pt': 'Sempre comece aberto',
		'pt-br': 'Sempre comece aberto',
		'es': 'Siempre empieza a abrir',
		'ru': 'Всегда начинайте открываться',
		'tr': 'Daima Açılmaya Başla',
	},
	'FILTER_MODE': {
		'en': 'Filter Mode Active!',
		'zh-CN': '过滤模式活动！',
		'zh-TW': '過濾模式活動！',
		'fr': 'Mode filtre Actif!',
		'de': 'Filtermodus aktiv!',
		'it': 'Modalità filtro attivo!',
		'ko': '필터 모드 활성!',
		'ja': 'フィルターモードアクティブ！',
		'pt': 'Modo de filtro ativo!',
		'pt-br': 'Modo de filtro ativo!',
		'es': '¡Modo de filtro activo!',
		'ru': 'Режим фильтра Active!',
		'tr': 'Filtre modu etkin!',
	},
	'MASS_FILTER': {
		'en': 'Mass filter icons?',
		'zh-CN': '质量过滤器图标？',
		'zh-TW': '質量過濾器圖標？',
		'fr': 'Icônes de filtre de masse?',
		'de': 'Massenfiltersymbole?',
		'it': 'Icone del filtro di massa?',
		'ko': '대량 필터 아이콘?',
		'ja': 'マスフィルターアイコン？',
		'pt': 'Ícones do filtro de massa?',
		'pt-br': 'Ícones do filtro de massa?',
		'es': 'Iconos de filtro de masa?',
		'ru': 'Массовые значки?',
		'tr': 'Kütle filtre simgeleri?',
	},
	'BOOSTS': {
		'en': 'Boosts',
		'zh-CN': '提升',
		'zh-TW': '提升',
		'fr': 'Augmentation',
		'de': 'Steigert',
		'it': 'Aumenta',
		'ko': '부스트',
		'ja': 'ブースト',
		'pt': 'Aumenta',
		'pt-br': 'Aumenta',
		'es': 'Impulso',
		'ru': 'Повышает',
		'tr': 'Artış',
	},
	'FILTER': {
		'en': 'Filter',
		'zh-CN': '筛选',
		'zh-TW': '篩選',
		'fr': 'Filtre',
		'de': 'Filter',
		'it': 'Filtro',
		'ko': '필터',
		'ja': 'フィルター',
		'pt': 'Filtro',
		'pt-br': 'Filtro',
		'es': 'Filtrar',
		'ru': 'Фильтр',
		'tr': 'Filtre',
	},
	'GLOBAL': {
		'en': 'Global',
		'zh-CN': '全球的',
		'zh-TW': '全球的',
		'fr': 'Mondial',
		'de': 'Global',
		'it': 'Globale',
		'ko': '글로벌',
		'ja': 'グローバル',
		'pt': 'Global',
		'pt-br': 'Global',
		'es': 'Global',
		'ru': 'Глобальный',
		'tr': 'Küresel',
	},
	'OBSTACLES': {
		'en': 'Obstacles',
		'zh-CN': '障碍',
		'zh-TW': '障礙',
		'fr': 'Obstacles',
		'de': 'Hindernisse',
		'it': 'Ostacoli',
		'ko': '장애물',
		'ja': '障害物',
		'pt': 'Obstáculos',
		'pt-br': 'Obstáculos',
		'es': 'Obstáculos',
		'ru': 'Препятствия',
		'tr': 'Engeller',
	},
	'PETSPURCHASES': {
		'en': 'Purchases & Pets',
		'zh-CN': '购买和宠物',
		'zh-TW': '購買和寵物',
		'fr': 'Achats et animaux de compagnie',
		'de': 'Einkäufe und Haustiere',
		'it': 'Acquisti e animali domestici',
		'ko': '구매 및 애완 동물',
		'ja': '購入とペット',
		'pt': 'Compras e animais de estimação',
		'pt-br': 'Compras e animais de estimação',
		'es': 'Compras y mascotas',
		'ru': 'Покупки и домашние животные',
		'tr': 'Alımlar ve Evcil hayvanlar',
	},
	'DELETE_DATA_2': {
		'en': 'This cannot be undone!',
		'zh-CN': '这不能被撤消！',
		'zh-TW': '這不能被撤消！',
		'fr': 'Ça ne peut pas être annulé!',
		'de': 'Das kann nicht rückgängig gemacht werden!',
		'it': 'Questo non può essere annullato!',
		'ko': '이 취소 할 수 없습니다!',
		'ja': 'これは、元に戻すことはできません！',
		'pt': 'Isto não pode ser desfeito!',
		'pt-br': 'Isto não pode ser desfeito!',
		'es': '¡Esto no se puede deshacer!',
		'ru': 'Это не может быть отменено!',
		'tr': 'Bu geri alınamaz!',
	},
	'FILTERING_DESC_3': {
		'en': 'When Mass Filtering is Enabled, all filtered icons will be synced with the clicked Icon.',
		'zh-CN': '启用批量过滤后，所有过滤的图标都将与点击的图标同步。',
		'zh-TW': '當啟用質量過濾時，所有過濾的圖標將與單擊圖標同步。',
		'fr': 'Lorsque le filtrage de masse est activé, toutes les icônes filtrées sont synchronisées avec l\'icône cliquée.',
		'de': 'Wenn die Massenfilterung aktiviert ist, werden alle gefilterten Symbole mit dem angeklickten Symbol synchronisiert.',
		'it': 'Quando il filtro di massa è abilitato, tutte le icone filtrate saranno sincronizzate con l\'icona cliccata.',
		'ko': '대량 필터링이 활성화되면 필터링된 모든 아이콘이 클릭한 아이콘과 동기화됩니다.',
		'ja': '一括フィルタリングを有効にすると、フィルタリングされたすべてのアイコンがクリックしたアイコンに同期されます。',
		'pt': 'Quando a Filtragem em massa está activada, todos os ícones filtrados serão sincronizados com o ícone clicado.',
		'pt-br': 'Quando a filtragem em massa estiver ativada, todos os ícones filtrados serão sincronizados com o ícone clicado.',
		'es': 'Cuando el Filtrado Masivo está Activado, todos los iconos filtrados se sincronizarán con el Icono pulsado.',
		'ru': 'Если включена массовая фильтрация, все отфильтрованные значки будут синхронизированы с выбранным значком.',
		'tr': 'Toplu Filtreleme Etkinleştirildiğinde, filtrelenen tüm simgeler tıklanan Simge ile senkronize edilecektir.',
	},
	'AUTOMATICALLY_HIDE': {
		'en': 'This category will be hidden if you own everything',
		'zh-CN': '如果您拥有一切，此类别将被隐藏',
		'zh-TW': '如果您擁有一切，此類別將被隱藏',
		'fr': 'Cette catégorie sera cachée si vous possédez tout',
		'de': 'Diese Kategorie wird versteckt, wenn Sie alles besitzen',
		'it': 'Questa categoria sarà nascosta se possiedi tutto',
		'ko': '이 카테고리는 모든 것을 소유 한 경우 숨겨집니다',
		'ja': 'このカテゴリは、すべてを所有している場合に非表示になります',
		'pt': 'Esta categoria estará oculta se você possui tudo',
		'pt-br': 'Esta categoria estará oculta se você possui tudo',
		'es': 'Esta categoría estará oculta si es dueño de todo',
		'ru': 'Эта категория будет скрыта, если у вас есть все',
		'tr': 'Her şeye sahipseniz bu kategori gizlenecektir',
	},
	'SETTING_AGILITY_COST': {
		'en': 'Use these when updating Agility Obstacle Backgrounds?',
		'zh-CN': '更新敏捷障碍背景时使用这些？',
		'zh-TW': '更新敏捷障礙背景時使用這些？',
		'fr': 'Utilisez-les lors de la mise à jour des arrière-plans d\'obstacles d\'agilité?',
		'de': 'Verwenden Sie diese, wenn Sie agilitätsbedingte Hindernishintergründe aktualisieren?',
		'it': 'Usarli durante l\'aggiornamento degli sfondi di ostacoli dell\'agilità?',
		'ko': '민첩성 장애물 배경을 업데이트 할 때 이것을 사용하십니까?',
		'ja': '俊敏性の障害物の背景を更新するときにこれらを使用しますか？',
		'pt': 'Use -os ao atualizar os antecedentes do obstáculo da agilidade?',
		'pt-br': 'Use -os ao atualizar os antecedentes do obstáculo da agilidade?',
		'es': '¿Usarlos al actualizar los fondos de obstáculos de agilidad?',
		'ru': 'Используйте их при обновлении фона препятствий на гибели?',
		'tr': 'Çeviklik Engel Arka Planlarını güncellerken bunları kullanın mı?',
	},
	'EQUIPMENT_INFO': {
		'en': 'Equipment',
		'zh-CN': '设备',
		'zh-TW': '裝置',
		'fr': 'Équipement',
		'de': 'Ausrüstung',
		'it': 'Attrezzatura',
		'ko': '장비',
		'ja': '装置',
		'pt': 'Equipamento',
		'pt-br': 'Equipamento',
		'es': 'Equipo',
		'ru': 'Оборудование',
		'tr': 'Teçhizat',
	},
	'OTHERS': {
		'en': 'Others',
		'zh-CN': '其他的',
		'zh-TW': '其他的',
		'fr': 'Autres',
		'de': 'Andere',
		'it': 'Altri',
		'ko': '기타',
		'ja': 'その他',
		'pt': 'Outros',
		'pt-br': 'Outros',
		'es': 'Otros',
		'ru': 'Другие',
		'tr': 'Diğerleri',
	},
	'INACTIVE': {
		'en': 'This is currently Inactive',
		'zh-CN': '这是当前不活动的',
		'zh-TW': '這是當前不活動的',
		'fr': 'Ceci est actuellement inactif',
		'de': 'Dies ist derzeit inaktiv',
		'it': 'Questo è attualmente inattivo',
		'ko': '이것은 현재 비활성입니다',
		'ja': 'これは現在非アクティブです',
		'pt': 'Isso está atualmente inativo',
		'pt-br': 'Isso está atualmente inativo',
		'es': 'Esto está actualmente inactivo',
		'ru': 'Это в настоящее время неактивно',
		'tr': 'Bu şu anda aktif değil',
	},
	'SETTING_ALLBUTX': {
		'en': 'Keep this amount of Consumables in your bank',
		'zh-CN': '在您的银行中保留这么多的消耗品',
		'zh-TW': '在您的銀行中保留這麼多的消耗品',
		'fr': 'Gardez cette quantité de consommables dans votre banque',
		'de': 'Halten Sie diese Menge an Verbrauchsmaterialien in Ihrer Bank',
		'it': 'Mantieni questa quantità di materiali di consumo nella tua banca',
		'ko': '이 양의 소모품을 은행에 보관하십시오',
		'ja': 'この量の消耗品を銀行に保管してください',
		'pt': 'Mantenha essa quantidade de consumíveis em seu banco',
		'pt-br': 'Mantenha essa quantidade de consumíveis em seu banco',
		'es': 'Mantenga esta cantidad de consumibles en su banco',
		'ru': 'Держите эту сумму расходных материалов в вашем банке',
		'tr': 'Bu miktarda sarf malzemesini bankanızda saklayın',
	},
	'SETTING_ALLBUTX_DESC': {
		'en': 'The quantity on the Icon will be reduced by this value',
		'zh-CN': '图标上的数量将通过此值减少',
		'zh-TW': '圖標上的數量將通過此值減少',
		'fr': 'La quantité sur l\'icône sera réduite par cette valeur',
		'de': 'Die Menge des Symbols wird durch diesen Wert reduziert',
		'it': 'La quantità sull\'icona sarà ridotta da questo valore',
		'ko': '아이콘의 수량은이 값에 의해 감소됩니다.',
		'ja': 'アイコンの数量はこの値によって減少します',
		'pt': 'A quantidade no ícone será reduzida por este valor',
		'pt-br': 'A quantidade no ícone será reduzida por este valor',
		'es': 'La cantidad en el icono se reducirá con este valor',
		'ru': 'Количество на значке будет уменьшено этим значением',
		'tr': 'Simgedeki miktar bu değerle azaltılacaktır',
	},
	'POSITIVE': {
		'en': 'Positive',
		'zh-CN': '积极的',
		'zh-TW': '積極的',
		'fr': 'Positif',
		'de': 'Positiv',
		'it': 'Positivo',
		'ko': '긍정적인',
		'ja': 'ポジティブ',
		'pt': 'Positivo',
		'pt-br': 'Positivo',
		'es': 'Positivo',
		'ru': 'Положительный',
		'tr': 'Pozitif',
	},
	'NEGATIVE': {
		'en': 'Negative',
		'zh-CN': '消极的',
		'zh-TW': '消極的',
		'fr': 'Négatif',
		'de': 'Negativ',
		'it': 'Negativo',
		'ko': '부정적인',
		'ja': 'ネガティブ',
		'pt': 'Negativo',
		'pt-br': 'Negativo',
		'es': 'Negativo',
		'ru': 'Отрицательный',
		'tr': 'Olumsuz',
	},
	'FILTER_BG': {
		'en': 'Blue Background',
		'zh-CN': '蓝色背景',
		'zh-TW': '藍色背景',
		'fr': 'Fond bleu',
		'de': 'Blauer Hintergrund',
		'it': 'Sfondo blu',
		'ko': '파란색 배경',
		'ja': '青い背景',
		'pt': 'Fundo azul',
		'pt-br': 'Fundo azul',
		'es': 'Fondo azul',
		'ru': 'Синий фон',
		'tr': 'Mavi arka plan',
	},
	'FILTERED_ICON': {
		'en': 'This icon is filtered',
		'zh-CN': '此图标已过滤',
		'zh-TW': '此圖標已過濾',
		'fr': 'Cette icône est filtrée',
		'de': 'Dieses Symbol wird gefiltert',
		'it': 'Questa icona è filtrata',
		'ko': '이 아이콘은 필터링됩니다',
		'ja': 'このアイコンはフィルタリングされています',
		'pt': 'Este ícone é filtrado',
		'pt-br': 'Este ícone é filtrado',
		'es': 'Este icono se filtra',
		'ru': 'Этот значок фильтруется',
		'tr': 'Bu simge filtrelenir',
	},
	'PASSIVE': {
		'en': 'This item is in the Passive Slot',
		'zh-CN': '此项目在被动插槽中',
		'zh-TW': '此項目在被動插槽中',
		'fr': 'Cet article est dans la fente passive',
		'de': 'Dieser Artikel befindet sich im passiven Slot',
		'it': 'Questo articolo è nella fessura passiva',
		'ko': '이 항목은 수동 슬롯에 있습니다',
		'ja': 'このアイテムはパッシブスロットにあります',
		'pt': 'Este item está no slot passivo',
		'pt-br': 'Este item está no slot passivo',
		'es': 'Este artículo está en la ranura pasiva',
		'ru': 'Этот предмет находится в пассивном слоте',
		'tr': 'Bu öğe pasif yuvada',
	},
};