export const lang = {
	'RESET': {
		'en': 'Reset',
		'zh-CN': '重置',
		'zh-TW': '重置',
		'fr': 'Réinitialiser',
		'de': 'Zurücksetzen',
		'it': 'Ripristina',
		'ko': '초기화',
		'ja': 'リセット',
		'pt': 'Reiniciar',
		'pt-br': 'Reiniciar',
		'es': 'Reiniciar',
		'ru': 'Перезагрузить',
		'tr': 'Sıfırla',
	},
	'PRESETS': {
		'en': 'Presets',
		'zh-CN': '预置',
		'zh-TW': '预置',
		'fr': 'Préconfigurations',
		'de': 'Voreinstellungen',
		'it': 'Preimpostazioni',
		'ko': '사전 설정',
		'ja': 'プリセット',
		'pt': 'Predefinições',
		'pt-br': 'Predefinições',
		'es': 'Preajustes',
		'ru': 'Пресеты',
		'tr': 'Ön ayarlar',
	},
	'BOOSTS': {
		'en': 'Boosts',
		'zh-CN': '提升',
		'zh-TW': '提升',
		'fr': 'Augmentation',
		'de': 'Steigert',
		'it': 'Aumenta',
		'ko': '부스트',
		'ja': 'ブースト',
		'pt': 'Aumenta',
		'pt-br': 'Aumenta',
		'es': 'Impulso',
		'ru': 'Повышает',
		'tr': 'Artış',
	},
	'FILTER': {
		'en': 'Filter',
		'zh-CN': '筛选',
		'zh-TW': '篩選',
		'fr': 'Filtre',
		'de': 'Filter',
		'it': 'Filtro',
		'ko': '필터',
		'ja': 'フィルター',
		'pt': 'Filtro',
		'pt-br': 'Filtro',
		'es': 'Filtrar',
		'ru': 'Фильтр',
		'tr': 'Filtre',
	},
	'OTHERS': {
		'en': 'Others',
		'zh-CN': '其他的',
		'zh-TW': '其他的',
		'fr': 'Autres',
		'de': 'Andere',
		'it': 'Altri',
		'ko': '기타',
		'ja': 'その他',
		'pt': 'Outros',
		'pt-br': 'Outros',
		'es': 'Otros',
		'ru': 'Другие',
		'tr': 'Diğerleri',
	},
	'CONSTELLATION': {
		'en': 'Constellation',
		'zh-CN': '星座',
		'zh-TW': '星座',
		'fr': 'Constellation',
		'de': 'Konstellation',
		'it': 'Costellazione',
		'ko': '별자리',
		'ja': '星座',
		'pt': 'constelação',
		'pt-br': 'constelação',
		'es': 'Constelación',
		'ru': 'Созвездие',
		'tr': 'takımyıldız',
	},
	'PURCHASES': {
		'en': 'Purchases',
		'zh-CN': '购买',
		'zh-TW': '購買',
		'fr': 'Achats',
		'de': 'Einkäufe',
		'it': 'Acquisti',
		'ko': '구매',
		'ja': '購入品',
		'pt': 'Compras',
		'pt-br': 'Compras',
		'es': 'Compras',
		'ru': 'Покупки',
		'tr': 'Satın almalar',
	},
	'SYNERGIES': {
		'en': 'Synergies',
		'zh-CN': '协同效应',
		'zh-TW': '綜效',
		'fr': 'Synergies',
		'de': 'Synergien',
		'it': 'Sinergie',
		'ko': '시너지 효과',
		'ja': '相乗効果',
		'pt': 'Sinergias',
		'pt-br': 'Sinergias',
		'es': 'Sinergias',
		'ru': 'Синергия',
		'tr': 'Sinerjiler',
	},
	'RELICS': {
		'en': 'Relics',
		'zh-CN': '代遗物',
		'zh-TW': '遺跡',
		'fr': 'Reliques',
		'de': 'Relikte',
		'it': 'Reliquie',
		'ko': '유물',
		'ja': '遺物',
		'pt': 'Relíquias',
		'pt-br': 'Relíquias',
		'es': 'reliquias',
		'ru': 'Реликвии',
		'tr': 'kalıntılar',
	},
	'POSITIVE': {
		'en': 'Positive',
		'zh-CN': '积极的',
		'zh-TW': '積極的',
		'fr': 'Positif',
		'de': 'Positiv',
		'it': 'Positivo',
		'ko': '긍정적인',
		'ja': 'ポジティブ',
		'pt': 'Positivo',
		'pt-br': 'Positivo',
		'es': 'Positivo',
		'ru': 'Положительный',
		'tr': 'Pozitif',
	},
	'NEGATIVE': {
		'en': 'Negative',
		'zh-CN': '消极的',
		'zh-TW': '消極的',
		'fr': 'Négatif',
		'de': 'Negativ',
		'it': 'Negativo',
		'ko': '부정적인',
		'ja': 'ネガティブ',
		'pt': 'Negativo',
		'pt-br': 'Negativo',
		'es': 'Negativo',
		'ru': 'Отрицательный',
		'tr': 'Olumsuz',
	},
	'DEFAULT': {
		'en': 'Default',
		'zh-CN': '默认',
		'zh-TW': '預設',
		'fr': 'Défaut',
		'de': 'Standard',
		'it': 'Predefinito',
		'ko': '기본',
		'ja': 'デフォルト',
		'pt': 'Padrão',
		'pt-br': 'Padrão',
		'es': 'Por defecto',
		'ru': 'По умолчанию',
		'tr': 'Varsayılan',
	},
	'CUSTOM': {
		'en': 'Custom',
		'zh-CN': '风俗',
		'zh-TW': '風俗',
		'fr': 'Coutume',
		'de': 'Brauch',
		'it': 'Costume',
		'ko': '관습',
		'ja': 'カスタム',
		'pt': 'Personalizado',
		'pt-br': 'Personalizado',
		'es': 'Costumbre',
		'ru': 'Обычай',
		'tr': 'Gelenek',
	},
	'EDIT': {
		'en': 'Edit',
		'zh-CN': '编辑',
		'zh-TW': '編輯',
		'fr': 'Éditer',
		'de': 'Bearbeiten',
		'it': 'Modifica',
		'ko': '편집하다',
		'ja': '編集',
		'pt': 'Editar',
		'pt-br': 'Editar',
		'es': 'Editar',
		'ru': 'Редактировать',
		'tr': 'Düzenle',
	},
	'CHANCE': {
		'en': 'Chance:',
		'zh-CN': '机会：',
		'zh-TW': '機會：',
		'fr': 'Chance:',
		'de': 'Chance:',
		'it': 'Opportunità:',
		'ko': '가능성:',
		'ja': 'チャンス：',
		'pt': 'Chance:',
		'pt-br': 'Chance:',
		'es': 'Oportunidad:',
		'ru': 'Шанс:',
		'tr': 'Şans:',
	},
	'SEARCH': {
		'en': 'Search',
		'zh-CN': '搜索',
		'zh-TW': '搜尋',
		'fr': 'Recherche',
		'de': 'Suchen',
		'it': 'Ricerca',
		'ko': '찾다',
		'ja': '検索',
		'pt': 'Procurar',
		'pt-br': 'Procurar',
		'es': 'Buscar',
		'ru': 'Поиск',
		'tr': 'Arama Yapın',
	},
	'INACTIVE': {
		'en': 'This is currently inactive. All prior obstacles must be built for an obstacle to be active.',
		'zh-CN': '目前该功能处于非活动状态。必须先构建所有先前的障碍才能使障碍处于活动状态。',
		'zh-TW': '目前該功能處於非活動狀態。必須先建構所有先前的障礙才能使障礙處於活動狀態。',
		'fr': 'Ceci est actuellement inactif. Tous les obstacles antérieurs doivent être construits pour qu\'un obstacle soit actif.',
		'de': 'Dies ist derzeit inaktiv. Damit ein Hindernis aktiv ist, müssen alle vorherigen Hindernisse gebaut sein.',
		'it': 'Questo è attualmente inattivo. Tutti gli ostacoli precedenti devono essere costruiti affinché un ostacolo sia attivo.',
		'ko': '현재는 비활성화되어 있습니다. 장애물이 활성화되려면 이전의 모든 장애물을 건설해야 합니다.',
		'ja': 'これは現在非アクティブです。障害物をアクティブにするには、以前のすべての障害物を構築する必要があります。',
		'pt': 'No momento, isso está inativo. Todos os obstáculos anteriores devem ser construídos para que um obstáculo seja ativo.',
		'pt-br': 'No momento, isso está inativo. Todos os obstáculos anteriores devem ser construídos para que um obstáculo seja ativo.',
		'es': 'Esto está actualmente inactivo. Todos los obstáculos anteriores deben construirse para que un obstáculo esté activo.',
		'ru': 'В настоящее время это неактивно. Чтобы препятствие было активным, все предыдущие препятствия должны быть построены.',
		'tr': 'Bu şu anda etkin değil. Bir engelin aktif olabilmesi için önceki tüm engellerin inşa edilmesi gerekir.',
	},
	'PASSIVE': {
		'en': 'This item is in the Passive Slot.',
		'zh-CN': '该物品位于被动槽中。',
		'zh-TW': '該物品位於被動槽中。',
		'fr': 'Cet objet se trouve dans l\'emplacement passif.',
		'de': 'Dieser Gegenstand befindet sich im Passiv-Slot.',
		'it': 'Questo oggetto è nello slot passivo.',
		'ko': '이 아이템은 패시브 슬롯에 있습니다.',
		'ja': 'このアイテムはパッシブ スロットにあります。',
		'pt': 'Este item está no Slot Passivo.',
		'pt-br': 'Este item está no Slot Passivo.',
		'es': 'Este elemento está en la ranura pasiva.',
		'ru': 'Этот предмет находится в пассивном слоте.',
		'tr': 'Bu öğe Pasif Yuvadadır.',
	},
	'SELECT_OBSTACLE': {
		'en': 'Select Obstacle',
		'zh-CN': '选择障碍物',
		'zh-TW': '選擇障礙物',
		'fr': 'Sélectionnez un obstacle',
		'de': 'Wählen Sie Hindernis',
		'it': 'Seleziona Ostacolo',
		'ko': '장애물 선택',
		'ja': '障害物を選択してください',
		'pt': 'Selecione Obstáculo',
		'pt-br': 'Selecione Obstáculo',
		'es': 'Seleccionar obstáculo',
		'ru': 'Выберите Препятствие',
		'tr': 'Engel Seç',
	},
	'SELECT_SLOT': {
		'en': 'Select Slot',
		'zh-CN': '选择插槽',
		'zh-TW': '選擇插槽',
		'fr': 'Sélectionnez un emplacement',
		'de': 'Wählen Sie Steckplatz',
		'it': 'Seleziona Slot',
		'ko': '슬롯 선택',
		'ja': 'スロットの選択',
		'pt': 'Selecione o slot',
		'pt-br': 'Selecione o slot',
		'es': 'Seleccionar ranura',
		'ru': 'Выберите слот',
		'tr': 'Slot Seç',
	},
	'SELECT_POI': {
		'en': 'Select Point of Interest',
		'zh-CN': '选择兴趣点',
		'zh-TW': '選擇興趣點',
		'fr': 'Sélectionnez un point d\'intérêt',
		'de': 'Wählen Sie Sonderziel aus',
		'it': 'Seleziona Punto di interesse',
		'ko': '관심장소 선택',
		'ja': '興味のある場所を選択してください',
		'pt': 'Selecione o ponto de interesse',
		'pt-br': 'Selecione o ponto de interesse',
		'es': 'Seleccionar punto de interés',
		'ru': 'Выберите достопримечательность',
		'tr': 'İlgi Çekici Noktayı Seçin',
	},
	'HIDE_MODIFIERS': {
		'en': 'Hide Modifiers',
		'zh-CN': '隐藏修饰符',
		'zh-TW': '隱藏修飾符',
		'fr': 'Masquer les modificateurs',
		'de': 'Modifikatoren ausblenden',
		'it': 'Nascondi modificatori',
		'ko': '수정자 숨기기',
		'ja': '修飾子を隠す',
		'pt': 'Ocultar modificadores',
		'pt-br': 'Ocultar modificadores',
		'es': 'Ocultar modificadores',
		'ru': 'Скрыть модификаторы',
		'tr': 'Değiştiricileri Gizle',
	},
	'FILTER_MODE': {
		'en': 'Filter Mode Active!',
		'zh-CN': '过滤模式激活！',
		'zh-TW': '過濾模式激活！',
		'fr': 'Mode filtre actif !',
		'de': 'Filtermodus aktiv!',
		'it': 'Modalità filtro attiva!',
		'ko': '필터 모드 활성화!',
		'ja': 'フィルターモードが有効です!',
		'pt': 'Modo de filtro ativo!',
		'pt-br': 'Modo de filtro ativo!',
		'es': '¡Modo de filtro activo!',
		'ru': 'Режим фильтра активен!',
		'tr': 'Filtre Modu Aktif!',
	},
	'MASS_FILTER': {
		'en': 'Mass filter icons?',
		'zh-CN': '质量过滤器图标？',
		'zh-TW': '品質過濾器圖標？',
		'fr': 'Icônes de filtre de masse ?',
		'de': 'Massenfiltersymbole?',
		'it': 'Icone del filtro di massa?',
		'ko': '대량 필터 아이콘?',
		'ja': 'マスフィルターアイコン?',
		'pt': 'Ícones de filtro em massa?',
		'pt-br': 'Ícones de filtro em massa?',
		'es': '¿Iconos de filtro masivo?',
		'ru': 'Значки массового фильтра?',
		'tr': 'Kütle filtresi simgeleri?',
	},
	'LOCKED_SYNERGY': {
		'en': 'This Synergy is not unlocked.',
		'zh-CN': '此协同作用尚未解锁。',
		'zh-TW': '此協同作用尚未解鎖。',
		'fr': 'Cette synergie n\'est pas débloquée.',
		'de': 'Diese Synergie ist nicht freigeschaltet.',
		'it': 'Questa sinergia non è sbloccata.',
		'ko': '이 시너지는 잠금 해제되지 않았습니다.',
		'ja': 'このシナジーはロック解除されていません。',
		'pt': 'Esta sinergia não está desbloqueada.',
		'pt-br': 'Esta sinergia não está desbloqueada.',
		'es': 'Esta Sinergia no está desbloqueada.',
		'ru': 'Эта синергия не разблокирована.',
		'tr': 'Bu Sinerjinin kilidi açılmamıştır.',
	},
	'NOT_ACTIVE': {
		'en': '${skillName} must be active',
		'zh-CN': '${skillName} 必须处于活动状态',
		'zh-TW': '${skillName} 必須處於作用中狀態',
		'fr': '${skillName} doit être actif',
		'de': '${skillName} muss aktiv sein',
		'it': '${skillName} deve essere attivo',
		'ko': '${skillName} 이(가) 활성화되어 있어야 합니다.',
		'ja': '${skillName} はアクティブである必要があります',
		'pt': '${skillName} deve estar ativo',
		'pt-br': '${skillName} deve estar ativo',
		'es': '${skillName} debe estar activo',
		'ru': '${skillName} должен быть активен',
		'tr': '${skillName} etkin olmalı',
	},
	'MASTERY_ACTION': {
		'en': 'An action with Mastery must be active.',
		'zh-CN': '精通的动作必须是活跃的。',
		'zh-TW': '精通的動作必須是活躍的。',
		'fr': 'Une action avec Maîtrise doit être active.',
		'de': 'Eine Aktion mit Meisterschaft muss aktiv sein.',
		'it': 'Un\'azione con Maestria deve essere attiva.',
		'ko': '숙달이 있는 행동은 활성화되어야 합니다.',
		'ja': 'マスタリーのあるアクションがアクティブである必要があります。',
		'pt': 'Uma ação com Maestria deve estar ativa.',
		'pt-br': 'Uma ação com Maestria deve estar ativa.',
		'es': 'Una acción con Maestría debe estar activa.',
		'ru': 'Действие с мастерством должно быть активным.',
		'tr': 'Ustalık içeren bir eylem aktif olmalıdır.',
	},
	'FILTERED_ICON': {
		'en': 'This item is filtered.',
		'zh-CN': '该项目已被过滤。',
		'zh-TW': '該項目已被過濾。',
		'fr': 'Cet élément est filtré.',
		'de': 'Dieser Artikel ist gefiltert.',
		'it': 'Questo elemento è filtrato.',
		'ko': '이 항목은 필터링되었습니다.',
		'ja': 'この項目はフィルタリングされています。',
		'pt': 'Este item é filtrado.',
		'pt-br': 'Este item é filtrado.',
		'es': 'Este artículo está filtrado.',
		'ru': 'Этот элемент отфильтрован.',
		'tr': 'Bu öğe filtrelendi.',
	},
	'SETTING_HEX_FORMAT': {
		'en': 'Format:',
		'zh-CN': '格式：',
		'zh-TW': '格式：',
		'fr': 'Format:',
		'de': 'Format:',
		'it': 'Formato:',
		'ko': '체재:',
		'ja': 'フォーマット：',
		'pt': 'Formatar:',
		'pt-br': 'Formatar:',
		'es': 'Formato:',
		'ru': 'Формат:',
		'tr': 'Biçim:',
	},
	'SETTING_FILTER': {
		'en': 'Mass filter by ID?',
		'zh-CN': '按 ID 进行质量过滤？',
		'zh-TW': '按 ID 進行品質過濾？',
		'fr': 'Filtrer en masse par ID ?',
		'de': 'Massenfilter nach ID?',
		'it': 'Filtro di massa per ID?',
		'ko': 'ID로 대량 필터링을 하시겠습니까?',
		'ja': 'IDによるマスフィルター?',
		'pt': 'Filtrar em massa por ID?',
		'pt-br': 'Filtrar em massa por ID?',
		'es': '¿Filtro masivo por ID?',
		'ru': 'Массовый фильтр по ID?',
		'tr': 'Kimliğe göre toplu filtre?',
	},
	'SETTING_FILTER_HINT': {
		'en': 'Prevents icons that have these phrases in their ID from being created. Works for all icon categories. Separate each entry with a comma.',
		'zh-CN': '防止创建 ID 中包含这些短语的图标。适用于所有图标类别。用逗号分隔每个条目。',
		'zh-TW': '防止在建立 ID 中包含這些短語的圖示。適用於所有圖示類別。用逗號分隔每個條目。',
		'fr': 'Empêche la création d\'icônes comportant ces expressions dans leur identifiant. Fonctionne pour toutes les catégories d\'icônes. Séparez chaque entrée par une virgule.',
		'de': 'Verhindert, dass Symbole erstellt werden, deren ID diese Phrasen enthält. Funktioniert für alle Symbolkategorien. Trennen Sie jeden Eintrag durch ein Komma.',
		'it': 'Impedisce la creazione di icone che contengono queste frasi nel loro ID. Funziona con tutte le categorie di icone. Separa ogni voce con una virgola.',
		'ko': 'ID에 이러한 문구가 포함된 아이콘이 생성되지 않도록 합니다. 모든 아이콘 카테고리에서 작동합니다. 각 항목을 쉼표로 구분하세요.',
		'ja': 'ID にこれらの語句が含まれるアイコンが作成されないようにします。すべてのアイコン カテゴリで機能します。各エントリはカンマで区切ります。',
		'pt': 'Impede a criação de ícones que tenham essas frases em seu ID. Funciona para todas as categorias de ícones. Separe cada entrada com uma vírgula.',
		'pt-br': 'Impede a criação de ícones que tenham essas frases em seu ID. Funciona para todas as categorias de ícones. Separe cada entrada com uma vírgula.',
		'es': 'Evita que se creen íconos que tengan estas frases en su ID. Funciona para todas las categorías de iconos. Separe cada entrada con una coma.',
		'ru': 'Предотвращает создание значков, в идентификаторе которых есть эти фразы. Работает для всех категорий значков. Разделяйте каждую запись запятой.',
		'tr': 'Kimliklerinde bu ifadeleri içeren simgelerin oluşturulmasını engeller. Tüm simge kategorileri için çalışır. Her girişi virgülle ayırın.',
	},
	'REQUIRES_RESTART': {
		'en': 'Requires a restart to take effect.',
		'zh-CN': '需要重启才能生效。',
		'zh-TW': '需要重啟才能生效。',
		'fr': 'Nécessite un redémarrage pour prendre effet.',
		'de': 'Erfordert einen Neustart, um wirksam zu werden.',
		'it': 'Richiede un riavvio per avere effetto.',
		'ko': '적용하려면 다시 시작해야 합니다.',
		'ja': '有効にするには再起動が必要です。',
		'pt': 'Requer uma reinicialização para entrar em vigor.',
		'pt-br': 'Requer uma reinicialização para entrar em vigor.',
		'es': 'Requiere un reinicio para que surta efecto.',
		'ru': 'Требуется перезагрузка, чтобы изменения вступили в силу.',
		'tr': 'Etkili olması için yeniden başlatma gerekir.',
	},
	'CREATE_PRESET': {
		'en': 'Create a Preset',
		'zh-CN': '创建预设',
		'zh-TW': '建立預設',
		'fr': 'Créer un préréglage',
		'de': 'Erstellen Sie eine Voreinstellung',
		'it': 'Crea una preimpostazione',
		'ko': '사전 설정 만들기',
		'ja': 'プリセットを作成する',
		'pt': 'Crie uma predefinição',
		'pt-br': 'Crie uma predefinição',
		'es': 'Crear un preajuste',
		'ru': 'Создать пресет',
		'tr': 'Ön Ayar Oluştur',
	},
	'SUPERIOR_ONLY': {
		'en': '(Superior only)',
		'zh-CN': '（仅限卓越）',
		'zh-TW': '（僅限卓越）',
		'fr': '(Supérieur seulement)',
		'de': '(Nur Superior)',
		'it': '(Solo superiore)',
		'ko': '(슈페리어 전용)',
		'ja': '(スーペリアのみ)',
		'pt': '(Somente superiores)',
		'pt-br': '(Somente superiores)',
		'es': '(Solo superiores)',
		'ru': '(Только для Превосходная)',
		'tr': '(Yalnızca Superior)',
	},
	'NO_REALM': {
		'en': 'No Realm',
		'zh-CN': '不国度',
		'zh-TW': '不領域',
		'fr': 'Aucun royaume',
		'de': 'Kein Reich',
		'it': 'Nessun regno',
		'ko': '영역 왕국',
		'ja': 'レルムなし',
		'pt': 'Sem reino',
		'pt-br': 'Sem reino',
		'es': 'Sin reino',
		'ru': 'Нет Царство',
		'tr': 'Diyar Yok',
	},
	'FILLER_OBSTACLE': {
		'en': 'Filler Obstacle',
		'zh-CN': '填充物障碍',
		'zh-TW': '填充物障礙',
		'fr': 'Obstacle de remplissage',
		'de': 'Füller-Hindernis',
		'it': 'Ostacolo del riempitivo',
		'ko': '필러 장애물',
		'ja': 'フィラー障害物',
		'pt': 'Obstáculo de preenchimento',
		'pt-br': 'Obstáculo de preenchimento',
		'es': 'Obstáculo de relleno',
		'ru': 'Наполнитель Препятствие',
		'tr': 'Dolgu Engeli',
	},
	'FILLER_OBSTACLE_DESC': {
		'en': 'A Filler Obstacle allows for switching obstacle tiers when a skill does not have that tier. These can be disabled in the mod settings.',
		'zh-CN': '当技能没有该层时，填充障碍允许切换障碍层。这些可以在模组设置中禁用。',
		'zh-TW': '當技能沒有該層時，填充障礙允許切換障礙層。這些可以在模組設定中停用。',
		'fr': 'Un obstacle de remplissage permet de changer de niveau d\'obstacle lorsqu\'une compétence n\'a pas ce niveau. Ceux-ci peuvent être désactivés dans les paramètres du mod.',
		'de': 'Ein Füllhindernis ermöglicht den Wechsel der Hindernisstufe, wenn eine Fertigkeit diese Stufe nicht hat. Diese können in den Mod-Einstellungen deaktiviert werden.',
		'it': 'Un ostacolo riempitivo consente di cambiare livello di ostacolo quando un\'abilità non ha quel livello. Questi possono essere disabilitati nelle impostazioni della mod.',
		'ko': '필러 장애물을 사용하면 스킬에 해당 계층이 없을 때 장애물 계층을 전환할 수 있습니다. 이는 모드 설정에서 비활성화할 수 있습니다.',
		'ja': 'フィラー障害物を使用すると、スキルに障害物の層がない場合にその層を切り替えることができます。これらはMOD設定で無効にすることができます。',
		'pt': 'Um Filler Obstacle permite alternar níveis de obstáculo quando uma habilidade não possui esse nível. Eles podem ser desativados nas configurações do mod.',
		'pt-br': 'Um Filler Obstacle permite alternar níveis de obstáculo quando uma habilidade não possui esse nível. Eles podem ser desativados nas configurações do mod.',
		'es': 'Un obstáculo de relleno permite cambiar de nivel de obstáculo cuando una habilidad no tiene ese nivel. Estos se pueden desactivar en la configuración del mod.',
		'ru': 'Препятствие-заполнитель позволяет переключать уровни препятствий, если навык не имеет этого уровня. Их можно отключить в настройках мода.',
		'tr': 'Doldurma Engeli, bir becerinin bu seviyeye sahip olmadığı durumlarda engel aşamalarının değiştirilmesine olanak tanır. Bunlar mod ayarlarında devre dışı bırakılabilir.',
	},
	'SETTING_SHOW_FILLER_OBSTACLE': {
		'en': 'Show Filler Obstacles?',
		'zh-CN': '显示填充障碍？',
		'zh-TW': '顯示填充障礙？',
		'fr': 'Afficher les obstacles de remplissage ?',
		'de': 'Füllhindernisse anzeigen?',
		'it': 'Mostra ostacoli del riempitivo?',
		'ko': '필러 장애물을 표시하시겠습니까?',
		'ja': 'フィラー障害物を表示しますか?',
		'pt': 'Mostrar obstáculos de preenchimento?',
		'pt-br': 'Mostrar obstáculos de preenchimento?',
		'es': '¿Mostrar obstáculos de relleno?',
		'ru': 'Показать препятствия-наполнители?',
		'tr': 'Dolgu Engelleri Gösterilsin mi?',
	},
	'SETTING_SHOW_FILLER_OBSTACLE_DESC': {
		'en': 'If a realm does not have an obstacle for a specific tier, a filler obstacle will be shown to allow changing that obstacle tier.',
		'zh-CN': '如果某个领域没有特定级别的障碍，则会显示填充障碍以允许更改该障碍级别。',
		'zh-TW': '如果某個領域沒有特定等級的障礙，則會顯示填滿障礙以允許變更該障礙等級。',
		'fr': 'Si un royaume n\'a pas d\'obstacle pour un niveau spécifique, un obstacle de remplissage sera affiché pour permettre de modifier ce niveau d\'obstacle.',
		'de': 'Wenn ein Reich kein Hindernis für eine bestimmte Stufe hat, wird ein Füllhindernis angezeigt, um die Änderung dieser Hindernisstufe zu ermöglichen.',
		'it': 'Se un reame non ha un ostacolo per un livello specifico, verrà mostrato un ostacolo riempitivo per consentire di modificare quel livello di ostacolo.',
		'ko': '영역에 특정 계층에 대한 장애물이 없는 경우 해당 장애물 계층을 변경할 수 있도록 필러 장애물이 표시됩니다.',
		'ja': 'レルムに特定の層の障害がない場合、その障害層を変更できるようにフィラー障害が表示されます。',
		'pt': 'Se um reino não tiver um obstáculo para um nível específico, um obstáculo de preenchimento será mostrado para permitir a alteração desse nível de obstáculo.',
		'pt-br': 'Se um reino não tiver um obstáculo para um nível específico, um obstáculo de preenchimento será mostrado para permitir a alteração desse nível de obstáculo.',
		'es': 'Si un reino no tiene obstáculos para un nivel específico, se mostrará un obstáculo de relleno para permitir cambiar ese nivel de obstáculo.',
		'ru': 'Если в мире нет препятствий для определенного уровня, будет показано препятствие-заполнитель, позволяющее изменить этот уровень препятствий.',
		'tr': 'Bir bölgenin belirli bir aşama için bir engeli yoksa, bu engel aşamasını değiştirmeye izin veren bir dolgu engeli gösterilecektir.',
	},
	'SETTING_FILTER_DESC': {
		'en': 'Filters everything this mod checks for.',
		'zh-CN': '过滤此 mod 检查的所有内容。',
		'zh-TW': '過濾此 mod 檢查的所有內容。',
		'fr': 'Filtre tout ce que ce mod vérifie.',
		'de': 'Filtert alles, wonach dieser Mod sucht.',
		'it': 'Filtra tutto ciò che controlla questa mod.',
		'ko': '이 모드가 확인하는 모든 것을 필터링합니다.',
		'ja': 'この MOD がチェックするすべてのものをフィルターします。',
		'pt': 'Filtra tudo o que este mod verifica.',
		'pt-br': 'Filtra tudo o que este mod verifica.',
		'es': 'Filtra todo lo que busca este mod.',
		'ru': 'Фильтрует все, что проверяет этот мод.',
		'tr': 'Bu modun kontrol ettiği her şeyi filtreler.',
	},
	'SETTING_RESET_DATA': {
		'en': 'Reset all filtered items?',
		'zh-CN': '重置所有过滤的项目？',
		'zh-TW': '重置所有過濾的項目？',
		'fr': 'Réinitialiser tous les éléments filtrés ?',
		'de': 'Alle gefilterten Elemente zurücksetzen?',
		'it': 'Reimpostare tutti gli elementi filtrati?',
		'ko': '필터링된 항목을 모두 재설정하시겠습니까?',
		'ja': 'フィルタリングされた項目をすべてリセットしますか?',
		'pt': 'Redefinir todos os itens filtrados?',
		'pt-br': 'Redefinir todos os itens filtrados?',
		'es': '¿Restablecer todos los elementos filtrados?',
		'ru': 'Сбросить все отфильтрованные элементы?',
		'tr': 'Filtrelenen tüm öğeler sıfırlansın mı?',
	},
	'SETTING_MENU_STATE': {
		'en': 'What state should the menu be in when loading a save?',
		'zh-CN': '加载保存时菜单应处于什么状态？',
		'zh-TW': '載入儲存時選單應處於什麼狀態？',
		'fr': 'Dans quel état doit être le menu lors du chargement d\'une sauvegarde ?',
		'de': 'In welchem ​​Zustand sollte sich das Menü beim Laden eines Speicherstandes befinden?',
		'it': 'In quale stato dovrebbe trovarsi il menu durante il caricamento di un salvataggio?',
		'ko': '저장 파일을 로드할 때 메뉴는 어떤 상태여야 합니까?',
		'ja': 'セーブデータをロードするとき、メニューはどの状態にあるべきですか?',
		'pt': 'Em que estado o menu deve estar ao carregar um salvamento?',
		'pt-br': 'Em que estado o menu deve estar ao carregar um salvamento?',
		'es': '¿En qué estado debe estar el menú al cargar un guardado?',
		'ru': 'В каком состоянии должно быть меню при загрузке сохранения?',
		'tr': 'Bir kayıt yüklenirken menü hangi durumda olmalıdır?',
	},
	'SETTING_MENU_STATE_1': {
		'en': 'Remember Previous State',
		'zh-CN': '记住之前的状态',
		'zh-TW': '記住之前的狀態',
		'fr': 'Mémoriser l\'état précédent',
		'de': 'Vorherigen Status merken',
		'it': 'Ricorda lo stato precedente',
		'ko': '이전 상태 기억',
		'ja': '以前の状態を記憶する',
		'pt': 'Lembre-se do estado anterior',
		'pt-br': 'Lembre-se do estado anterior',
		'es': 'Recordar estado anterior',
		'ru': 'Запомнить предыдущее состояние',
		'tr': 'Önceki Durumu Hatırla',
	},
	'SETTING_MENU_STATE_2': {
		'en': 'Always Start Closed',
		'zh-CN': '始终开始关闭',
		'zh-TW': '始終開始關閉',
		'fr': 'Toujours démarrer fermé',
		'de': 'Immer geschlossen starten',
		'it': 'Inizia sempre chiuso',
		'ko': '항상 시작은 닫혀 있음',
		'ja': '常に閉じて開始する',
		'pt': 'Sempre comece fechado',
		'pt-br': 'Sempre comece fechado',
		'es': 'Empezar siempre cerrado',
		'ru': 'Всегда начинать с закрытого',
		'tr': 'Daima Kapalı Başlat',
	},
	'SETTING_MENU_STATE_3': {
		'en': 'Always Start Opened',
		'zh-CN': '始终开始打开',
		'zh-TW': '始終開始打開',
		'fr': 'Toujours commencer ouvert',
		'de': 'Immer geöffnet starten',
		'it': 'Inizia sempre aperto',
		'ko': '항상 시작이 열려 있음',
		'ja': '常に開いた状態で開始します',
		'pt': 'Sempre comece aberto',
		'pt-br': 'Sempre comece aberto',
		'es': 'Empezar siempre abierto',
		'ru': 'Всегда начинать открытым',
		'tr': 'Daima Açık Başla',
	},
	'SETTING_REALM_STATE': {
		'en': 'What realm should be selected when loading a save?',
		'zh-CN': '加载存档时应选择哪个领域？',
		'zh-TW': '載入存檔時應選擇哪個領域？',
		'fr': 'Quel domaine faut-il sélectionner lors du chargement d\'une sauvegarde ?',
		'de': 'Welcher Realm sollte beim Laden eines Speicherstands ausgewählt werden?',
		'it': 'Quale regno dovrebbe essere selezionato quando si carica un salvataggio?',
		'ko': '저장 파일을 로드할 때 어떤 영역을 선택해야 합니까?',
		'ja': 'セーブデータをロードするときにどのレルムを選択する必要がありますか?',
		'pt': 'Qual reino deve ser selecionado ao carregar um save?',
		'pt-br': 'Qual reino deve ser selecionado ao carregar um save?',
		'es': '¿Qué reino se debe seleccionar al cargar un guardado?',
		'ru': 'Какой мир следует выбирать при загрузке сохранения?',
		'tr': 'Bir kaydetme yüklenirken hangi bölge seçilmelidir?',
	},
	'SETTING_REALM_STATE_1': {
		'en': 'Remember Previous Realm',
		'zh-CN': '记住上一个境界',
		'zh-TW': '記住上一個境界',
		'fr': 'Se souvenir du royaume précédent',
		'de': 'Erinnern Sie sich an das vorherige Reich',
		'it': 'Ricorda il regno precedente',
		'ko': '이전 영역 기억',
		'ja': '以前のレルムを記憶する',
		'pt': 'Lembre-se do reino anterior',
		'pt-br': 'Lembre-se do reino anterior',
		'es': 'Recuerda el reino anterior',
		'ru': 'Помните предыдущую реальность',
		'tr': 'Önceki Bölgeyi Hatırla',
	},
	'SETTING_REALM_STATE_2': {
		'en': 'Always Start No Realm',
		'zh-CN': '永远开始无境界',
		'zh-TW': '永遠開始無境界',
		'fr': 'Ne démarrez toujours aucun royaume',
		'de': 'Starte immer No Realm',
		'it': 'Inizia sempre Nessun regno',
		'ko': '항상 영역 없음 시작',
		'ja': '常にレルムを開始しない',
		'pt': 'Sempre comece sem reino',
		'pt-br': 'Sempre comece sem reino',
		'es': 'Siempre comience sin reino',
		'ru': 'Всегда начинать без мира',
		'tr': 'Her Zaman Hiçbir Bölgeyi Başlat',
	},
	'SETTING_REALM_STATE_3': {
		'en': 'Always Start Melvor',
		'zh-CN': '始终启动“Melvor”',
		'zh-TW': '始終啟動“Melvor”',
		'fr': 'Toujours démarrer Melvor',
		'de': 'Starten Sie immer Melvor',
		'it': 'Avvia sempre Melvor',
		'ko': '항상 Melvor 시작',
		'ja': '常に「Melvor」を起動します',
		'pt': 'Sempre comece Melvor',
		'pt-br': 'Sempre comece Melvor',
		'es': 'Empiece siempre con Melvor',
		'ru': 'Всегда начинайте Мелвор',
		'tr': 'Her Zaman Melvor\'u Başlat',
	},
	'SETTING_REALM_STATE_4': {
		'en': 'Always Start Abyssal',
		'zh-CN': '始终启动深渊',
		'zh-TW': '始終啟動深淵',
		'fr': 'Commencez toujours Abyssal',
		'de': 'Starten Sie immer Abyssal',
		'it': 'Inizia sempre Abissale',
		'ko': '항상 어비설을 시작하세요',
		'ja': '常に深淵を開始する',
		'pt': 'Sempre inicie o Abyssal',
		'pt-br': 'Sempre inicie o Abyssal',
		'es': 'Siempre comienza abisal',
		'ru': 'Всегда начинайте с Бездны',
		'tr': 'Daima Abyssal\'i Başlat',
	},
	'SETTING_AUTO_REALM': {
		'en': 'Automatically change Realms?',
		'zh-CN': '自动改变领域？',
		'zh-TW': '自動改變領域？',
		'fr': 'Changer automatiquement de royaume ?',
		'de': 'Realms automatisch wechseln?',
		'it': 'Cambiare automaticamente i regni?',
		'ko': '영역을 자동으로 변경하시겠습니까?',
		'ja': 'レルムを自動的に変更しますか?',
		'pt': 'Alterar reinos automaticamente?',
		'pt-br': 'Alterar reinos automaticamente?',
		'es': '¿Cambiar automáticamente los reinos?',
		'ru': 'Автоматически менять Realms?',
		'tr': 'Bölgeler otomatik olarak değiştirilsin mi?',
	},
	'SETTING_AUTO_REALM_HINT': {
		'en': 'When the game\'s realm is swapped, this will also swap the Menu\'s realm to match the new realm.',
		'zh-CN': '当游戏的领域被交换时，这也将交换菜单的领域以匹配新的领域。',
		'zh-TW': '當遊戲的領域被交換時，這也將交換選單的領域以匹配新的領域。',
		'fr': 'Lorsque le royaume du jeu est échangé, cela permutera également le royaume du menu pour qu\'il corresponde au nouveau royaume.',
		'de': 'Wenn der Realm des Spiels ausgetauscht wird, wird dadurch auch der Realm des Menüs getauscht, damit er mit dem neuen Realm übereinstimmt.',
		'it': 'Quando il regno del gioco viene scambiato, verrà scambiato anche il regno del menu per corrispondere al nuovo regno.',
		'ko': '게임의 영역이 교체되면 메뉴의 영역도 새 영역에 맞게 교체됩니다.',
		'ja': 'ゲームのレルムが交換されると、新しいレルムと一致するようにメニューのレルムも交換されます。',
		'pt': 'Quando o reino do jogo é trocado, o reino do Menu também será trocado para corresponder ao novo reino.',
		'pt-br': 'Quando o reino do jogo é trocado, o reino do Menu também será trocado para corresponder ao novo reino.',
		'es': 'Cuando se intercambia el reino del juego, esto también cambiará el reino del menú para que coincida con el nuevo reino.',
		'ru': 'Когда игровое пространство поменяется местами, это также поменяет место в меню, чтобы оно соответствовало новому царству.',
		'tr': 'Oyunun bölgesi değiştirildiğinde, bu aynı zamanda Menünün bölgesini de yeni bölgeye uyacak şekilde değiştirecektir.',
	},
	'SETTING_ALLBUTX': {
		'en': 'Keep this amount of Consumables and Potions in the Bank',
		'zh-CN': '将这些消耗品和药水保存在银行中',
		'zh-TW': '將這些消耗品和藥水保存在銀行中',
		'fr': 'Gardez cette quantité de consommables et de potions en banque',
		'de': 'Bewahren Sie diese Menge an Verbrauchsgütern und Tränken in der Bank auf',
		'it': 'Mantieni questa quantità di materiali di consumo e pozioni nella banca',
		'ko': '일정량의 소모품과 물약을 은행에 보관하세요.',
		'ja': 'この量の消耗品とポーションを銀行に保管してください',
		'pt': 'Mantenha esta quantidade de consumíveis e poções no banco',
		'pt-br': 'Mantenha esta quantidade de consumíveis e poções no banco',
		'es': 'Mantén esta cantidad de consumibles y pociones en el banco.',
		'ru': 'Храните это количество расходных материалов и зелий в банке.',
		'tr': 'Bu miktardaki Sarf Malzemelerini ve İksirleri Bankada tutun',
	},
	'SETTING_ALLBUTX_DESC_1': {
		'en': 'The quantity shown on the Icon will be reduced by this value.',
		'zh-CN': '图标上显示的数量将减少该值。',
		'zh-TW': '圖示上顯示的數量將減少該值。',
		'fr': 'La quantité affichée sur l\'Icône sera réduite de cette valeur.',
		'de': 'Die auf dem Icon angezeigte Menge wird um diesen Wert reduziert.',
		'it': 'La quantità mostrata sull\'icona verrà ridotta di questo valore.',
		'ko': '아이콘에 표시되는 수량은 이 값만큼 감소됩니다.',
		'ja': 'アイコンに表示される数量は、この値だけ減ります。',
		'pt': 'A quantidade mostrada no Ícone será reduzida neste valor.',
		'pt-br': 'A quantidade mostrada no Ícone será reduzida neste valor.',
		'es': 'La cantidad que se muestra en el Icono se verá reducida por este valor.',
		'ru': 'Количество, отображаемое на значке, будет уменьшено на это значение.',
		'tr': 'Simgede gösterilen miktar bu değer kadar azaltılacaktır.',
	},
	'SETTING_ALLBUTX_DESC_2': {
		'en': 'This will prevent Potions from being used when at this limit.',
		'zh-CN': '这将防止在达到此限制时使用药水。',
		'zh-TW': '這將防止在達到此限制時使用藥水。',
		'fr': 'Cela empêchera l\'utilisation des potions à cette limite.',
		'de': 'Dadurch wird verhindert, dass Tränke verwendet werden, wenn dieses Limit erreicht ist.',
		'it': 'Ciò impedirà l\'utilizzo delle Pozioni quando si raggiunge questo limite.',
		'ko': '이렇게 하면 이 한도에 도달하면 물약을 사용할 수 없게 됩니다.',
		'ja': 'これにより、この制限に達するとポーションが使用できなくなります。',
		'pt': 'Isso impedirá que Poções sejam usadas neste limite.',
		'pt-br': 'Isso impedirá que Poções sejam usadas neste limite.',
		'es': 'Esto evitará que se utilicen pociones cuando se alcance este límite.',
		'ru': 'Это предотвратит использование зелий при достижении этого предела.',
		'tr': 'Bu, İksirlerin bu sınırda kullanılmasını önleyecektir.',
	},
	'ITEM_DESC_1': {
		'en': 'This item is currently Equipped.',
		'zh-CN': '该物品目前已装备。',
		'zh-TW': '該物品目前已裝備。',
		'fr': 'Cet objet est actuellement équipé.',
		'de': 'Dieser Artikel ist derzeit ausgerüstet.',
		'it': 'Questo oggetto è attualmente equipaggiato.',
		'ko': '이 아이템은 현재 장착되어 있습니다.',
		'ja': 'このアイテムは現在装備されています。',
		'pt': 'Este item está atualmente Equipado.',
		'pt-br': 'Este item está atualmente Equipado.',
		'es': 'Este artículo está actualmente equipado.',
		'ru': 'Этот предмет в настоящее время экипирован.',
		'tr': 'Bu öğe şu anda Donanımlıdır.',
	},
	'ITEM_DESC_2': {
		'en': 'This item is in another Equipment set.',
		'zh-CN': '该物品位于另一套装备中。',
		'zh-TW': '該物品位於另一套裝備中。',
		'fr': 'Cet objet fait partie d\'un autre ensemble d\'équipement.',
		'de': 'Dieser Gegenstand ist in einem anderen Ausrüstungsset enthalten.',
		'it': 'Questo oggetto è in un altro set di equipaggiamento.',
		'ko': '이 아이템은 다른 장비 세트에 포함되어 있습니다.',
		'ja': 'このアイテムは別の装備セットに含まれています。',
		'pt': 'Este item está em outro conjunto de equipamentos.',
		'pt-br': 'Este item está em outro conjunto de equipamentos.',
		'es': 'Este artículo está en otro conjunto de equipo.',
		'ru': 'Этот предмет находится в другом наборе снаряжения.',
		'tr': 'Bu öğe başka bir Ekipman setindedir.',
	},
	'ITEM_DESC_3': {
		'en': 'You do not have this item.',
		'zh-CN': '您没有该商品。',
		'zh-TW': '您沒有該商品。',
		'fr': 'Vous n\'avez pas cet article.',
		'de': 'Sie haben diesen Artikel nicht.',
		'it': 'Non hai questo articolo.',
		'ko': '이 항목이 없습니다.',
		'ja': 'このアイテムはありません。',
		'pt': 'Você não possui este item.',
		'pt-br': 'Você não possui este item.',
		'es': 'No tienes este artículo.',
		'ru': 'У вас нет этого товара.',
		'tr': 'Bu öğeye sahip değilsiniz.',
	},
	'ITEM_DESC_4': {
		'en': 'This item is in the bank.',
		'zh-CN': '该物品在银行。',
		'zh-TW': '該物品在銀行。',
		'fr': 'Cet article est à la banque.',
		'de': 'Dieser Artikel befindet sich auf der Bank.',
		'it': 'Questo oggetto è in banca.',
		'ko': '이 항목은 은행에 있습니다.',
		'ja': 'この商品は銀行にあります。',
		'pt': 'Este item está no banco.',
		'pt-br': 'Este item está no banco.',
		'es': 'Este artículo está en el banco.',
		'ru': 'Этот предмет находится в банке.',
		'tr': 'Bu ürün bankada.',
	},
	'ITEM_DESC_5': {
		'en': 'You have more in the Bank.',
		'zh-CN': '你银行里还有更多钱。',
		'zh-TW': '你銀行還有更多錢。',
		'fr': 'Vous en avez plus à la banque.',
		'de': 'Sie haben mehr auf der Bank.',
		'it': 'Ne hai di più in banca.',
		'ko': '은행에 더 많은 것이 있습니다.',
		'ja': '銀行にはさらに多くのものがあります。',
		'pt': 'Você tem mais no banco.',
		'pt-br': 'Você tem mais no banco.',
		'es': 'Tienes más en el banco.',
		'ru': 'У вас есть еще в банке.',
		'tr': 'Bankada daha fazlası var.',
	},
	'ITEM_DESC_6': {
		'en': 'Clicking on an icon will equip the item into the main slot.',
		'zh-CN': '单击图标会将物品装备到主插槽中。',
		'zh-TW': '點擊圖示會將物品裝備到主插槽。',
		'fr': 'Cliquer sur une icône équipera l’objet dans l’emplacement principal.',
		'de': 'Durch Klicken auf ein Symbol wird der Gegenstand im Hauptslot ausgerüstet.',
		'it': 'Facendo clic su un\'icona l\'oggetto verrà equipaggiato nello slot principale.',
		'ko': '아이콘을 클릭하면 해당 아이템이 메인 슬롯에 장착됩니다.',
		'ja': 'アイコンをクリックすると、アイテムがメインスロットに装備されます。',
		'pt': 'Clicar em um ícone equipará o item no slot principal.',
		'pt-br': 'Clicar em um ícone equipará o item no slot principal.',
		'es': 'Al hacer clic en un ícono, se equipará el artículo en la ranura principal.',
		'ru': 'Нажатие на значок переместит предмет в основной слот.',
		'tr': 'Bir simgeye tıklamak, öğeyi ana yuvaya yerleştirecektir.',
	},
	'ITEM_DESC_7': {
		'en': 'Right Clicking (Long Hold on mobile) will Equip them into the secondary slot. If there are more than 2 slots, a menu will open.',
		'zh-CN': '右键单击（在移动设备上长按）会将它们装备到辅助插槽中。如果有超过 2 个插槽，则会打开一个菜单。',
		'zh-TW': '右鍵單擊（在行動裝置上長按）會將它們裝備到輔助插槽中。如果有超過 2 個插槽，則會開啟一個選單。',
		'fr': 'Un clic droit (maintien prolongé sur mobile) les équipera dans l\'emplacement secondaire. S\'il y a plus de 2 emplacements, un menu s\'ouvrira.',
		'de': 'Durch Klicken mit der rechten Maustaste (langes Halten auf dem Mobilgerät) werden sie im sekundären Slot ausgerüstet. Bei mehr als 2 Slots öffnet sich ein Menü.',
		'it': 'Facendo clic con il pulsante destro del mouse (tieni premuto a lungo sui dispositivi mobili) li equipaggerai nello slot secondario. Se sono presenti più di 2 slot, si aprirà un menu.',
		'ko': '마우스 오른쪽 버튼을 클릭(모바일에서는 길게 누르기)하면 보조 슬롯에 장착됩니다. 슬롯이 2개 이상인 경우 메뉴가 열립니다.',
		'ja': '右クリック (モバイルでは長押し) すると、それらを 2 番目のスロットに装備します。スロットが 2 つ以上ある場合は、メニューが開きます。',
		'pt': 'Clicar com o botão direito (segure longamente no celular) irá equipá-los no slot secundário. Se houver mais de 2 slots, um menu será aberto.',
		'pt-br': 'Clicar com o botão direito (segure longamente no celular) irá equipá-los no slot secundário. Se houver mais de 2 slots, um menu será aberto.',
		'es': 'Al hacer clic derecho (mantener presionado en dispositivos móviles) se los equipará en la ranura secundaria. Si hay más de 2 espacios, se abrirá un menú.',
		'ru': 'Щелчок правой кнопкой мыши (длительное удержание на мобильном телефоне) установит их во дополнительный слот. Если слотов больше 2, откроется меню.',
		'tr': 'Sağ Tıklama (Mobilde Uzun Tutma) onları ikincil yuvaya yerleştirecektir. 2\'den fazla yuva varsa bir menü açılacaktır.',
	},
	'ITEM_DESC_8': {
		'en': 'If the item is in another equipment set and no additional items are in the bank, the item will be unequipped from the other equipment set and into the current equipment set.',
		'zh-CN': '如果该物品在另一个装备集中，并且库中没有其他物品，则该物品将从其他装备集中取消装备并放入当前装备集中。',
		'zh-TW': '如果該物品在另一個裝備集中，且庫中沒有其他物品，則該物品將從其他裝備集中取消裝備並放入當前裝備集中。',
		'fr': 'Si l\'objet se trouve dans un autre ensemble d\'équipement et qu\'aucun objet supplémentaire n\'est dans la banque, l\'objet sera déséquipé de l\'autre ensemble d\'équipement et sera transféré dans l\'ensemble d\'équipement actuel.',
		'de': 'Befindet sich der Gegenstand in einem anderen Ausrüstungssatz und befinden sich keine weiteren Gegenstände in der Bank, wird der Gegenstand aus dem anderen Ausrüstungssatz entfernt und in den aktuellen Ausrüstungssatz aufgenommen.',
		'it': 'Se l\'oggetto si trova in un altro set di equipaggiamento e non ci sono oggetti aggiuntivi nella banca, l\'oggetto verrà tolto dall\'altro set di equipaggiamento e verrà inserito nel set di equipaggiamento attuale.',
		'ko': '해당 아이템이 다른 장비 세트에 있고 은행에 추가 아이템이 없다면 해당 아이템은 다른 장비 세트에서 제거되어 현재 장비 세트로 들어갑니다.',
		'ja': 'アイテムが別の装備セットにあり、バンクに追加のアイテムがない場合、アイテムは他の装備セットから装備解除され、現在の装備セットに追加されます。',
		'pt': 'Se o item estiver em outro conjunto de equipamentos e não houver itens adicionais no banco, o item será desequipado do outro conjunto de equipamentos e colocado no conjunto de equipamentos atual.',
		'pt-br': 'Se o item estiver em outro conjunto de equipamentos e não houver itens adicionais no banco, o item será desequipado do outro conjunto de equipamentos e colocado no conjunto de equipamentos atual.',
		'es': 'Si el artículo está en otro conjunto de equipos y no hay artículos adicionales en el banco, el artículo se desequipará del otro conjunto de equipos y se colocará en el conjunto de equipos actual.',
		'ru': 'Если предмет находится в другом наборе снаряжения и в банке нет дополнительных предметов, предмет будет перенесен из другого комплекта снаряжения в текущий комплект снаряжения.',
		'tr': 'Öğe başka bir ekipman setindeyse ve bankada ek öğe yoksa, öğe diğer ekipman setinden çıkarılarak mevcut ekipman setine aktarılacaktır.',
	},
	'POI_DESC_1': {
		'en': 'This is in another Map.',
		'zh-CN': '这是在另一张地图上的。',
		'zh-TW': '這是在另一張地圖上的。',
		'fr': 'C\'est dans une autre carte.',
		'de': 'Dies ist in einer anderen Karte.',
		'it': 'Questo è in un\'altra mappa.',
		'ko': '이것은 다른 지도에 있습니다.',
		'ja': 'これは別のマップにあります。',
		'pt': 'Isso está em outro mapa.',
		'pt-br': 'Isso está em outro mapa.',
		'es': 'Esto está en otro mapa.',
		'ru': 'Это на другой карте.',
		'tr': 'Bu başka bir Haritada.',
	},
	'OBSTACLE_DESC_1': {
		'en': 'This is currently built.',
		'zh-CN': '目前已建成。',
		'zh-TW': '目前已建成。',
		'fr': 'Ceci est actuellement construit.',
		'de': 'Dieses wird derzeit gebaut.',
		'it': 'Questo è attualmente costruito.',
		'ko': '이것은 현재 건설되었습니다.',
		'ja': 'これは現在構築されています。',
		'pt': 'Isso está construído atualmente.',
		'pt-br': 'Isso está construído atualmente.',
		'es': 'Este está actualmente construido.',
		'ru': 'В настоящее время это построено.',
		'tr': 'Bu şu anda inşa edilmiştir.',
	},
	'OBSTACLE_DESC_2': {
		'en': 'You can\'t afford this.',
		'zh-CN': '你买不起这个。',
		'zh-TW': '你買不起這個。',
		'fr': 'Vous ne pouvez pas vous le permettre.',
		'de': 'Das können Sie sich nicht leisten.',
		'it': 'Non puoi permettertelo.',
		'ko': '당신은 이것을 감당할 수 없습니다.',
		'ja': 'こんな余裕はありません。',
		'pt': 'Você não pode permitir isso.',
		'pt-br': 'Você não pode permitir isso.',
		'es': 'No puedes permitirte esto.',
		'ru': 'Вы не можете себе этого позволить.',
		'tr': 'Bunu karşılayamazsın.',
	},
	'OBSTACLE_DESC_3': {
		'en': 'You do not meet the level requirement.',
		'zh-CN': '您不符合级别要求。',
		'zh-TW': '您不符合級別要求。',
		'fr': 'Vous ne répondez pas au niveau requis.',
		'de': 'Sie erfüllen die Levelanforderung nicht.',
		'it': 'Non soddisfi i requisiti di livello.',
		'ko': '레벨 요구 사항을 충족하지 않습니다.',
		'ja': 'レベル要件を満たしていません。',
		'pt': 'Você não atende ao requisito de nível.',
		'pt-br': 'Você não atende ao requisito de nível.',
		'es': 'No cumples con el requisito de nivel.',
		'ru': 'Вы не соответствуете требованиям по уровню.',
		'tr': 'Seviye şartını karşılamıyorsunuz.',
	},
	'OBSTACLE_DESC_4': {
		'en': 'You meet all the requirements to build this.',
		'zh-CN': '您满足构建此项目的所有要求。',
		'zh-TW': '您滿足建置此專案的所有要求。',
		'fr': 'Vous remplissez toutes les conditions pour construire cela.',
		'de': 'Sie erfüllen alle Voraussetzungen, um dies zu bauen.',
		'it': 'Soddisfi tutti i requisiti per costruirlo.',
		'ko': '이를 구축하기 위한 모든 요구 사항을 충족합니다.',
		'ja': 'これを構築するための要件をすべて満たしています。',
		'pt': 'Você atende a todos os requisitos para construir isso.',
		'pt-br': 'Você atende a todos os requisitos para construir isso.',
		'es': 'Cumples con todos los requisitos para construir esto.',
		'ru': 'Вы соответствуете всем требованиям, чтобы построить это.',
		'tr': 'Bunu oluşturmak için tüm gereksinimleri karşılıyorsunuz.',
	},
	'OBSTACLE_DESC_5': {
		'en': 'Clicking the icon will open up a build menu.',
		'zh-CN': '单击该图标将打开构建菜单。',
		'zh-TW': '點擊該圖示將開啟建置選單。',
		'fr': 'Cliquer sur l\'icône ouvrira un menu de construction.',
		'de': 'Durch Klicken auf das Symbol wird ein Build-Menü geöffnet.',
		'it': 'Facendo clic sull\'icona si aprirà un menu di creazione.',
		'ko': '아이콘을 클릭하면 빌드 메뉴가 열립니다.',
		'ja': 'アイコンをクリックするとビルドメニューが開きます。',
		'pt': 'Clicar no ícone abrirá um menu de construção.',
		'pt-br': 'Clicar no ícone abrirá um menu de construção.',
		'es': 'Al hacer clic en el icono se abrirá un menú de compilación.',
		'ru': 'При нажатии на значок откроется меню сборки.',
		'tr': 'Simgeye tıklamak bir yapı menüsü açacaktır.',
	},
	'OBSTACLE_DESC_6': {
		'en': 'Right Clicking (Long Hold on Mobile) will open a menu with all other obstacles from the same tier.',
		'zh-CN': '右键单击（在移动设备上长按）将打开一个菜单，其中包含同一层的所有其他障碍物。',
		'zh-TW': '右鍵單擊（在行動裝置上長按）將開啟一個選單，其中包含同一層的所有其他障礙物。',
		'fr': 'Un clic droit (longue attente sur mobile) ouvrira un menu avec tous les autres obstacles du même niveau.',
		'de': 'Durch Klicken mit der rechten Maustaste (langes Halten auf dem Handy) wird ein Menü mit allen anderen Hindernissen derselben Stufe geöffnet.',
		'it': 'Facendo clic con il pulsante destro del mouse (tieni premuto a lungo su dispositivo mobile) si aprirà un menu con tutti gli altri ostacoli dello stesso livello.',
		'ko': '마우스 오른쪽 버튼을 클릭(모바일에서 길게 누르기)하면 동일한 계층의 다른 모든 장애물이 포함된 메뉴가 열립니다.',
		'ja': '右クリック (モバイルでは長押し) すると、同じ層の他のすべての障害物を含むメニューが開きます。',
		'pt': 'Clicar com o botão direito (segure longamente no celular) abrirá um menu com todos os outros obstáculos do mesmo nível.',
		'pt-br': 'Clicar com o botão direito (segure longamente no celular) abrirá um menu com todos os outros obstáculos do mesmo nível.',
		'es': 'Al hacer clic derecho (mantener presionado en el móvil) se abrirá un menú con todos los demás obstáculos del mismo nivel.',
		'ru': 'Щелчок правой кнопкой мыши (длительное удержание на мобильном устройстве) откроет меню со всеми остальными препятствиями того же уровня.',
		'tr': 'Sağ Tıklama (Mobilde Uzun Tutma), aynı seviyedeki diğer tüm engellerin bulunduğu bir menü açacaktır.',
	},
	'OTHER_DESC_1': {
		'en': 'You can\'t purchase this or the pet is not owned.',
		'zh-CN': '您无法购买该宠物，或者该宠物不属于您。',
		'zh-TW': '您無法購買該寵物，或該寵物不屬於您。',
		'fr': 'Vous ne pouvez pas l\'acheter ou l\'animal n\'appartient pas.',
		'de': 'Sie können dies nicht kaufen oder das Haustier gehört nicht.',
		'it': 'Non puoi acquistarlo o l\'animale non è di proprietà.',
		'ko': '구매하실 수 없습니다. 그렇지 않으면 애완동물을 소유하고 있지 않습니다.',
		'ja': 'これを購入できないか、ペットが飼われていません。',
		'pt': 'Você não pode comprar isso ou o animal não é seu.',
		'pt-br': 'Você não pode comprar isso ou o animal não é seu.',
		'es': 'No puedes comprar esto o la mascota no es de su propiedad.',
		'ru': 'Вы не можете купить это, или домашнее животное не является собственностью.',
		'tr': 'Bunu satın alamazsınız veya evcil hayvanın mülkiyeti yoktur.',
	},
	'PURCHASE_DESC_1': {
		'en': 'You have all the requirements to purchase this.',
		'zh-CN': '您满足购买此产品的所有要求。',
		'zh-TW': '您滿足購買此產品的所有要求。',
		'fr': 'Vous avez toutes les conditions requises pour l\'acheter.',
		'de': 'Sie haben alle Voraussetzungen, um dies zu kaufen.',
		'it': 'Hai tutti i requisiti per acquistarlo.',
		'ko': '이 제품을 구매하기 위한 모든 요구 사항을 갖추고 있습니다.',
		'ja': 'これを購入するための要件が​​すべて揃っています。',
		'pt': 'Você tem todos os requisitos para comprar isso.',
		'pt-br': 'Você tem todos os requisitos para comprar isso.',
		'es': 'Tienes todos los requisitos para adquirirlo.',
		'ru': 'У вас есть все условия для покупки.',
		'tr': 'Bunu satın almak için tüm gereksinimlere sahipsiniz.',
	},
	'PURCHASE_DESC_2': {
		'en': 'Click the icon to purchase this.',
		'zh-CN': '单击该图标即可购买。',
		'zh-TW': '點擊該圖示即可購買。',
		'fr': 'Cliquez sur l\'icône pour l\'acheter.',
		'de': 'Klicken Sie auf das Symbol, um es zu kaufen.',
		'it': 'Fare clic sull\'icona per acquistarlo.',
		'ko': '아이콘을 클릭하시면 구매하실 수 있습니다.',
		'ja': 'アイコンをクリックしてご購入ください。',
		'pt': 'Clique no ícone para comprar isto.',
		'pt-br': 'Clique no ícone para comprar isto.',
		'es': 'Haga clic en el icono para comprarlo.',
		'ru': 'Нажмите на значок, чтобы купить это.',
		'tr': 'Bunu satın almak için simgeye tıklayın.',
	},
	'FILTER_DESC_1': {
		'en': '1. Click on the icons you wish to filter',
		'zh-CN': '1. 点击您想要过滤的图标',
		'zh-TW': '1. 點擊您想要過濾的圖標',
		'fr': '1. Cliquez sur les icônes que vous souhaitez filtrer',
		'de': '1. Klicken Sie auf die Symbole, die Sie filtern möchten',
		'it': '1. Fare clic sulle icone che si desidera filtrare',
		'ko': '1. 필터링하려는 아이콘을 클릭하세요.',
		'ja': '1. フィルタリングしたいアイコンをクリックします',
		'pt': '1. Clique nos ícones que deseja filtrar',
		'pt-br': '1. Clique nos ícones que deseja filtrar',
		'es': '1. Haga clic en los iconos que desea filtrar.',
		'ru': '1. Нажмите на значки, которые вы хотите отфильтровать.',
		'tr': '1. Filtrelemek istediğiniz simgelere tıklayın',
	},
	'FILTER_DESC_2': {
		'en': '2. Click "Filter Icon" to hide all filtered icons.',
		'zh-CN': '2. 点击“过滤图标”可隐藏所有已过滤的图标。',
		'zh-TW': '2. 點選「過濾圖示」可隱藏所有已過濾的圖示。',
		'fr': '2. Cliquez sur « Icône de filtre » pour masquer toutes les icônes filtrées.',
		'de': '2. Klicken Sie auf „Symbol filtern“, um alle gefilterten Symbole auszublenden.',
		'it': '2. Fare clic su "Icona filtro" per nascondere tutte le icone filtrate.',
		'ko': '2. "필터 아이콘"을 클릭하면 필터링된 모든 아이콘이 숨겨집니다.',
		'ja': '2. 「フィルターアイコン」をクリックすると、フィルターされたアイコンがすべて非表示になります。',
		'pt': '2. Clique em "Ícone de filtro" para ocultar todos os ícones filtrados.',
		'pt-br': '2. Clique em "Ícone de filtro" para ocultar todos os ícones filtrados.',
		'es': '2. Haga clic en "Icono de filtro" para ocultar todos los iconos filtrados.',
		'ru': '2. Нажмите «Значок фильтра», чтобы скрыть все отфильтрованные значки.',
		'tr': '2. Tüm filtrelenmiş simgeleri gizlemek için "Filtre Simgesi"ne tıklayın.',
	},
	'FILTER_DESC_3': {
		'en': 'Mass Filtering will filter that icon in all skills.',
		'zh-CN': '质量过滤将过滤所有技能中的该图标。',
		'zh-TW': '品質過濾將過濾所有技能中的該圖示。',
		'fr': 'Le filtrage de masse filtrera cette icône dans toutes les compétences.',
		'de': 'Durch die Massenfilterung wird dieses Symbol in allen Fertigkeiten gefiltert.',
		'it': 'Il Filtraggio di massa filtrerà quell\'icona in tutte le abilità.',
		'ko': '대량 필터링은 모든 스킬에서 해당 아이콘을 필터링합니다.',
		'ja': '大量フィルタリングにより、すべてのスキルでそのアイコンがフィルタリングされます。',
		'pt': 'A Filtragem em Massa filtrará esse ícone em todas as habilidades.',
		'pt-br': 'A Filtragem em Massa filtrará esse ícone em todas as habilidades.',
		'es': 'El filtrado masivo filtrará ese ícono en todas las habilidades.',
		'ru': 'Массовая фильтрация отфильтрует этот значок во всех навыках.',
		'tr': 'Toplu Filtreleme bu simgeyi tüm becerilerde filtreleyecektir.',
	},
	'FILTER_DESC_4': {
		'en': 'When Mass Filtering is enabled, the filter state of all icons will be synced with the clicked icon.',
		'zh-CN': '当启用批量过滤时，所有图标的过滤状态将与点击的图标同步。',
		'zh-TW': '啟用品質過濾時，所有圖示的過濾狀態將與點擊的圖示同步。',
		'fr': 'Lorsque le filtrage de masse est activé, l\'état du filtre de toutes les icônes sera synchronisé avec l\'icône cliquée.',
		'de': 'Wenn die Massenfilterung aktiviert ist, wird der Filterstatus aller Symbole mit dem angeklickten Symbol synchronisiert.',
		'it': 'Quando il filtro di massa è abilitato, lo stato del filtro di tutte le icone verrà sincronizzato con l\'icona su cui si è fatto clic.',
		'ko': '대량 필터링이 활성화되면 모든 아이콘의 필터 상태가 클릭한 아이콘과 동기화됩니다.',
		'ja': '一括フィルタリングが有効な場合、すべてのアイコンのフィルタ状態は、クリックされたアイコンと同期されます。',
		'pt': 'Quando a Filtragem em Massa estiver ativada, o estado do filtro de todos os ícones será sincronizado com o ícone clicado.',
		'pt-br': 'Quando a Filtragem em Massa estiver ativada, o estado do filtro de todos os ícones será sincronizado com o ícone clicado.',
		'es': 'Cuando el filtrado masivo está habilitado, el estado del filtro de todos los íconos se sincronizará con el ícono en el que se hizo clic.',
		'ru': 'Если массовая фильтрация включена, состояние фильтра всех значков будет синхронизировано с выбранным значком.',
		'tr': 'Toplu Filtreleme etkinleştirildiğinde, tüm simgelerin filtre durumu tıklanan simgeyle senkronize edilecektir.',
	},
	'DELETE_DATA_2': {
		'en': 'This cannot be undone!',
		'zh-CN': '这不能被撤消！',
		'zh-TW': '這不能被撤銷！',
		'fr': 'Ça ne peut pas être annulé!',
		'de': 'Das kann nicht rückgängig gemacht werden!',
		'it': 'Questa operazione non può essere annullata!',
		'ko': '이 취소 할 수 없습니다!',
		'ja': 'これは、元に戻すことはできません！',
		'pt': 'Isto não pode ser desfeito!',
		'pt-br': 'Isto não pode ser desfeito!',
		'es': '¡Esto no se puede deshacer!',
		'ru': 'Это не может быть отменено!',
		'tr': 'Bu geri alınamaz!',
	},
	'AUTOMATICALLY_HIDE': {
		'en': 'This category will be hidden if you own everything.',
		'zh-CN': '如果您拥有一切，此类别将被隐藏。',
		'zh-TW': '如果您擁有一切，此類別將被隱藏。',
		'fr': 'Cette catégorie sera masquée si vous possédez tout.',
		'de': 'Diese Kategorie wird ausgeblendet, wenn Sie alles besitzen.',
		'it': 'Questa categoria verrà nascosta se possiedi tutto.',
		'ko': '모든 항목을 소유한 경우 이 카테고리는 숨겨집니다.',
		'ja': 'すべてを所有している場合、このカテゴリは非表示になります。',
		'pt': 'Esta categoria ficará oculta se você possuir tudo.',
		'pt-br': 'Esta categoria ficará oculta se você possuir tudo.',
		'es': 'Esta categoría estará oculta si eres dueño de todo.',
		'ru': 'Эта категория будет скрыта, если у вас есть все.',
		'tr': 'Her şeyin sahibiyseniz bu kategori gizlenecektir.',
	},
	'SETTING_MERGE': {
		'en': 'Merge Global and Skill categories?',
		'zh-CN': '合并全局和技能类别？',
		'zh-TW': '合併全域和技能類別？',
		'fr': 'Fusionner les catégories Global et Compétence ?',
		'de': 'Globale und Kompetenzkategorien zusammenführen?',
		'it': 'Unire le categorie globali e di competenza?',
		'ko': '글로벌 및 스킬 카테고리를 병합하시겠습니까?',
		'ja': 'グローバル カテゴリとスキル カテゴリを統合しますか?',
		'pt': 'Mesclar categorias globais e de habilidades?',
		'pt-br': 'Mesclar categorias globais e de habilidades?',
		'es': '¿Fusionar las categorías Global y Skill?',
		'ru': 'Объединить глобальные категории и категории навыков?',
		'tr': 'Global ve Beceri kategorileri birleştirilsin mi?',
	},
	'SETTING_MERGE_DESC': {
		'en': 'This setting may be removed in the next big update.',
		'zh-CN': '此设置可能会在下一次大更新中删除。',
		'zh-TW': '此設定可能會在下次大更新中刪除。',
		'fr': 'Ce paramètre pourrait être supprimé lors de la prochaine grande mise à jour.',
		'de': 'Diese Einstellung wird möglicherweise im nächsten großen Update entfernt.',
		'it': 'Questa impostazione potrebbe essere rimossa nel prossimo grande aggiornamento.',
		'ko': '이 설정은 다음 대규모 업데이트에서 제거될 수 있습니다.',
		'ja': 'この設定は次の大きなアップデートで削除される可能性があります。',
		'pt': 'Esta configuração pode ser removida na próxima grande atualização.',
		'pt-br': 'Esta configuração pode ser removida na próxima grande atualização.',
		'es': 'Es posible que esta configuración se elimine en la próxima gran actualización.',
		'ru': 'Этот параметр может быть удален в следующем большом обновлении.',
		'tr': 'Bu ayar bir sonraki büyük güncellemede kaldırılabilir.',
	},
	'SETTING_ASTRO_SPOILERS': {
		'en': 'Show locked Astrology modifiers?',
		'zh-CN': '显示锁定的占星术修改器？',
		'zh-TW': '顯示鎖定的占星術修改器？',
		'fr': 'Afficher les modificateurs d\'astrologie verrouillés ?',
		'de': 'Gesperrte Astrologie-Modifikatoren anzeigen?',
		'it': 'Mostrare i modificatori di astrologia bloccati?',
		'ko': '잠긴 점성술 수정자를 표시하시겠습니까?',
		'ja': 'ロックされた占星術修飾子を表示しますか?',
		'pt': 'Mostrar modificadores astrológicos bloqueados?',
		'pt-br': 'Mostrar modificadores astrológicos bloqueados?',
		'es': '¿Mostrar modificadores de astrología bloqueados?',
		'ru': 'Показать заблокированные модификаторы астрологии?',
		'tr': 'Kilitli Astroloji değiştiricileri gösterilsin mi?',
	},
	'SETTING_ASTRO_SPOILERS_HINT': {
		'en': 'When enabled, the spend stardust menu when clicking on a Constellation and the Constellation tooltips will show modifiers that are not unlocked.',
		'zh-CN': '启用后，单击星座时的花费星尘菜单和星座工具提示将显示未解锁的修改器。',
		'zh-TW': '啟用後，點擊星座時的花費星塵選單和星座工具提示將顯示未解鎖的修改器。',
		'fr': 'Lorsqu\'il est activé, le menu Dépenser de la poussière d\'étoile lorsque vous cliquez sur une constellation et les info-bulles de la constellation afficheront les modificateurs qui ne sont pas déverrouillés.',
		'de': 'Wenn diese Option aktiviert ist, werden beim Klicken auf eine Konstellation im Menü „Sternenstaub ausgeben“ und in den Tooltips der Konstellation Modifikatoren angezeigt, die nicht freigeschaltet sind.',
		'it': 'Se abilitato, il menu di spesa della polvere di stelle quando si fa clic su una costellazione e i suggerimenti della costellazione mostreranno i modificatori che non sono sbloccati.',
		'ko': '활성화하면 별자리를 클릭할 때 별가루 소비 메뉴와 별자리 툴팁에 잠금 해제되지 않은 수정자가 표시됩니다.',
		'ja': '有効にすると、星座をクリックしたときのスターダストの消費メニューと星座ツールチップに、ロックが解除されていないモディファイアが表示されます。',
		'pt': 'Quando ativado, o menu de gasto de poeira estelar ao clicar em uma Constelação e as dicas de ferramentas da Constelação mostrarão modificadores que não estão desbloqueados.',
		'pt-br': 'Quando ativado, o menu de gasto de poeira estelar ao clicar em uma Constelação e as dicas de ferramentas da Constelação mostrarão modificadores que não estão desbloqueados.',
		'es': 'Cuando está habilitado, el menú de gastar polvo de estrellas al hacer clic en una constelación y la información sobre herramientas de la constelación mostrarán modificadores que no están desbloqueados.',
		'ru': 'Если этот параметр включен, в меню траты звездной пыли при нажатии на Созвездие и во всплывающих подсказках Созвездия будут отображаться модификаторы, которые не разблокированы.',
		'tr': 'Etkinleştirildiğinde, bir Constellation ve Constellation araç ipuçlarına tıklandığında yıldız tozu harcama menüsü, kilidi açık olmayan değiştiricileri gösterecektir.',
	},
	'SETTING_HIDE_REDBGS': {
		'en': 'Hide icons with a "red" background?',
		'zh-CN': '隐藏带有“红色”背景的图标？',
		'zh-TW': '隱藏帶有“紅色”背景的圖示？',
		'fr': 'Masquer les icônes avec un fond « rouge » ?',
		'de': 'Icons mit „rotem“ Hintergrund ausblenden?',
		'it': 'Nascondere le icone con uno sfondo "rosso"?',
		'ko': '"빨간색" 배경의 아이콘을 숨기시겠습니까?',
		'ja': '背景が「赤」のアイコンを非表示にしますか?',
		'pt': 'Ocultar ícones com fundo "vermelho"?',
		'pt-br': 'Ocultar ícones com fundo "vermelho"?',
		'es': '¿Ocultar iconos con fondo "rojo"?',
		'ru': 'Скрыть иконки с «красным» фоном?',
		'tr': '"Kırmızı" arka plana sahip simgeler gizlensin mi?',
	},
	'SETTING_HIDE_REDBGS_HINT': {
		'en': 'Hides any icon with a "red" background in the respective category.',
		'zh-CN': '隐藏相应类别中具有“红色”背景的任何图标。',
		'zh-TW': '隱藏相應類別中具有“紅色”背景的任何圖示。',
		'fr': 'Masque toute icône avec un fond « rouge » dans la catégorie respective.',
		'de': 'Blendet alle Icons mit „rotem“ Hintergrund in der jeweiligen Kategorie aus.',
		'it': 'Nasconde qualsiasi icona con sfondo "rosso" nella rispettiva categoria.',
		'ko': '해당 카테고리에서 배경이 "빨간색"인 아이콘을 숨깁니다.',
		'ja': 'それぞれのカテゴリ内の背景が「赤」のアイコンを非表示にします。',
		'pt': 'Oculta qualquer ícone com fundo "vermelho" na respectiva categoria.',
		'pt-br': 'Oculta qualquer ícone com fundo "vermelho" na respectiva categoria.',
		'es': 'Oculta cualquier icono con fondo "rojo" en la categoría respectiva.',
		'ru': 'Скрывает любой значок с «красным» фоном в соответствующей категории.',
		'tr': 'İlgili kategorideki "kırmızı" arka plana sahip herhangi bir simgeyi gizler.',
	},
	'INCLUDE_FILTERED': {
		'en': 'Include Filtered',
		'zh-CN': '包括过滤的',
		'zh-TW': '包括過濾的',
		'fr': 'Inclure filtré',
		'de': 'Gefiltert einschließen',
		'it': 'Includi filtrato',
		'ko': '필터링된 항목 포함',
		'ja': 'フィルタリングされたものを含む',
		'pt': 'Incluir Filtrado',
		'pt-br': 'Incluir Filtrado',
		'es': 'Incluir filtrado',
		'ru': 'Включить отфильтрованное',
		'tr': 'Filtrelenmişleri Dahil Et',
	},
	'INCLUDE_HIDDEN': {
		'en': 'Include Hidden',
		'zh-CN': '包括隐藏',
		'zh-TW': '包括隱藏',
		'fr': 'Inclure masqué',
		'de': 'Versteckt einbeziehen',
		'it': 'Includi nascosti',
		'ko': '숨겨진 항목 포함',
		'ja': '非表示を含む',
		'pt': 'Incluir oculto',
		'pt-br': 'Incluir oculto',
		'es': 'Incluir oculto',
		'ru': 'Включить скрытое',
		'tr': 'Gizliyi Ekle',
	},
	'INCLUDE_REDBG': {
		'en': 'Include "Red" Backgrounds',
		'zh-CN': '包括“红色”背景',
		'zh-TW': '包括“紅色”背景',
		'fr': 'Inclure les arrière-plans « rouges »',
		'de': 'Fügen Sie „rote“ Hintergründe hinzu',
		'it': 'Includi sfondi "rossi".',
		'ko': '"빨간색" 배경 포함',
		'ja': '「赤」の背景を含める',
		'pt': 'Incluir fundos "vermelhos"',
		'pt-br': 'Incluir fundos "vermelhos"',
		'es': 'Incluir fondos "rojos"',
		'ru': 'Включить «красный» фон',
		'tr': '"Kırmızı" Arka Planları Ekle',
	},
	'INCLUDE_REALMS': {
		'en': 'Include All Realms',
		'zh-CN': '包括所有领域',
		'zh-TW': '包括所有領域',
		'fr': 'Inclure tous les domaines',
		'de': 'Alle Bereiche einbeziehen',
		'it': 'Includi tutti i regni',
		'ko': '모든 영역 포함',
		'ja': 'すべてのレルムを含める',
		'pt': 'Incluir todos os reinos',
		'pt-br': 'Incluir todos os reinos',
		'es': 'Incluir todos los reinos',
		'ru': 'Включить все области',
		'tr': 'Tüm Bölgeleri Dahil Et',
	},
	'SETTINGS_MODIFIER_TEXT': {
		'en': 'Which should be included when searching modifier text?',
		'zh-CN': '搜索修饰符文本时应包含哪些内容？',
		'zh-TW': '搜尋修飾符文字時應包含哪些內容？',
		'fr': 'Lequel doit être inclus lors de la recherche de texte de modificateur ?',
		'de': 'Was sollte bei der Suche nach Modifikatortext berücksichtigt werden?',
		'it': 'Quale dovrebbe essere incluso durante la ricerca del testo modificatore?',
		'ko': '수정자 텍스트를 검색할 때 어떤 항목을 포함해야 합니까?',
		'ja': '修飾子テキストを検索する場合はどれを含める必要がありますか?',
		'pt': 'O que deve ser incluído ao pesquisar texto modificador?',
		'pt-br': 'O que deve ser incluído ao pesquisar texto modificador?',
		'es': '¿Qué debería incluirse al buscar texto modificador?',
		'ru': 'Что следует включать при поиске текста модификатора?',
		'tr': 'Değiştirici metin aranırken hangisi dahil edilmelidir?',
	},
	'SETTING_ONLY_USEFUL_MODS': {
		'en': 'Only show useful modifiers in tooltips?',
		'zh-CN': '只在工具提示中显示有用的修饰符？',
		'zh-TW': '只在工具提示中顯示有用的修飾符？',
		'fr': 'Afficher uniquement les modificateurs utiles dans les info-bulles ?',
		'de': 'Nur nützliche Modifikatoren in Tooltips anzeigen?',
		'it': 'Mostrare solo i modificatori utili nei tooltip?',
		'ko': '툴팁에 유용한 수정자만 표시하시겠습니까?',
		'ja': '有用な修飾子のみをツールチップに表示しますか?',
		'pt': 'Mostrar apenas modificadores úteis nas dicas de ferramentas?',
		'pt-br': 'Mostrar apenas modificadores úteis nas dicas de ferramentas?',
		'es': '¿Mostrar sólo modificadores útiles en la información sobre herramientas?',
		'ru': 'Показывать во всплывающих подсказках только полезные модификаторы?',
		'tr': 'Araç ipuçlarında yalnızca yararlı değiştiriciler gösterilsin mi?',
	},
	'SETTING_PRESET_BUTTON': {
		'en': 'Show Presets Button?',
		'zh-CN': '显示预置按钮？',
		'zh-TW': '顯示预置按鈕？',
		'fr': 'Afficher le bouton Préréglages ?',
		'de': 'Schaltfläche „Voreinstellungen anzeigen“?',
		'it': 'Mostra pulsante Preimpostazioni?',
		'ko': '사전 설정 버튼을 표시하시겠습니까?',
		'ja': 'プリセットボタンを表示しますか?',
		'pt': 'Mostrar botão de predefinições?',
		'pt-br': 'Mostrar botão de predefinições?',
		'es': '¿Mostrar botón de ajustes preestablecidos?',
		'ru': 'Показать кнопку предустановок?',
		'tr': 'Ön Ayarlar Düğmesi Gösterilsin mi?',
	},
	'SETTING_PRESET_FILTER': {
		'en': 'Filter by Preset Type',
		'zh-CN': '按预设类型过滤',
		'zh-TW': '按預設類型過濾',
		'fr': 'Filtrer par type de préréglage',
		'de': 'Nach Voreinstellungstyp filtern',
		'it': 'Filtra per tipo di preimpostazione',
		'ko': '사전 설정 유형으로 필터링',
		'ja': 'プリセットタイプによるフィルター',
		'pt': 'Filtrar por tipo predefinido',
		'pt-br': 'Filtrar por tipo predefinido',
		'es': 'Filtrar por tipo preestablecido',
		'ru': 'Фильтровать по типу предустановки',
		'tr': 'Ön Ayar Türüne Göre Filtrele',
	},
	'SETTING_PRESET_FILTER_ALL_SKILL': {
		'en': 'All + Skill or Combat',
		'zh-CN': '全部+技能或战斗',
		'zh-TW': '全部+技能或戰鬥',
		'fr': 'Tout + Compétence ou Combat',
		'de': 'Alle + Geschicklichkeit oder Kampf',
		'it': 'Tutto + Abilità o Combattimento',
		'ko': '모두 + 스킬 또는 전투',
		'ja': 'すべて + スキルまたは戦闘',
		'pt': 'Tudo + Habilidade ou Combate',
		'pt-br': 'Tudo + Habilidade ou Combate',
		'es': 'Todo + Habilidad o Combate',
		'ru': 'Все + Навык или Бой',
		'tr': 'Hepsi + Beceri veya Savaş',
	},
	'SETTING_PRESET_FILTER_ALL_SKILL_HINT': {
		'en': 'Shows Preset Types "All" and "Combat" (while on the Combat page) or "Skill" (while on a skill page).',
		'zh-CN': '显示预设类型“全部”和“战斗”（在战斗页面上）或“技能”（在技能页面上）。',
		'zh-TW': '顯示預設類型「全部」和「戰鬥」（在戰鬥頁面上）或「技能」（在技能頁面上）。',
		'fr': 'Affiche les types prédéfinis « Tous » et « Combat » (sur la page Combat) ou « Compétence » (sur une page de compétences).',
		'de': 'Zeigt die voreingestellten Typen „Alle“ und „Kampf“ (auf der Kampfseite) oder „Fertigkeit“ (auf einer Fertigkeitsseite) an.',
		'it': 'Mostra i tipi di preimpostazione "Tutti" e "Combattimento" (nella pagina Combattimento) o "Abilità" (nella pagina delle abilità).',
		'ko': '사전 설정 유형 "All" 및 "Combat"(전투 페이지에 있는 동안) 또는 "Skill"(스킬 페이지에 있는 동안)을 표시합니다.',
		'ja': 'プリセット タイプ「すべて」と「戦闘」(戦闘ページにいるとき)、または「スキル」(スキル ページにいるとき)を表示します。',
		'pt': 'Mostra os tipos predefinidos "Todos" e "Combate" (na página Combate) ou "Habilidade" (na página de habilidade).',
		'pt-br': 'Mostra os tipos predefinidos "Todos" e "Combate" (na página Combate) ou "Habilidade" (na página de habilidade).',
		'es': 'Muestra los tipos preestablecidos "Todos" y "Combate" (mientras estás en la página de Combate) o "Habilidad" (mientras estás en una página de habilidades).',
		'ru': 'Показывает предустановленные типы «Все» и «Бой» (на странице «Бой») или «Навык» (на странице навыков).',
		'tr': 'Ön Ayar Türlerini "Tümü" ve "Savaş" (Savaş sayfasındayken) veya "Beceri" (beceri sayfasındayken) gösterir.',
	},
	'SETTING_PRESET_FILTER_ONLY_SKILLS': {
		'en': 'Only Skill or Combat',
		'zh-CN': '仅限技能或战斗',
		'zh-TW': '僅限技能或戰鬥',
		'fr': 'Seulement compétence ou combat',
		'de': 'Nur Geschicklichkeit oder Kampf',
		'it': 'Solo Abilità o Combattimento',
		'ko': '스킬이나 전투만 가능',
		'ja': 'スキルまたは戦闘のみ',
		'pt': 'Apenas Habilidade ou Combate',
		'pt-br': 'Apenas Habilidade ou Combate',
		'es': 'Sólo Habilidad o Combate',
		'ru': 'Только навык или бой',
		'tr': 'Yalnızca Beceri veya Savaş',
	},
	'SETTING_PRESET_FILTER_ONLY_SKILLS_HINT': {
		'en': 'Only shows Preset Type "Combat" or "Skill"',
		'zh-CN': '仅显示预设类型“战斗”或“技能”',
		'zh-TW': '僅顯示預設類型“戰鬥”或“技能”',
		'fr': 'Affiche uniquement le type prédéfini « Combat » ou « Compétence »',
		'de': 'Zeigt nur den voreingestellten Typ „Kampf“ oder „Fähigkeit“ an.',
		'it': 'Mostra solo il tipo di preimpostazione "Combattimento" o "Abilità"',
		'ko': '사전 설정 유형 "전투" 또는 "스킬"만 표시됩니다.',
		'ja': 'プリセットタイプ「戦闘」または「スキル」のみを表示',
		'pt': 'Mostra apenas o tipo predefinido "Combate" ou "Habilidade"',
		'pt-br': 'Mostra apenas o tipo predefinido "Combate" ou "Habilidade"',
		'es': 'Solo muestra el tipo de preajuste "Combate" o "Habilidad"',
		'ru': 'Показывает только тип предустановки «Бой» или «Навык».',
		'tr': 'Yalnızca Ön Ayar Türü "Savaş" veya "Beceri"yi gösterir',
	},
	'SETTING_PRESET_FILTER_CURRENT_SKILL': {
		'en': 'Only Current Skill',
		'zh-CN': '仅当前技能',
		'zh-TW': '僅當前技能',
		'fr': 'Seule la compétence actuelle',
		'de': 'Nur aktuelle Fähigkeit',
		'it': 'Solo abilità attuale',
		'ko': '현재 스킬만',
		'ja': '現在のスキルのみ',
		'pt': 'Apenas habilidade atual',
		'pt-br': 'Apenas habilidade atual',
		'es': 'Sólo habilidad actual',
		'ru': 'Только текущий навык',
		'tr': 'Yalnızca Mevcut Beceri',
	},
	'SETTING_PRESET_FILTER_CURRENT_SKILL_HINT': {
		'en': 'Only shows Presets for the current skill page. The Preset must have the skill enabled in the Minibar settings. Combat page will default to "Combat" presets.',
		'zh-CN': '仅显示当前技能页面的预设。预设必须在迷你栏设置中启用该技能。战斗页面将默认为“战斗”预设。',
		'zh-TW': '僅顯示目前技能頁面的預設。預設必須在迷你欄設定中啟用此技能。戰鬥頁面將預設為「戰鬥」預設。',
		'fr': 'Affiche uniquement les préréglages pour la page de compétence actuelle. Le préréglage doit avoir la compétence activée dans les paramètres du minibar. La page de combat sera par défaut sur les préréglages "Combat".',
		'de': 'Zeigt nur Voreinstellungen für die aktuelle Skill-Seite an. Für die Voreinstellung muss der Skill in den Minibar-Einstellungen aktiviert sein. Die Kampfseite verwendet standardmäßig die Voreinstellungen „Kampf“.',
		'it': 'Mostra solo le preimpostazioni per la pagina dell\'abilità corrente. La preimpostazione deve avere l\'abilità abilitata nelle impostazioni della Minibar. La pagina di combattimento utilizzerà per impostazione predefinita le preimpostazioni "Combattimento".".',
		'ko': '현재 스킬 페이지에 대한 프리셋만 표시됩니다. 프리셋에는 미니바 설정에서 스킬이 활성화되어 있어야 합니다. 전투 페이지는 기본적으로 "전투" 사전 설정으로 설정됩니다.',
		'ja': '現在のスキルページのプリセットのみを表示します。プリセットのミニバー設定でスキルが有効になっている必要があります。戦闘ページはデフォルトで「戦闘」プリセットになります。',
		'pt': 'Mostra apenas predefinições para a página de habilidade atual. O Preset deve ter a habilidade habilitada nas configurações do Minibar. A página de combate terá como padrão as predefinições de "Combate".',
		'pt-br': 'Mostra apenas predefinições para a página de habilidade atual. O Preset deve ter a habilidade habilitada nas configurações do Minibar. A página de combate terá como padrão as predefinições de "Combate".',
		'es': 'Solo muestra ajustes preestablecidos para la página de habilidades actual. El Preset debe tener la habilidad habilitada en la configuración del Minibar. La página de combate tendrá de forma predeterminada los ajustes preestablecidos de "Combate".',
		'ru': 'Показывает только пресеты для текущей страницы навыков. Для предустановки этот навык должен быть включен в настройках мини-бара. На странице боя по умолчанию используются пресеты «Боевые».',
		'tr': 'Yalnızca geçerli beceri sayfasının Ön Ayarlarını gösterir. Ön Ayarın Minibar ayarlarında etkinleştirilmiş olması gerekir. Savaş sayfasında varsayılan olarak "Savaş" ön ayarları kullanılacaktır.',
	},
	'SETTING_PRESET_FILTER_ALL': {
		'en': 'All Presets',
		'zh-CN': '所有预设',
		'zh-TW': '所有預設',
		'fr': 'Tous les préréglages',
		'de': 'Alle Voreinstellungen',
		'it': 'Tutti i preset',
		'ko': '모든 사전 설정',
		'ja': 'すべてのプリセット',
		'pt': 'Todas as predefinições',
		'pt-br': 'Todas as predefinições',
		'es': 'Todos los ajustes preestablecidos',
		'ru': 'Все пресеты',
		'tr': 'Tüm Ön Ayarlar',
	},
	'SETTING_PRESET_FILTER_ALL_HINT': {
		'en': 'Shows all Presets regardless of type',
		'zh-CN': '显示所有预设，无论类型如何',
		'zh-TW': '顯示所有預設，無論類型為何',
		'fr': 'Affiche tous les préréglages quel que soit leur type',
		'de': 'Zeigt alle Voreinstellungen unabhängig vom Typ an',
		'it': 'Mostra tutti i preset indipendentemente dal tipo',
		'ko': '유형에 관계없이 모든 사전 설정을 표시합니다.',
		'ja': 'タイプに関係なくすべてのプリセットを表示します',
		'pt': 'Mostra todas as predefinições, independentemente do tipo',
		'pt-br': 'Mostra todas as predefinições, independentemente do tipo',
		'es': 'Muestra todos los presets independientemente del tipo',
		'ru': 'Показывает все пресеты независимо от типа.',
		'tr': 'Türüne bakılmaksızın tüm Ön Ayarları gösterir',
	},
	'SETTING_PRESET_NO_PRESET': {
		'en': 'Create a Preset if you have no Presets?',
		'zh-CN': '如果没有预设，是否创建预设？',
		'zh-TW': '如果沒有預設，是否建立預設？',
		'fr': 'Créer un préréglage si vous n\'avez pas de préréglages ?',
		'de': 'Eine Voreinstellung erstellen, wenn Sie keine Voreinstellungen haben?',
		'it': 'Creare un preset se non hai preset?',
		'ko': '사전 설정이 없는 경우 사전 설정을 만드시겠습니까?',
		'ja': 'プリセットがない場合はプリセットを作成しますか?',
		'pt': 'Criar uma predefinição se você não tiver predefinições?',
		'pt-br': 'Criar uma predefinição se você não tiver predefinições?',
		'es': '¿Crear un preset si no tienes presets?',
		'ru': 'Создать пресет, если у вас нет пресетов?',
		'tr': 'Ön Ayarınız yoksa bir Ön Ayar oluşturulsun mu?',
	},
	'SETTING_PRESET_NO_PRESET_HINT': {
		'en': 'When the Presets button is clicked, should it automatically start creating a Preset if none are created?',
		'zh-CN': '单击“预设”按钮时，如果没有创建预设，是否应该自动开始创建预设？',
		'zh-TW': '當您按一下「預設」按鈕時，如果沒有建立預設，是否應該自動開始建立預設？',
		'fr': 'Lorsque vous cliquez sur le bouton Préréglages, doit-il automatiquement commencer à créer un préréglage si aucun n\'est créé ?',
		'de': 'Soll beim Klicken auf die Schaltfläche „Voreinstellungen“ automatisch mit der Erstellung einer Voreinstellung begonnen werden, wenn keine erstellt wurde?',
		'it': 'Quando si fa clic sul pulsante Preset, dovrebbe iniziare automaticamente a creare un Preset se non ne viene creato nessuno?',
		'ko': '사전 설정 버튼을 클릭하면 사전 설정이 생성되지 않은 경우 자동으로 사전 설정 생성이 시작되어야 합니까?',
		'ja': '[プリセット] ボタンをクリックすると、何も作成されていない場合は自動的にプリセットの作成が開始されますか?',
		'pt': 'Quando o botão Presets é clicado, ele deve começar a criar automaticamente um Preset se nenhum for criado?',
		'pt-br': 'Quando o botão Presets é clicado, ele deve começar a criar automaticamente um Preset se nenhum for criado?',
		'es': 'Cuando se hace clic en el botón Presets, ¿debería comenzar a crear automáticamente un preset si no se crea ninguno?',
		'ru': 'Должен ли при нажатии кнопки «Пресеты» автоматически начаться создание пресета, если ни один не создан?',
		'tr': 'Ön Ayarlar düğmesi tıklatıldığında, herhangi bir Ön Ayar oluşturulmamışsa otomatik olarak bir Ön Ayar oluşturmaya başlamalı mı?',
	},
	'SETTING_PRESET_ONE_PRESET': {
		'en': 'Edit Preset if there\'s only one Preset?',
		'zh-CN': '如果只有一个预设，是否要编辑预设？',
		'zh-TW': '如果只有一個預設，是否要編輯預設？',
		'fr': 'Modifier le préréglage s\'il n\'y a qu\'un seul préréglage ?',
		'de': 'Voreinstellung bearbeiten, wenn es nur eine Voreinstellung gibt?',
		'it': 'Modifica la preimpostazione se c\'è una sola preimpostazione?',
		'ko': '프리셋이 하나만 있는 경우 프리셋을 편집하시겠습니까?',
		'ja': 'プリセットが 1 つしかない場合、プリセットを編集しますか?',
		'pt': 'Editar Preset se houver apenas um Preset?',
		'pt-br': 'Editar Preset se houver apenas um Preset?',
		'es': '¿Editar preestablecido si solo hay un preestablecido?',
		'ru': 'Изменить пресет, если есть только один пресет?',
		'tr': 'Yalnızca bir Ön Ayar varsa Ön Ayar düzenlensin mi?',
	},
	'SETTING_PRESET_ONE_PRESET_HINT': {
		'en': 'When enabled, this will edit the existing preset if only one preset was found for the current skill.',
		'zh-CN': '启用后，如果当前技能仅找到一个预设，则会编辑现有预设。',
		'zh-TW': '啟用後，如果目前技能僅找到一個預設，則會編輯現有預設。',
		'fr': 'Lorsqu\'il est activé, cela modifiera le préréglage existant si un seul préréglage a été trouvé pour la compétence actuelle.',
		'de': 'Wenn diese Option aktiviert ist, wird die vorhandene Voreinstellung bearbeitet, wenn für die aktuelle Fertigkeit nur eine Voreinstellung gefunden wurde.',
		'it': 'Se abilitato, modificherà la preimpostazione esistente se è stata trovata una sola preimpostazione per l\'abilità corrente.',
		'ko': '활성화되면 현재 스킬에 대해 하나의 사전 설정만 발견된 경우 기존 사전 설정을 편집합니다.',
		'ja': '有効にすると、現在のスキルでプリセットが 1 つだけ見つかった場合、既存のプリセットが編集されます。',
		'pt': 'Quando ativado, isso editará a predefinição existente se apenas uma predefinição for encontrada para a habilidade atual.',
		'pt-br': 'Quando ativado, isso editará a predefinição existente se apenas uma predefinição for encontrada para a habilidade atual.',
		'es': 'Cuando está habilitado, esto editará el ajuste preestablecido existente si solo se encontró un ajuste preestablecido para la habilidad actual.',
		'ru': 'Если эта опция включена, существующая предустановка будет отредактирована, если для текущего навыка была найдена только одна предустановка.',
		'tr': 'Etkinleştirildiğinde, mevcut beceri için yalnızca bir ön ayar bulunmuşsa bu, mevcut ön ayarı düzenler.',
	},
	'SETTING_BUILD_MENU': {
		'en': 'When should the Obstacle build menu be shown?',
		'zh-CN': '何时应显示障碍物构建菜单？',
		'zh-TW': '何時應顯示障礙物建構選單？',
		'fr': 'Quand le menu de construction d’obstacles doit-il être affiché ?',
		'de': 'Wann sollte das Hindernisbau-Menü angezeigt werden?',
		'it': 'Quando dovrebbe essere mostrato il menu di creazione degli ostacoli?',
		'ko': '장애물 제작 메뉴는 언제 표시되어야 합니까?',
		'ja': 'Obstacle build メニューはいつ表示されるべきですか?',
		'pt': 'Quando o menu de construção de Obstáculos deve ser mostrado?',
		'pt-br': 'Quando o menu de construção de Obstáculos deve ser mostrado?',
		'es': '¿Cuándo debería mostrarse el menú de construcción de obstáculos?',
		'ru': 'Когда должно отображаться меню построения препятствий?',
		'tr': 'Engel oluşturma menüsü ne zaman gösterilmelidir?',
	},
	'SETTING_COMBAT_SYNERGIES': {
		'en': 'Include Synergies on the Combat Menu?',
		'zh-CN': '在战斗菜单中加入协同作用？',
		'zh-TW': '在戰鬥選單中加入協同作用？',
		'fr': 'Inclure des synergies dans le menu de combat ?',
		'de': 'Synergien in das Kampfmenü aufnehmen?',
		'it': 'Includere sinergie nel menu di combattimento?',
		'ko': '전투 메뉴에 시너지 효과를 포함하시겠습니까?',
		'ja': '戦闘メニューに相乗効果を含めますか?',
		'pt': 'Incluir Sinergias no Menu de Combate?',
		'pt-br': 'Incluir Sinergias no Menu de Combate?',
		'es': '¿Incluir sinergias en el menú de combate?',
		'ru': 'Включить синергию в боевое меню?',
		'tr': 'Sinerjiler Savaş Menüsü\'ne dahil edilsin mi?',
	},
	'SETTING_BUILD_MENU_1': {
		'en': 'Always',
		'zh-CN': '总是',
		'zh-TW': '總是',
		'fr': 'Toujours',
		'de': 'Stets',
		'it': 'Sempre',
		'ko': '언제나',
		'ja': 'いつも',
		'pt': 'Sempre',
		'pt-br': 'Sempre',
		'es': 'Siempre',
		'ru': 'Всегда',
		'tr': 'Her zaman',
	},
	'SETTING_BUILD_MENU_2': {
		'en': 'On Left Click',
		'zh-CN': '左键单击',
		'zh-TW': '左鍵點選',
		'fr': 'Sur clic gauche',
		'de': 'Beim Linksklick',
		'it': 'Al clic sinistro',
		'ko': '왼쪽 클릭 시',
		'ja': '左クリック時',
		'pt': 'Ao clicar com o botão esquerdo',
		'pt-br': 'Ao clicar com o botão esquerdo',
		'es': 'Al hacer clic izquierdo',
		'ru': 'При левом клике',
		'tr': 'Sol Tıklamada',
	},
	'SETTING_BUILD_MENU_3': {
		'en': 'On Right Click',
		'zh-CN': '右键单击时',
		'zh-TW': '右鍵單擊時',
		'fr': 'Sur clic droit',
		'de': 'Per Rechtsklick',
		'it': 'Fare clic con il tasto destro',
		'ko': '마우스 오른쪽 버튼 클릭 시',
		'ja': '右クリック時',
		'pt': 'Ao clicar com o botão direito',
		'pt-br': 'Ao clicar com o botão direito',
		'es': 'Al hacer clic derecho',
		'ru': 'При щелчке правой кнопкой мыши',
		'tr': 'Sağ Tıklamada',
	},
	'SETTING_BUILD_MENU_4': {
		'en': 'Never',
		'zh-CN': '绝不',
		'zh-TW': '絕不',
		'fr': 'Jamais',
		'de': 'Niemals',
		'it': 'Mai',
		'ko': '절대',
		'ja': '一度もない',
		'pt': 'Nunca',
		'pt-br': 'Nunca',
		'es': 'Nunca',
		'ru': 'Никогда',
		'tr': 'Asla',
	},
	'SETTING_AGILITY_COST': {
		'en': 'Use these when updating Obstacle Backgrounds?',
		'zh-CN': '更新障碍物背景时使用这些吗？',
		'zh-TW': '更新障礙物背景時要使用這些嗎？',
		'fr': 'Les utiliser lors de la mise à jour des arrière-plans d\'obstacles ?',
		'de': 'Verwenden Sie diese beim Aktualisieren von Hindernishintergründen?',
		'it': 'Usarli quando aggiorni gli sfondi degli ostacoli?',
		'ko': '장애물 배경을 업데이트할 때 이것을 사용하시겠습니까?',
		'ja': '障害物の背景を更新するときにこれらを使用しますか?',
		'pt': 'Use-os ao atualizar Fundos de Obstáculos?',
		'pt-br': 'Use-os ao atualizar Fundos de Obstáculos?',
		'es': '¿Utilizarlos al actualizar los fondos de obstáculos?',
		'ru': 'Использовать их при обновлении фона препятствий?',
		'tr': 'Engel Arka Planlarını güncellerken bunlar kullanılsın mı?',
	},
	'SETTING_AGILITY_COST_HINT': {
		'en': 'When an obstacle\'s background color is being updated, it will account for the cost reduction from these items.',
		'zh-CN': '当更新障碍物的背景颜色时，它将考虑这些项目的成本降低。',
		'zh-TW': '當更新障礙物的背景顏色時，它將考慮這些項目的成本降低。',
		'fr': 'Lorsque la couleur d\'arrière-plan d\'un obstacle est mise à jour, cela tiendra compte de la réduction du coût de ces éléments.',
		'de': 'Wenn die Hintergrundfarbe eines Hindernisses aktualisiert wird, wird die Kostenreduzierung durch diese Gegenstände berücksichtigt.',
		'it': 'Quando il colore di sfondo di un ostacolo viene aggiornato, ciò terrà conto della riduzione del costo derivante da questi elementi.',
		'ko': '장애물의 배경색이 업데이트되면 해당 항목의 비용이 절감됩니다.',
		'ja': '障害物の背景色が更新されるとき、これらのアイテムによるコスト削減が考慮されます。',
		'pt': 'Quando a cor de fundo de um obstáculo estiver sendo atualizada, isso será responsável pela redução de custo desses itens.',
		'pt-br': 'Quando a cor de fundo de um obstáculo estiver sendo atualizada, isso será responsável pela redução de custo desses itens.',
		'es': 'Cuando se actualiza el color de fondo de un obstáculo, se tendrá en cuenta la reducción de costos de estos elementos.',
		'ru': 'Когда цвет фона препятствия обновляется, это учитывает снижение стоимости этих предметов.',
		'tr': 'Bir engelin arka plan rengi güncellendiğinde bu öğelerden kaynaklanan maliyet düşüşü hesaba katılacaktır.',
	},
	'SETTING_OPACITY': {
		'en': 'Add Opacity to unused slot icons?',
		'zh-CN': '为未使用的插槽图标添加不透明度？',
		'zh-TW': '為未使用的插槽圖示新增不透明度？',
		'fr': 'Ajouter de l\'opacité aux icônes d\'emplacements inutilisées ?',
		'de': 'Den ungenutzten Slot-Symbolen Deckkraft hinzufügen?',
		'it': 'Aggiungere opacità alle icone degli slot inutilizzati?',
		'ko': '사용하지 않는 슬롯 아이콘에 불투명도를 추가하시겠습니까?',
		'ja': '未使用のスロットアイコンに不透明度を追加しますか?',
		'pt': 'Adicionar opacidade aos ícones de slots não utilizados?',
		'pt-br': 'Adicionar opacidade aos ícones de slots não utilizados?',
		'es': '¿Agregar opacidad a los íconos de ranuras no utilizados?',
		'ru': 'Добавить непрозрачность к неиспользуемым значкам слотов?',
		'tr': 'Kullanılmayan yuva simgelerine Opaklık eklensin mi?	',
	},
	'SETTING_OPACITY_HINT': {
		'en': 'When an item (for the current skill) is equipped into an equipment slot, all other items that fit into that slot will have 50% opacity. Works with Obstacles too.',
		'zh-CN': '当一个物品（针对当前技能）装备到装备槽中时，适合该槽的所有其他物品都将设置不透明度。也适用于障碍。',
		'zh-TW': '當一個物品（針對目前技能）裝備到裝備槽時，適合該槽的所有其他物品都會設定不透明度。也適用於障礙。',
		'fr': 'Lorsqu\'un objet (pour la compétence actuelle) est équipé dans un emplacement d\'équipement, tous les autres objets qui rentrent dans cet emplacement auront une opacité définie. Fonctionne également avec les obstacles.',
		'de': 'Wenn ein Gegenstand (für die aktuelle Fertigkeit) in einen Ausrüstungsplatz eingebaut wird, wird für alle anderen Gegenstände, die in diesen Platz passen, die Deckkraft festgelegt. Funktioniert auch mit Hindernissen.',
		'it': 'Quando un oggetto (per l\'abilità corrente) viene equipaggiato in uno slot equipaggiamento, tutti gli altri oggetti che rientrano in quello slot avranno l\'opacità impostata su di essi. Funziona anche con gli ostacoli.',
		'ko': '아이템(현재 스킬용)이 장비 슬롯에 장착되면 해당 슬롯에 맞는 다른 모든 아이템에는 불투명도가 설정됩니다. 장애물과도 작동합니다.',
		'ja': 'アイテム（現在のスキル用）が装備スロットに装備されると、そのスロットに収まる他のすべてのアイテムには不透明度が設定されます。障害物にも対応します。',
		'pt': 'Quando um item (para a habilidade atual) é equipado em um slot de equipamento, todos os outros itens que cabem nesse slot terão a opacidade definida. Também funciona com obstáculos.',
		'pt-br': 'Quando um item (para a habilidade atual) é equipado em um slot de equipamento, todos os outros itens que cabem nesse slot terão a opacidade definida. Também funciona com obstáculos.',
		'es': 'Cuando un elemento (para la habilidad actual) se equipa en una ranura de equipo, todos los demás elementos que quepan en esa ranura tendrán opacidad configurada. También funciona con obstáculos.',
		'ru': 'Когда предмет (для текущего навыка) устанавливается в слот оборудования, для всех остальных предметов, которые помещаются в этот слот, будет установлена ​​непрозрачность. Работает и с препятствиями.',
		'tr': 'Bir eşya (mevcut beceri için) bir ekipman yuvasına takıldığında, o yuvaya uyan diğer tüm eşyaların donukluğu ayarlanacaktır. Engellerle de çalışır.',
	},
	'SETTING_EQUIP_FROM_OTHER_SETS': {
		'en': 'Enable equipping from other equipment sets?',
		'zh-CN': '启用其他设备组的装备吗？',
		'zh-TW': '啟用其他設備組的裝備嗎？',
		'fr': 'Activer l\'équipement à partir d\'autres ensembles d\'équipements ?',
		'de': 'Ausrüsten aus anderen Ausrüstungssets aktivieren?',
		'it': 'Abilitare l\'equipaggiamento da altri set di equipaggiamento?',
		'ko': '다른 장비 세트의 장착을 활성화하시겠습니까?',
		'ja': '他の装備セットからの装備を有効にしますか?',
		'pt': 'Habilitar equipamentos de outros conjuntos de equipamentos?',
		'pt-br': 'Habilitar equipamentos de outros conjuntos de equipamentos?',
		'es': '¿Habilitar el equipamiento desde otros conjuntos de equipos?',
		'ru': 'Включить оснащение из других комплектов оборудования?',
		'tr': 'Diğer donanım setlerinden donatılma etkinleştirilsin mi?',
	},
	'SETTING_EQUIP_FROM_OTHER_SETS_HINT': {
		'en': 'If another mod modifies the Unequip function, this may cause unintended behavior such as items being deleted or duplicated.',
		'zh-CN': '如果另一个 mod 修改了 Unequip 功能，这可能会导致意外行为，例如项目被删除或重复。',
		'zh-TW': '如果另一個 mod 修改了 Unequip 功能，這可能會導致意外行為，例如項目被刪除或重複。',
		'fr': 'Si un autre mod modifie la fonction Unequip, cela peut entraîner un comportement involontaire tel que la suppression ou la duplication d\'éléments.',
		'de': 'Wenn ein anderer Mod die Unequip-Funktion ändert, kann dies zu unbeabsichtigtem Verhalten führen, z. B. zum Löschen oder Duplizieren von Gegenständen.',
		'it': 'Se un\'altra mod modifica la funzione Unequip, ciò potrebbe causare comportamenti imprevisti come l\'eliminazione o la duplicazione di elementi.',
		'ko': '다른 모드가 장비 해제 기능을 수정하면 아이템이 삭제되거나 복제되는 등 의도하지 않은 동작이 발생할 수 있습니다.',
		'ja': '他のMODで装備解除機能を変更すると、アイテムが削除されたり、重複したりするなど、意図しない動作が発生する可能性があります。',
		'pt': 'Se outro mod modificar a função Desequipar, isso pode causar comportamento não intencional, como exclusão ou duplicação de itens.',
		'pt-br': 'Se outro mod modificar a função Desequipar, isso pode causar comportamento não intencional, como exclusão ou duplicação de itens.',
		'es': 'Si otro mod modifica la función Desequipar, esto puede provocar un comportamiento no deseado, como la eliminación o duplicación de elementos.',
		'ru': 'Если другой мод изменяет функцию Unequip, это может привести к непредвиденному поведению, например к удалению или дублированию элементов.',
		'tr': 'Başka bir mod Unequip işlevini değiştirirse bu, öğelerin silinmesi veya çoğaltılması gibi istenmeyen davranışlara neden olabilir.',
	},
	'SETTING_EQUIP_FROM_OTHER_SETS_ERROR': {
		'en': 'A setting must be enabled before items can be unequipped from another equipment set.',
		'zh-CN': '必须先启用一项设置，然后才能从其他装备组中卸下物品。',
		'zh-TW': '必須先啟用一項設置，然後才能從另一個裝備組中卸下物品。',
		'fr': 'Un paramètre doit être activé avant que des objets puissent être déséquipés d’un autre ensemble d’équipements.',
		'de': 'Eine Einstellung muss aktiviert werden, bevor Gegenstände aus einem anderen Ausrüstungssatz entfernt werden können.',
		'it': 'È necessario abilitare un\'impostazione prima che gli oggetti possano essere rimossi da un altro set di equipaggiamento.',
		'ko': '다른 장비 세트에서 아이템을 장착 해제하려면 먼저 설정을 활성화해야 합니다.',
		'ja': '別の装備セットからアイテムを装備解除するには、設定を有効にする必要があります。',
		'pt': 'Uma configuração deve ser habilitada antes que itens possam ser desequipados de outro conjunto de equipamentos.',
		'pt-br': 'Uma configuração deve ser habilitada antes que itens possam ser desequipados de outro conjunto de equipamentos.',
		'es': 'Se debe habilitar una configuración antes de que se puedan desequipar elementos de otro conjunto de equipos.',
		'ru': 'Настройка должна быть включена, прежде чем предметы можно будет снять с другого набора снаряжения.',
		'tr': 'Öğelerin başka bir ekipman setinden çıkarılabilmesi için önce bir ayarın etkinleştirilmesi gerekir.',
	},
};