export const lang = {
	'RESET': {
		'en': 'Reset',
		'zh-CN': '重置',
		'zh-TW': '重置',
		'fr': 'Réinitialiser',
		'de': 'Zurücksetzen',
		'it': 'Ripristina',
		'ko': '초기화',
		'ja': 'リセット',
		'pt': 'Reiniciar',
		'pt-br': 'Reiniciar',
		'es': 'Reiniciar',
		'ru': 'Перезагрузить',
		'tr': 'Sıfırla',
	},
	'PRESETS': {
		'en': 'Presets',
		'zh-CN': '预置',
		'zh-TW': '预置',
		'fr': 'Préconfigurations',
		'de': 'Voreinstellungen',
		'it': 'Preimpostazioni',
		'ko': '사전 설정',
		'ja': 'プリセット',
		'pt': 'Predefinições',
		'pt-br': 'Predefinições',
		'es': 'Preajustes',
		'ru': 'Пресеты',
		'tr': 'Ön ayarlar',
	},
	'BOOSTS': {
		'en': 'Boosts',
		'zh-CN': '提升',
		'zh-TW': '提升',
		'fr': 'Augmentation',
		'de': 'Steigert',
		'it': 'Aumenta',
		'ko': '부스트',
		'ja': 'ブースト',
		'pt': 'Aumenta',
		'pt-br': 'Aumenta',
		'es': 'Impulso',
		'ru': 'Повышает',
		'tr': 'Artış',
	},
	'FILTER': {
		'en': 'Filter',
		'zh-CN': '筛选',
		'zh-TW': '篩選',
		'fr': 'Filtre',
		'de': 'Filter',
		'it': 'Filtro',
		'ko': '필터',
		'ja': 'フィルター',
		'pt': 'Filtro',
		'pt-br': 'Filtro',
		'es': 'Filtrar',
		'ru': 'Фильтр',
		'tr': 'Filtre',
	},
	'OTHERS': {
		'en': 'Others',
		'zh-CN': '其他的',
		'zh-TW': '其他的',
		'fr': 'Autres',
		'de': 'Andere',
		'it': 'Altri',
		'ko': '기타',
		'ja': 'その他',
		'pt': 'Outros',
		'pt-br': 'Outros',
		'es': 'Otros',
		'ru': 'Другие',
		'tr': 'Diğerleri',
	},
	'CONSTELLATION': {
		'en': 'Constellation',
		'zh-CN': '星座',
		'zh-TW': '星座',
		'fr': 'Constellation',
		'de': 'Konstellation',
		'it': 'Costellazione',
		'ko': '별자리',
		'ja': '星座',
		'pt': 'constelação',
		'pt-br': 'constelação',
		'es': 'Constelación',
		'ru': 'Созвездие',
		'tr': 'takımyıldız',
	},
	'PURCHASES': {
		'en': 'Purchases',
		'zh-CN': '购买',
		'zh-TW': '購買',
		'fr': 'Achats',
		'de': 'Einkäufe',
		'it': 'Acquisti',
		'ko': '구매',
		'ja': '購入品',
		'pt': 'Compras',
		'pt-br': 'Compras',
		'es': 'Compras',
		'ru': 'Покупки',
		'tr': 'Satın almalar',
	},
	'SYNERGIES': {
		'en': 'Synergies',
		'zh-CN': '协同效应',
		'zh-TW': '綜效',
		'fr': 'Synergies',
		'de': 'Synergien',
		'it': 'Sinergie',
		'ko': '시너지 효과',
		'ja': '相乗効果',
		'pt': 'Sinergias',
		'pt-br': 'Sinergias',
		'es': 'Sinergias',
		'ru': 'Синергия',
		'tr': 'Sinerjiler',
	},
	'POSITIVE': {
		'en': 'Positive',
		'zh-CN': '积极的',
		'zh-TW': '積極的',
		'fr': 'Positif',
		'de': 'Positiv',
		'it': 'Positivo',
		'ko': '긍정적인',
		'ja': 'ポジティブ',
		'pt': 'Positivo',
		'pt-br': 'Positivo',
		'es': 'Positivo',
		'ru': 'Положительный',
		'tr': 'Pozitif',
	},
	'NEGATIVE': {
		'en': 'Negative',
		'zh-CN': '消极的',
		'zh-TW': '消極的',
		'fr': 'Négatif',
		'de': 'Negativ',
		'it': 'Negativo',
		'ko': '부정적인',
		'ja': 'ネガティブ',
		'pt': 'Negativo',
		'pt-br': 'Negativo',
		'es': 'Negativo',
		'ru': 'Отрицательный',
		'tr': 'Olumsuz',
	},
	'DEFAULT': {
		'en': 'Default',
		'zh-CN': '默认',
		'zh-TW': '預設',
		'fr': 'Défaut',
		'de': 'Standard',
		'it': 'Predefinito',
		'ko': '기본',
		'ja': 'デフォルト',
		'pt': 'Padrão',
		'pt-br': 'Padrão',
		'es': 'Por defecto',
		'ru': 'По умолчанию',
		'tr': 'Varsayılan',
	},
	'CUSTOM': {
		'en': 'Custom',
		'zh-CN': '风俗',
		'zh-TW': '風俗',
		'fr': 'Coutume',
		'de': 'Brauch',
		'it': 'Costume',
		'ko': '관습',
		'ja': 'カスタム',
		'pt': 'Personalizado',
		'pt-br': 'Personalizado',
		'es': 'Costumbre',
		'ru': 'Обычай',
		'tr': 'Gelenek',
	},
	'EDIT': {
		'en': 'Edit',
		'zh-CN': '编辑',
		'zh-TW': '編輯',
		'fr': 'Éditer',
		'de': 'Bearbeiten',
		'it': 'Modifica',
		'ko': '편집하다',
		'ja': '編集',
		'pt': 'Editar',
		'pt-br': 'Editar',
		'es': 'Editar',
		'ru': 'Редактировать',
		'tr': 'Düzenle',
	},
	'CHANCE': {
		'en': 'Chance:',
		'zh-CN': '机会：',
		'zh-TW': '機會：',
		'fr': 'Chance:',
		'de': 'Chance:',
		'it': 'Opportunità:',
		'ko': '가능성:',
		'ja': 'チャンス：',
		'pt': 'Chance:',
		'pt-br': 'Chance:',
		'es': 'Oportunidad:',
		'ru': 'Шанс:',
		'tr': 'Şans:',
	},
	'SEARCH': {
		'en': 'Search',
		'zh-CN': '搜索',
		'zh-TW': '搜尋',
		'fr': 'Recherche',
		'de': 'Suchen',
		'it': 'Ricerca',
		'ko': '찾다',
		'ja': '検索',
		'pt': 'Procurar',
		'pt-br': 'Procurar',
		'es': 'Buscar',
		'ru': 'Поиск',
		'tr': 'Arama Yapın',
	},
	'INACTIVE': {
		'en': 'This is currently Inactive.',
		'zh-CN': '目前该项目处于非活动状态。',
		'zh-TW': '目前該項目處於非活動狀態。',
		'fr': 'Ceci est actuellement inactif.',
		'de': 'Dies ist derzeit inaktiv.',
		'it': 'Questo è attualmente inattivo.',
		'ko': '현재 비활성 상태입니다.',
		'ja': 'これは現在非アクティブです。',
		'pt': 'Atualmente está inativo.',
		'pt-br': 'Atualmente está inativo.',
		'es': 'Actualmente está inactivo.',
		'ru': 'В настоящее время это неактивно.',
		'tr': 'Bu şu anda Aktif Değildir.',
	},
	'PASSIVE': {
		'en': 'This item is in the Passive Slot.',
		'zh-CN': '该物品位于被动槽中。',
		'zh-TW': '該物品位於被動槽中。',
		'fr': 'Cet objet se trouve dans l\'emplacement passif.',
		'de': 'Dieser Gegenstand befindet sich im Passiv-Slot.',
		'it': 'Questo oggetto è nello slot passivo.',
		'ko': '이 아이템은 패시브 슬롯에 있습니다.',
		'ja': 'このアイテムはパッシブ スロットにあります。',
		'pt': 'Este item está no Slot Passivo.',
		'pt-br': 'Este item está no Slot Passivo.',
		'es': 'Este elemento está en la ranura pasiva.',
		'ru': 'Этот предмет находится в пассивном слоте.',
		'tr': 'Bu öğe Pasif Yuvadadır.',
	},
	'SELECT_OBSTACLE': {
		'en': 'Select Obstacle',
		'zh-CN': '选择障碍物',
		'zh-TW': '選擇障礙物',
		'fr': 'Sélectionnez un obstacle',
		'de': 'Wählen Sie Hindernis',
		'it': 'Seleziona Ostacolo',
		'ko': '장애물 선택',
		'ja': '障害物を選択してください',
		'pt': 'Selecione Obstáculo',
		'pt-br': 'Selecione Obstáculo',
		'es': 'Seleccionar obstáculo',
		'ru': 'Выберите Препятствие',
		'tr': 'Engel Seç',
	},
	'SELECT_SLOT': {
		'en': 'Select Slot',
		'zh-CN': '选择插槽',
		'zh-TW': '選擇插槽',
		'fr': 'Sélectionnez un emplacement',
		'de': 'Wählen Sie Steckplatz',
		'it': 'Seleziona Slot',
		'ko': '슬롯 선택',
		'ja': 'スロットの選択',
		'pt': 'Selecione o slot',
		'pt-br': 'Selecione o slot',
		'es': 'Seleccionar ranura',
		'ru': 'Выберите слот',
		'tr': 'Slot Seç',
	},
	'HIDE_MODIFIERS': {
		'en': 'Hide Modifiers',
		'zh-CN': '隐藏修饰符',
		'zh-TW': '隱藏修飾符',
		'fr': 'Masquer les modificateurs',
		'de': 'Modifikatoren ausblenden',
		'it': 'Nascondi modificatori',
		'ko': '수정자 숨기기',
		'ja': '修飾子を隠す',
		'pt': 'Ocultar modificadores',
		'pt-br': 'Ocultar modificadores',
		'es': 'Ocultar modificadores',
		'ru': 'Скрыть модификаторы',
		'tr': 'Değiştiricileri Gizle',
	},
	'FILTER_MODE': {
		'en': 'Filter Mode Active!',
		'zh-CN': '过滤模式活动！',
		'zh-TW': '過濾模式活動！',
		'fr': 'Mode filtre Actif!',
		'de': 'Filtermodus aktiv!',
		'it': 'Modalità filtro attivo!',
		'ko': '필터 모드 활성!',
		'ja': 'フィルターモードアクティブ！',
		'pt': 'Modo de filtro ativo!',
		'pt-br': 'Modo de filtro ativo!',
		'es': '¡Modo de filtro activo!',
		'ru': 'Режим фильтра Active!',
		'tr': 'Filtre modu etkin!',
	},
	'MASS_FILTER': {
		'en': 'Mass filter icons?',
		'zh-CN': '质量过滤器图标？',
		'zh-TW': '質量過濾器圖標？',
		'fr': 'Icônes de filtre de masse?',
		'de': 'Massenfiltersymbole?',
		'it': 'Icone del filtro di massa?',
		'ko': '대량 필터 아이콘?',
		'ja': 'マスフィルターアイコン？',
		'pt': 'Ícones do filtro de massa?',
		'pt-br': 'Ícones do filtro de massa?',
		'es': 'Iconos de filtro de masa?',
		'ru': 'Массовые значки?',
		'tr': 'Kütle filtre simgeleri?',
	},
	'LOCKED_SYNERGY': {
		'en': 'This Synergy is not unlocked.',
		'zh-CN': '此协同作用尚未解锁。',
		'zh-TW': '此協同作用尚未解鎖。',
		'fr': 'Cette synergie n\'est pas débloquée.',
		'de': 'Diese Synergie ist nicht freigeschaltet.',
		'it': 'Questa sinergia non è sbloccata.',
		'ko': '이 시너지는 잠금 해제되지 않았습니다.',
		'ja': 'このシナジーはロック解除されていません。',
		'pt': 'Esta sinergia não está desbloqueada.',
		'pt-br': 'Esta sinergia não está desbloqueada.',
		'es': 'Esta Sinergia no está desbloqueada.',
		'ru': 'Эта синергия не разблокирована.',
		'tr': 'Bu Sinerjinin kilidi açılmamıştır.',
	},
	'NOT_ACTIVE': {
		'en': '${skillName} must be active',
		'zh-CN': '${skillName} 必须处于活动状态',
		'zh-TW': '${skillName} 必須處於作用中狀態',
		'fr': '${skillName} doit être actif',
		'de': '${skillName} muss aktiv sein',
		'it': '${skillName} deve essere attivo',
		'ko': '${skillName} 이(가) 활성화되어 있어야 합니다.',
		'ja': '${skillName} はアクティブである必要があります',
		'pt': '${skillName} deve estar ativo',
		'pt-br': '${skillName} deve estar ativo',
		'es': '${skillName} debe estar activo',
		'ru': '${skillName} должен быть активен',
		'tr': '${skillName} etkin olmalı',
	},
	'MASTERY_ACTION': {
		'en': 'An action with Mastery must be active.',
		'zh-CN': '精通的动作必须是活跃的。',
		'zh-TW': '精通的動作必須是活躍的。',
		'fr': 'Une action avec Maîtrise doit être active.',
		'de': 'Eine Aktion mit Meisterschaft muss aktiv sein.',
		'it': 'Un\'azione con Maestria deve essere attiva.',
		'ko': '숙달이 있는 행동은 활성화되어야 합니다.',
		'ja': 'マスタリーのあるアクションがアクティブである必要があります。',
		'pt': 'Uma ação com Maestria deve estar ativa.',
		'pt-br': 'Uma ação com Maestria deve estar ativa.',
		'es': 'Una acción con Maestría debe estar activa.',
		'ru': 'Действие с мастерством должно быть активным.',
		'tr': 'Ustalık içeren bir eylem aktif olmalıdır.',
	},
	'FILTERED_ICON': {
		'en': 'This icon is filtered.',
		'zh-CN': '该图标已被过滤。',
		'zh-TW': '該圖標已被過濾。',
		'fr': 'Cette icône est filtrée.',
		'de': 'Dieses Symbol ist gefiltert.',
		'it': 'Questa icona è filtrata.',
		'ko': '이 아이콘은 필터링되었습니다.',
		'ja': 'このアイコンはフィルタリングされています。',
		'pt': 'Este ícone é filtrado.',
		'pt-br': 'Este ícone é filtrado.',
		'es': 'Este icono está filtrado.',
		'ru': 'Этот значок отфильтрован.',
		'tr': 'Bu simge filtrelenmiştir.',
	},
	'SETTING_FILTER': {
		'en': 'Mass filter by ID?',
		'zh-CN': '按 ID 进行质量过滤？',
		'zh-TW': '按 ID 進行品質過濾？',
		'fr': 'Filtrer en masse par ID ?',
		'de': 'Massenfilter nach ID?',
		'it': 'Filtro di massa per ID?',
		'ko': 'ID로 대량 필터링을 하시겠습니까?',
		'ja': 'IDによるマスフィルター?',
		'pt': 'Filtrar em massa por ID?',
		'pt-br': 'Filtrar em massa por ID?',
		'es': '¿Filtro masivo por ID?',
		'ru': 'Массовый фильтр по ID?',
		'tr': 'Kimliğe göre toplu filtre?',
	},
	'REQUIRES_RESTART': {
		'en': 'Requires a restart to take effect.',
		'zh-CN': '需要重启才能生效。',
		'zh-TW': '需要重啟才能生效。',
		'fr': 'Nécessite un redémarrage pour prendre effet.',
		'de': 'Erfordert einen Neustart, um wirksam zu werden.',
		'it': 'Richiede un riavvio per avere effetto.',
		'ko': '적용하려면 다시 시작해야 합니다.',
		'ja': '有効にするには再起動が必要です。',
		'pt': 'Requer uma reinicialização para entrar em vigor.',
		'pt-br': 'Requer uma reinicialização para entrar em vigor.',
		'es': 'Requiere un reinicio para que surta efecto.',
		'ru': 'Требуется перезагрузка, чтобы изменения вступили в силу.',
		'tr': 'Etkili olması için yeniden başlatma gerekir.',
	},
	'CREATE_PRESET': {
		'en': 'Create a Preset',
		'zh-CN': '创建预设',
		'zh-TW': '建立預設',
		'fr': 'Créer un préréglage',
		'de': 'Erstellen Sie eine Voreinstellung',
		'it': 'Crea una preimpostazione',
		'ko': '사전 설정 만들기',
		'ja': 'プリセットを作成する',
		'pt': 'Crie uma predefinição',
		'pt-br': 'Crie uma predefinição',
		'es': 'Crear un preajuste',
		'ru': 'Создать пресет',
		'tr': 'Ön Ayar Oluştur',
	},
	'SUPERIOR_ONLY': {
		'en': '(Superior only)',
		'zh-CN': '（仅限卓越）',
		'zh-TW': '（僅限卓越）',
		'fr': '(Supérieur seulement)',
		'de': '(Nur Superior)',
		'it': '(Solo superiore)',
		'ko': '(슈페리어 전용)',
		'ja': '(スーペリアのみ)',
		'pt': '(Somente superiores)',
		'pt-br': '(Somente superiores)',
		'es': '(Solo superiores)',
		'ru': '(Только для Превосходная)',
		'tr': '(Yalnızca Superior)',
	},
	'SETTING_FILTER_DESC': {
		'en': 'Filters everything this mod checks for.',
		'zh-CN': '过滤此 mod 检查的所有内容。',
		'zh-TW': '過濾此 mod 檢查的所有內容。',
		'fr': 'Filtre tout ce que ce mod vérifie.',
		'de': 'Filtert alles, wonach dieser Mod sucht.',
		'it': 'Filtra tutto ciò che controlla questa mod.',
		'ko': '이 모드가 확인하는 모든 것을 필터링합니다.',
		'ja': 'この MOD がチェックするすべてのものをフィルターします。',
		'pt': 'Filtra tudo o que este mod verifica.',
		'pt-br': 'Filtra tudo o que este mod verifica.',
		'es': 'Filtra todo lo que busca este mod.',
		'ru': 'Фильтрует все, что проверяет этот мод.',
		'tr': 'Bu modun kontrol ettiği her şeyi filtreler.',
	},
	'SETTING_RESET_DATA': {
		'en': 'Reset all filtered items?',
		'zh-CN': '重置所有过滤的项目？',
		'zh-TW': '重置所有過濾的項目？',
		'fr': 'Réinitialiser tous les éléments filtrés ?',
		'de': 'Alle gefilterten Elemente zurücksetzen?',
		'it': 'Reimpostare tutti gli elementi filtrati?',
		'ko': '필터링된 항목을 모두 재설정하시겠습니까?',
		'ja': 'フィルタリングされた項目をすべてリセットしますか?',
		'pt': 'Redefinir todos os itens filtrados?',
		'pt-br': 'Redefinir todos os itens filtrados?',
		'es': '¿Restablecer todos los elementos filtrados?',
		'ru': 'Сбросить все отфильтрованные элементы?',
		'tr': 'Filtrelenen tüm öğeler sıfırlansın mı?',
	},
	'SETTING_MENU_STATE': {
		'en': 'What state should the menu be in when loading a save?',
		'zh-CN': '加载保存时菜单应处于什么状态？',
		'zh-TW': '載入儲存時選單應處於什麼狀態？',
		'fr': 'Dans quel état doit être le menu lors du chargement d\'une sauvegarde ?',
		'de': 'In welchem ​​Zustand sollte sich das Menü beim Laden eines Speicherstandes befinden?',
		'it': 'In quale stato dovrebbe trovarsi il menu durante il caricamento di un salvataggio?',
		'ko': '저장 파일을 로드할 때 메뉴는 어떤 상태여야 합니까?',
		'ja': 'セーブデータをロードするとき、メニューはどの状態にあるべきですか?',
		'pt': 'Em que estado o menu deve estar ao carregar um salvamento?',
		'pt-br': 'Em que estado o menu deve estar ao carregar um salvamento?',
		'es': '¿En qué estado debe estar el menú al cargar un guardado?',
		'ru': 'В каком состоянии должно быть меню при загрузке сохранения?',
		'tr': 'Bir kayıt yüklenirken menü hangi durumda olmalıdır?',
	},
	'SETTING_MENU_STATE_1': {
		'en': 'Remember Previous State',
		'zh-CN': '记住之前的状态',
		'zh-TW': '記住之前的狀態',
		'fr': 'Mémoriser l\'état précédent',
		'de': 'Vorherigen Status merken',
		'it': 'Ricorda lo stato precedente',
		'ko': '이전 상태 기억',
		'ja': '以前の状態を記憶する',
		'pt': 'Lembre-se do estado anterior',
		'pt-br': 'Lembre-se do estado anterior',
		'es': 'Recordar estado anterior',
		'ru': 'Запомнить предыдущее состояние',
		'tr': 'Önceki Durumu Hatırla',
	},
	'SETTING_MENU_STATE_2': {
		'en': 'Always Start Closed',
		'zh-CN': '始终开始关闭',
		'zh-TW': '始終開始關閉',
		'fr': 'Toujours démarrer fermé',
		'de': 'Immer geschlossen starten',
		'it': 'Inizia sempre chiuso',
		'ko': '항상 시작은 닫혀 있음',
		'ja': '常に閉じて開始する',
		'pt': 'Sempre comece fechado',
		'pt-br': 'Sempre comece fechado',
		'es': 'Empezar siempre cerrado',
		'ru': 'Всегда начинать с закрытого',
		'tr': 'Daima Kapalı Başlat',
	},
	'SETTING_MENU_STATE_3': {
		'en': 'Always Start Opened',
		'zh-CN': '始终开始打开',
		'zh-TW': '始終開始打開',
		'fr': 'Toujours commencer ouvert',
		'de': 'Immer geöffnet starten',
		'it': 'Inizia sempre aperto',
		'ko': '항상 시작이 열려 있음',
		'ja': '常に開いた状態で開始します',
		'pt': 'Sempre comece aberto',
		'pt-br': 'Sempre comece aberto',
		'es': 'Empezar siempre abierto',
		'ru': 'Всегда начинать открытым',
		'tr': 'Daima Açık Başla',
	},
	'SETTING_REALM_STATE': {
		'en': 'What realm should be selected when loading a save?',
		'zh-CN': '加载存档时应选择哪个领域？',
		'zh-TW': '載入存檔時應選擇哪個領域？',
		'fr': 'Quel domaine faut-il sélectionner lors du chargement d\'une sauvegarde ?',
		'de': 'Welcher Realm sollte beim Laden eines Speicherstands ausgewählt werden?',
		'it': 'Quale regno dovrebbe essere selezionato quando si carica un salvataggio?',
		'ko': '저장 파일을 로드할 때 어떤 영역을 선택해야 합니까?',
		'ja': 'セーブデータをロードするときにどのレルムを選択する必要がありますか?',
		'pt': 'Qual reino deve ser selecionado ao carregar um save?',
		'pt-br': 'Qual reino deve ser selecionado ao carregar um save?',
		'es': '¿Qué reino se debe seleccionar al cargar un guardado?',
		'ru': 'Какой мир следует выбирать при загрузке сохранения?',
		'tr': 'Bir kaydetme yüklenirken hangi bölge seçilmelidir?',
	},
	'SETTING_REALM_STATE_1': {
		'en': 'Remember Previous Realm',
		'zh-CN': '记住上一个境界',
		'zh-TW': '記住上一個境界',
		'fr': 'Se souvenir du royaume précédent',
		'de': 'Erinnern Sie sich an das vorherige Reich',
		'it': 'Ricorda il regno precedente',
		'ko': '이전 영역 기억',
		'ja': '以前のレルムを記憶する',
		'pt': 'Lembre-se do reino anterior',
		'pt-br': 'Lembre-se do reino anterior',
		'es': 'Recuerda el reino anterior',
		'ru': 'Помните предыдущую реальность',
		'tr': 'Önceki Bölgeyi Hatırla',
	},
	'SETTING_REALM_STATE_2': {
		'en': 'Always Start Default',
		'zh-CN': '始终默认启动',
		'zh-TW': '始終預設啟動',
		'fr': 'Toujours démarrer par défaut',
		'de': 'Immer standardmäßig starten',
		'it': 'Avvia sempre predefinito',
		'ko': '항상 시작 기본값',
		'ja': '常にデフォルトで開始',
		'pt': 'Sempre iniciar padrão',
		'pt-br': 'Sempre iniciar padrão',
		'es': 'Iniciar siempre por defecto',
		'ru': 'Всегда начинать по умолчанию',
		'tr': 'Her Zaman Varsayılanı Başlat',
	},
	'SETTING_REALM_STATE_3': {
		'en': 'Always Start Melvor',
		'zh-CN': '始终启动“Melvor”',
		'zh-TW': '始終啟動“Melvor”',
		'fr': 'Toujours démarrer Melvor',
		'de': 'Starten Sie immer Melvor',
		'it': 'Avvia sempre Melvor',
		'ko': '항상 Melvor 시작',
		'ja': '常に「Melvor」を起動します',
		'pt': 'Sempre comece Melvor',
		'pt-br': 'Sempre comece Melvor',
		'es': 'Empiece siempre con Melvor',
		'ru': 'Всегда начинайте Мелвор',
		'tr': 'Her Zaman Melvor\'u Başlat',
	},
	'SETTING_REALM_STATE_4': {
		'en': 'Always Start Abyssal',
		'zh-CN': '始终启动深渊',
		'zh-TW': '始終啟動深淵',
		'fr': 'Commencez toujours Abyssal',
		'de': 'Starten Sie immer Abyssal',
		'it': 'Inizia sempre Abissale',
		'ko': '항상 어비설을 시작하세요',
		'ja': '常に深淵を開始する',
		'pt': 'Sempre inicie o Abyssal',
		'pt-br': 'Sempre inicie o Abyssal',
		'es': 'Siempre comienza abisal',
		'ru': 'Всегда начинайте с Бездны',
		'tr': 'Daima Abyssal\'i Başlat',
	},
	'SETTING_AUTO_REALM': {
		'en': 'Automatically filter icons by Realm?',
		'zh-CN': '按领域自动过滤图标？',
		'zh-TW': '按領域自動過濾圖示？',
		'fr': 'Filtrer automatiquement les icônes par domaine ?',
		'de': 'Symbole automatisch nach Bereich filtern?',
		'it': 'Filtrare automaticamente le icone per Realm?',
		'ko': '영역별로 아이콘을 자동으로 필터링하시겠습니까?',
		'ja': 'レルムごとにアイコンを自動的にフィルタリングしますか?',
		'pt': 'Filtrar ícones automaticamente por Realm?',
		'pt-br': 'Filtrar ícones automaticamente por Realm?',
		'es': '¿Filtrar iconos automáticamente por reino?',
		'ru': 'Автоматически фильтровать значки по Realm?',
		'tr': 'Simgeler bölgeye göre otomatik olarak filtrelensin mi?',
	},
	'SETTING_ALLBUTX': {
		'en': 'Keep this amount of Consumables in the Bank',
		'zh-CN': '将这笔消耗品存入银行',
		'zh-TW': '將這筆消耗品存入銀行',
		'fr': 'Conservez cette quantité de consommables en banque',
		'de': 'Bewahren Sie diese Menge an Verbrauchsmaterialien in der Bank auf',
		'it': 'Mantieni questa quantità di materiali di consumo nella banca',
		'ko': '이만큼의 소모품을 은행에 보관하세요',
		'ja': 'この量の消耗品を銀行に保管してください',
		'pt': 'Mantenha esta quantidade de consumíveis no banco',
		'pt-br': 'Mantenha esta quantidade de consumíveis no banco',
		'es': 'Mantenga esta cantidad de consumibles en el banco.',
		'ru': 'Храните это количество Расходных материалов в Банке.',
		'tr': 'Bu miktarda Sarf Malzemesini Bankada tutun',
	},
	'SETTING_ALLBUTX_DESC': {
		'en': 'The quantity on the Icon will be reduced by this value',
		'zh-CN': '图标上的数量将减少该值',
		'zh-TW': '圖標上的數量將減少該值',
		'fr': 'La quantité sur l\'Icône sera réduite de cette valeur',
		'de': 'Die Menge auf dem Icon wird um diesen Wert reduziert',
		'it': 'La quantità sull\'icona verrà ridotta di questo valore',
		'ko': '아이콘의 수량은 이 값만큼 감소됩니다.',
		'ja': 'アイコン上の数量がこの値だけ減ります',
		'pt': 'A quantidade no Ícone será reduzida por este valor',
		'pt-br': 'A quantidade no Ícone será reduzida por este valor',
		'es': 'La cantidad en el ícono se reducirá en este valor.',
		'ru': 'Количество на значке будет уменьшено на это значение.',
		'tr': 'Simgedeki miktar bu değer kadar azaltılacak',
	},
	'ITEM_DESC_1': {
		'en': 'Item is currently Equipped',
		'zh-CN': '物品目前已装备',
		'zh-TW': '物品目前已裝備',
		'fr': 'L\'objet est actuellement équipé',
		'de': 'Der Artikel ist derzeit ausgerüstet',
		'it': 'L\'oggetto è attualmente equipaggiato',
		'ko': '현재 아이템이 장착되어 있습니다',
		'ja': 'アイテムは現在装備されています',
		'pt': 'O item está atualmente equipado',
		'pt-br': 'O item está atualmente equipado',
		'es': 'El artículo está equipado actualmente',
		'ru': 'Предмет в настоящее время оборудован',
		'tr': 'Öğe şu anda Donatılmıştır',
	},
	'ITEM_DESC_2': {
		'en': 'You have this in the Bank.',
		'zh-CN': '你在银行里有这个。',
		'zh-TW': '你在銀行有這個。',
		'fr': 'Vous avez ceci à la banque.',
		'de': 'Sie haben das in der Bank.',
		'it': 'Hai questo in banca.',
		'ko': '당신은 이것을 은행에 가지고 있습니다.',
		'ja': 'これは銀行にあります。',
		'pt': 'Você tem isso no banco.',
		'pt-br': 'Você tem isso no banco.',
		'es': 'Tienes esto en el banco.',
		'ru': 'Это у вас есть в Банке.',
		'tr': 'Bankada bu var.',
	},
	'ITEM_DESC_3': {
		'en': 'Item is in another Equipment set.',
		'zh-CN': '物品位于另一套装备中。',
		'zh-TW': '物品位於另一套裝備中。',
		'fr': 'L\'objet se trouve dans un autre ensemble d\'équipement.',
		'de': 'Der Gegenstand befindet sich in einem anderen Ausrüstungsset.',
		'it': 'L\'oggetto si trova in un altro set di equipaggiamento.',
		'ko': '아이템이 다른 장비 세트에 있습니다.',
		'ja': 'アイテムは別の装備セットにあります。',
		'pt': 'O item está em outro conjunto de equipamentos.',
		'pt-br': 'O item está em outro conjunto de equipamentos.',
		'es': 'El artículo está en otro conjunto de equipo.',
		'ru': 'Предмет находится в другом наборе снаряжения.',
		'tr': 'Öğe başka bir Ekipman setinde.',
	},
	'ITEM_DESC_4': {
		'en': 'You do not have this item.',
		'zh-CN': '您没有该商品。',
		'zh-TW': '您沒有該商品。',
		'fr': 'Vous n\'avez pas cet article.',
		'de': 'Sie haben diesen Artikel nicht.',
		'it': 'Non hai questo articolo.',
		'ko': '이 항목이 없습니다.',
		'ja': 'このアイテムはありません。',
		'pt': 'Você não possui este item.',
		'pt-br': 'Você não possui este item.',
		'es': 'No tienes este artículo.',
		'ru': 'У вас нет этого товара.',
		'tr': 'Bu öğeye sahip değilsiniz.',
	},
	'ITEM_DESC_5': {
		'en': 'You have more in the Bank.',
		'zh-CN': '你银行里还有更多钱。',
		'zh-TW': '你銀行還有更多錢。',
		'fr': 'Vous en avez plus à la banque.',
		'de': 'Sie haben mehr auf der Bank.',
		'it': 'Ne hai di più in banca.',
		'ko': '은행에 더 많은 것이 있습니다.',
		'ja': '銀行にはさらに多くのものがあります。',
		'pt': 'Você tem mais no banco.',
		'pt-br': 'Você tem mais no banco.',
		'es': 'Tienes más en el banco.',
		'ru': 'У вас есть еще в банке.',
		'tr': 'Bankada daha fazlası var.',
	},
	'ITEM_DESC_6': {
		'en': 'Clicking on the icon will Equip the item into the main slot.',
		'zh-CN': '单击该图标会将物品装备到主插槽中。',
		'zh-TW': '點擊該圖示會將物品裝備到主插槽。',
		'fr': 'Cliquer sur l\'icône équipera l\'objet dans l\'emplacement principal.',
		'de': 'Durch Klicken auf das Symbol wird der Gegenstand im Hauptslot ausgerüstet.',
		'it': 'Facendo clic sull\'icona l\'oggetto verrà equipaggiato nello slot principale.',
		'ko': '아이콘을 클릭하면 해당 아이템이 메인 슬롯에 장착됩니다.',
		'ja': 'アイコンをクリックすると、メインスロットにアイテムが装備されます。',
		'pt': 'Clicar no ícone equipará o item no slot principal.',
		'pt-br': 'Clicar no ícone equipará o item no slot principal.',
		'es': 'Al hacer clic en el icono, se equipará el artículo en la ranura principal.',
		'ru': 'Нажав на значок, вы установите предмет в основной слот.',
		'tr': 'Simgeye tıklamak, öğeyi ana yuvaya yerleştirecektir.',
	},
	'ITEM_DESC_7': {
		'en': 'Right Clicking (Long Hold on mobile) will Equip them into the secondary slot. If there are more than 2 slots, a menu will open.',
		'zh-CN': '右键单击（在移动设备上长按）会将它们装备到辅助插槽中。如果有超过 2 个插槽，则会打开一个菜单。',
		'zh-TW': '右鍵單擊（在行動裝置上長按）會將它們裝備到輔助插槽中。如果有超過 2 個插槽，則會開啟一個選單。',
		'fr': 'Un clic droit (maintien prolongé sur mobile) les équipera dans l\'emplacement secondaire. S\'il y a plus de 2 emplacements, un menu s\'ouvrira.',
		'de': 'Durch Klicken mit der rechten Maustaste (langes Halten auf dem Mobilgerät) werden sie im sekundären Slot ausgerüstet. Bei mehr als 2 Slots öffnet sich ein Menü.',
		'it': 'Facendo clic con il pulsante destro del mouse (tieni premuto a lungo sui dispositivi mobili) li equipaggerai nello slot secondario. Se sono presenti più di 2 slot, si aprirà un menu.',
		'ko': '마우스 오른쪽 버튼을 클릭(모바일에서는 길게 누르기)하면 보조 슬롯에 장착됩니다. 슬롯이 2개 이상인 경우 메뉴가 열립니다.',
		'ja': '右クリック (モバイルでは長押し) すると、それらを 2 番目のスロットに装備します。スロットが 2 つ以上ある場合は、メニューが開きます。',
		'pt': 'Clicar com o botão direito (segure longamente no celular) irá equipá-los no slot secundário. Se houver mais de 2 slots, um menu será aberto.',
		'pt-br': 'Clicar com o botão direito (segure longamente no celular) irá equipá-los no slot secundário. Se houver mais de 2 slots, um menu será aberto.',
		'es': 'Al hacer clic derecho (mantener presionado en dispositivos móviles) se los equipará en la ranura secundaria. Si hay más de 2 espacios, se abrirá un menú.',
		'ru': 'Щелчок правой кнопкой мыши (длительное удержание на мобильном телефоне) установит их во дополнительный слот. Если слотов больше 2, откроется меню.',
		'tr': 'Sağ Tıklama (Mobilde Uzun Tutma) onları ikincil yuvaya yerleştirecektir. 2\'den fazla yuva varsa bir menü açılacaktır.',
	},
	'POI_DESC_1': {
		'en': 'This is in another Map.',
		'zh-CN': '这是在另一张地图上的。',
		'zh-TW': '這是在另一張地圖上的。',
		'fr': 'C\'est dans une autre carte.',
		'de': 'Dies ist in einer anderen Karte.',
		'it': 'Questo è in un\'altra mappa.',
		'ko': '이것은 다른 지도에 있습니다.',
		'ja': 'これは別のマップにあります。',
		'pt': 'Isso está em outro mapa.',
		'pt-br': 'Isso está em outro mapa.',
		'es': 'Esto está en otro mapa.',
		'ru': 'Это на другой карте.',
		'tr': 'Bu başka bir Haritada.',
	},
	'OBSTACLE_DESC_1': {
		'en': 'This obstacle is built.',
		'zh-CN': '这个障碍是建立起来的。',
		'zh-TW': '這個障礙是建立起來的。',
		'fr': 'Cet obstacle est construit.',
		'de': 'Dieses Hindernis ist gebaut.',
		'it': 'Questo ostacolo è costruito.',
		'ko': '이 장애물이 만들어졌습니다.',
		'ja': 'この障害物は作られています。',
		'pt': 'Este obstáculo está construído.',
		'pt-br': 'Este obstáculo está construído.',
		'es': 'Este obstáculo está construido.',
		'ru': 'Это препятствие построено.',
		'tr': 'Bu engel inşa edilmiştir.',
	},
	'OBSTACLE_DESC_2': {
		'en': 'You meet all the requirements to build this.',
		'zh-CN': '您满足构建此项目的所有要求。',
		'zh-TW': '您滿足建置此專案的所有要求。',
		'fr': 'Vous remplissez toutes les conditions pour construire cela.',
		'de': 'Sie erfüllen alle Voraussetzungen, um dies zu bauen.',
		'it': 'Soddisfi tutti i requisiti per costruirlo.',
		'ko': '이를 구축하기 위한 모든 요구 사항을 충족합니다.',
		'ja': 'これを構築するための要件をすべて満たしています。',
		'pt': 'Você atende a todos os requisitos para construir isso.',
		'pt-br': 'Você atende a todos os requisitos para construir isso.',
		'es': 'Cumples con todos los requisitos para construir esto.',
		'ru': 'Вы соответствуете всем требованиям, чтобы построить это.',
		'tr': 'Bunu oluşturmak için tüm gereksinimleri karşılıyorsunuz.',
	},
	'OBSTACLE_DESC_3': {
		'en': 'You can\'t afford this.',
		'zh-CN': '你买不起这个。',
		'zh-TW': '你買不起這個。',
		'fr': 'Vous ne pouvez pas vous le permettre.',
		'de': 'Das können Sie sich nicht leisten.',
		'it': 'Non puoi permettertelo.',
		'ko': '당신은 이것을 감당할 수 없습니다.',
		'ja': 'こんな余裕はありません。',
		'pt': 'Não se pode dar a este luxo.',
		'pt-br': 'Você não pode pagar por isso.',
		'es': 'No puedes permitirte esto.',
		'ru': 'Ты не можешь себе этого позволить.',
		'tr': 'Bunu karşılayamazsın.',
	},
	'OBSTACLE_DESC_4': {
		'en': 'You do not meet the level requirement.',
		'zh-CN': '您不符合级别要求。',
		'zh-TW': '您不符合級別要求。',
		'fr': 'Vous ne répondez pas au niveau requis.',
		'de': 'Sie erfüllen die Levelanforderung nicht.',
		'it': 'Non soddisfi i requisiti di livello.',
		'ko': '레벨 요구 사항을 충족하지 않습니다.',
		'ja': 'レベル要件を満たしていません。',
		'pt': 'Você não atende ao requisito de nível.',
		'pt-br': 'Você não atende ao requisito de nível.',
		'es': 'No cumples con el requisito de nivel.',
		'ru': 'Вы не соответствуете требованиям по уровню.',
		'tr': 'Seviye şartını karşılamıyorsunuz.',
	},
	'OBSTACLE_DESC_5': {
		'en': 'Clicking the icon will open up a build menu.',
		'zh-CN': '单击该图标将打开构建菜单。',
		'zh-TW': '點擊該圖示將開啟建置選單。',
		'fr': 'Cliquer sur l\'icône ouvrira un menu de construction.',
		'de': 'Durch Klicken auf das Symbol wird ein Build-Menü geöffnet.',
		'it': 'Facendo clic sull\'icona si aprirà un menu di creazione.',
		'ko': '아이콘을 클릭하면 빌드 메뉴가 열립니다.',
		'ja': 'アイコンをクリックするとビルドメニューが開きます。',
		'pt': 'Clicar no ícone abrirá um menu de construção.',
		'pt-br': 'Clicar no ícone abrirá um menu de construção.',
		'es': 'Al hacer clic en el icono se abrirá un menú de compilación.',
		'ru': 'При нажатии на значок откроется меню сборки.',
		'tr': 'Simgeye tıklamak bir yapı menüsü açacaktır.',
	},
	'OBSTACLE_DESC_6': {
		'en': 'Right Clicking (Long Hold on Mobile) will open a menu with all other obstacles from the same tier.',
		'zh-CN': '右键单击（在移动设备上长按）将打开一个菜单，其中包含同一层的所有其他障碍物。',
		'zh-TW': '右鍵單擊（在行動裝置上長按）將開啟一個選單，其中包含同一層的所有其他障礙物。',
		'fr': 'Un clic droit (longue attente sur mobile) ouvrira un menu avec tous les autres obstacles du même niveau.',
		'de': 'Durch Klicken mit der rechten Maustaste (langes Halten auf dem Handy) wird ein Menü mit allen anderen Hindernissen derselben Stufe geöffnet.',
		'it': 'Facendo clic con il pulsante destro del mouse (tieni premuto a lungo su dispositivo mobile) si aprirà un menu con tutti gli altri ostacoli dello stesso livello.',
		'ko': '마우스 오른쪽 버튼을 클릭(모바일에서 길게 누르기)하면 동일한 계층의 다른 모든 장애물이 포함된 메뉴가 열립니다.',
		'ja': '右クリック (モバイルでは長押し) すると、同じ層の他のすべての障害物を含むメニューが開きます。',
		'pt': 'Clicar com o botão direito (segure longamente no celular) abrirá um menu com todos os outros obstáculos do mesmo nível.',
		'pt-br': 'Clicar com o botão direito (segure longamente no celular) abrirá um menu com todos os outros obstáculos do mesmo nível.',
		'es': 'Al hacer clic derecho (mantener presionado en el móvil) se abrirá un menú con todos los demás obstáculos del mismo nivel.',
		'ru': 'Щелчок правой кнопкой мыши (длительное удержание на мобильном устройстве) откроет меню со всеми остальными препятствиями того же уровня.',
		'tr': 'Sağ Tıklama (Mobilde Uzun Tutma), aynı seviyedeki diğer tüm engellerin bulunduğu bir menü açacaktır.',
	},
	'OTHER_DESC_1': {
		'en': 'You do not have this.',
		'zh-CN': '你没有这个。',
		'zh-TW': '你沒有這個。',
		'fr': 'Vous n\'avez pas cela.',
		'de': 'Das haben Sie nicht.',
		'it': 'Non hai questo.',
		'ko': '당신은 이것을 가지고 있지 않습니다.',
		'ja': 'あなたはこれを持っていません。',
		'pt': 'Você não tem isso.',
		'pt-br': 'Você não tem isso.',
		'es': 'No tienes esto.',
		'ru': 'У вас этого нет.',
		'tr': 'Buna sahip değilsin.',
	},
	'PURCHASE_DESC_1': {
		'en': 'You have all the requirements to purchase this.',
		'zh-CN': '您满足购买此产品的所有要求。',
		'zh-TW': '您滿足購買此產品的所有要求。',
		'fr': 'Vous avez toutes les conditions requises pour l\'acheter.',
		'de': 'Sie haben alle Voraussetzungen, um dies zu kaufen.',
		'it': 'Hai tutti i requisiti per acquistarlo.',
		'ko': '이 제품을 구매하기 위한 모든 요구 사항을 갖추고 있습니다.',
		'ja': 'これを購入するための要件が​​すべて揃っています。',
		'pt': 'Você tem todos os requisitos para comprar isso.',
		'pt-br': 'Você tem todos os requisitos para comprar isso.',
		'es': 'Tienes todos los requisitos para adquirirlo.',
		'ru': 'У вас есть все условия для покупки.',
		'tr': 'Bunu satın almak için tüm gereksinimlere sahipsiniz.',
	},
	'PURCHASE_DESC_2': {
		'en': 'Click the icon to purchase this.',
		'zh-CN': '单击该图标即可购买。',
		'zh-TW': '點擊該圖示即可購買。',
		'fr': 'Cliquez sur l\'icône pour l\'acheter.',
		'de': 'Klicken Sie auf das Symbol, um es zu kaufen.',
		'it': 'Fare clic sull\'icona per acquistarlo.',
		'ko': '아이콘을 클릭하시면 구매하실 수 있습니다.',
		'ja': 'アイコンをクリックしてご購入ください。',
		'pt': 'Clique no ícone para comprar isto.',
		'pt-br': 'Clique no ícone para comprar isto.',
		'es': 'Haga clic en el icono para comprarlo.',
		'ru': 'Нажмите на значок, чтобы купить это.',
		'tr': 'Bunu satın almak için simgeye tıklayın.',
	},
	'FILTERING_DESC_1': {
		'en': 'Click on an icon to Filter!',
		'zh-CN': '单击图标进行过滤！',
		'zh-TW': '點擊圖標進行過濾！',
		'fr': 'Cliquez sur une icône pour filtrer !',
		'de': 'Klicken Sie auf ein Symbol, um zu filtern!',
		'it': 'Clicca su un\'icona per filtrare!',
		'ko': '필터링하려면 아이콘을 클릭하세요!',
		'ja': 'フィルターするにはアイコンをクリックしてください。',
		'pt': 'Clique em um ícone para filtrar!',
		'pt-br': 'Clique em um ícone para filtrar!',
		'es': '¡Haga clic en un icono para filtrar!',
		'ru': 'Нажмите на значок, чтобы отфильтровать!',
		'tr': 'Filtrelemek için bir simgeye tıklayın!',
	},
	'FILTERING_DESC_2': {
		'en': 'Mass Filtering will filter that icon everywhere.',
		'zh-CN': '质量过滤将在各处过滤该图标。',
		'zh-TW': '品質過濾將在各處過濾該圖示。',
		'fr': 'Le filtrage de masse filtrera cette icône partout.',
		'de': 'Durch die Massenfilterung wird dieses Symbol überall gefiltert.',
		'it': 'Il filtraggio di massa filtrerà quell\'icona ovunque.',
		'ko': '대량 필터링은 해당 아이콘을 모든 곳에서 필터링합니다.',
		'ja': '一括フィルタリングは、そのアイコンをあらゆる場所でフィルタリングします。',
		'pt': 'A Filtragem em Massa filtrará esse ícone em todos os lugares.',
		'pt-br': 'A Filtragem em Massa filtrará esse ícone em todos os lugares.',
		'es': 'El filtrado masivo filtrará ese icono en todas partes.',
		'ru': 'Массовая фильтрация будет фильтровать этот значок повсюду.',
		'tr': 'Toplu Filtreleme bu simgeyi her yerde filtreleyecektir.',
	},
	'FILTERING_DESC_3': {
		'en': 'When Mass Filtering is enabled, all filtered icons will be synced with the clicked icon.',
		'zh-CN': '启用质量过滤后，所有过滤的图标将与单击的图标同步。',
		'zh-TW': '啟用品質過濾後，所有過濾的圖示將與點擊的圖示同步。',
		'fr': 'Lorsque le filtrage de masse est activé, toutes les icônes filtrées seront synchronisées avec l\'icône cliquée.',
		'de': 'Wenn die Massenfilterung aktiviert ist, werden alle gefilterten Symbole mit dem angeklickten Symbol synchronisiert.',
		'it': 'Quando il filtro di massa è abilitato, tutte le icone filtrate verranno sincronizzate con l\'icona su cui si è fatto clic.',
		'ko': '대량 필터링이 활성화되면 필터링된 모든 아이콘이 클릭한 아이콘과 동기화됩니다.',
		'ja': '一括フィルタリングを有効にすると、フィルタリングされたすべてのアイコンがクリックされたアイコンと同期されます。',
		'pt': 'Quando a Filtragem em Massa estiver habilitada, todos os ícones filtrados serão sincronizados com o ícone clicado.',
		'pt-br': 'Quando a Filtragem em Massa estiver habilitada, todos os ícones filtrados serão sincronizados com o ícone clicado.',
		'es': 'Cuando el filtrado masivo está habilitado, todos los íconos filtrados se sincronizarán con el ícono en el que se hizo clic.',
		'ru': 'Если массовая фильтрация включена, все отфильтрованные значки будут синхронизированы с выбранным значком.',
		'tr': 'Toplu Filtreleme etkinleştirildiğinde, filtrelenen tüm simgeler tıklanan simgeyle senkronize edilecektir.',
	},
	'DELETE_DATA_2': {
		'en': 'This cannot be undone!',
		'zh-CN': '这不能被撤消！',
		'zh-TW': '這不能被撤銷！',
		'fr': 'Ça ne peut pas être annulé!',
		'de': 'Das kann nicht rückgängig gemacht werden!',
		'it': 'Questa operazione non può essere annullata!',
		'ko': '이 취소 할 수 없습니다!',
		'ja': 'これは、元に戻すことはできません！',
		'pt': 'Isto não pode ser desfeito!',
		'pt-br': 'Isto não pode ser desfeito!',
		'es': '¡Esto no se puede deshacer!',
		'ru': 'Это не может быть отменено!',
		'tr': 'Bu geri alınamaz!',
	},
	'AUTOMATICALLY_HIDE': {
		'en': 'This category will be hidden if you own everything.',
		'zh-CN': '如果您拥有一切，此类别将被隐藏。',
		'zh-TW': '如果您擁有一切，此類別將被隱藏。',
		'fr': 'Cette catégorie sera masquée si vous possédez tout.',
		'de': 'Diese Kategorie wird ausgeblendet, wenn Sie alles besitzen.',
		'it': 'Questa categoria verrà nascosta se possiedi tutto.',
		'ko': '모든 항목을 소유한 경우 이 카테고리는 숨겨집니다.',
		'ja': 'すべてを所有している場合、このカテゴリは非表示になります。',
		'pt': 'Esta categoria ficará oculta se você possuir tudo.',
		'pt-br': 'Esta categoria ficará oculta se você possuir tudo.',
		'es': 'Esta categoría estará oculta si eres dueño de todo.',
		'ru': 'Эта категория будет скрыта, если у вас есть все.',
		'tr': 'Her şeyin sahibiyseniz bu kategori gizlenecektir.',
	},
	'SETTING_MERGE': {
		'en': 'Merge Global and Skill categories?',
		'zh-CN': '合并全局和技能类别？',
		'zh-TW': '合併全域和技能類別？',
		'fr': 'Fusionner les catégories Global et Compétence ?',
		'de': 'Globale und Kompetenzkategorien zusammenführen?',
		'it': 'Unire le categorie globali e di competenza?',
		'ko': '글로벌 및 스킬 카테고리를 병합하시겠습니까?',
		'ja': 'グローバル カテゴリとスキル カテゴリを統合しますか?',
		'pt': 'Mesclar categorias globais e de habilidades?',
		'pt-br': 'Mesclar categorias globais e de habilidades?',
		'es': '¿Fusionar las categorías Global y Skill?',
		'ru': 'Объединить глобальные категории и категории навыков?',
		'tr': 'Global ve Beceri kategorileri birleştirilsin mi?',
	},
	'SETTING_MERGE_DESC': {
		'en': 'This setting may be removed in the next big update.',
		'zh-CN': '此设置可能会在下一次大更新中删除。',
		'zh-TW': '此設定可能會在下次大更新中刪除。',
		'fr': 'Ce paramètre pourrait être supprimé lors de la prochaine grande mise à jour.',
		'de': 'Diese Einstellung wird möglicherweise im nächsten großen Update entfernt.',
		'it': 'Questa impostazione potrebbe essere rimossa nel prossimo grande aggiornamento.',
		'ko': '이 설정은 다음 대규모 업데이트에서 제거될 수 있습니다.',
		'ja': 'この設定は次の大きなアップデートで削除される可能性があります。',
		'pt': 'Esta configuração pode ser removida na próxima grande atualização.',
		'pt-br': 'Esta configuração pode ser removida na próxima grande atualização.',
		'es': 'Es posible que esta configuración se elimine en la próxima gran actualización.',
		'ru': 'Этот параметр может быть удален в следующем большом обновлении.',
		'tr': 'Bu ayar bir sonraki büyük güncellemede kaldırılabilir.',
	},
	'SETTING_ASTRO_SPOILERS': {
		'en': 'Show locked Astrology modifiers?',
		'zh-CN': '显示锁定的占星术修改器？',
		'zh-TW': '顯示鎖定的占星術修改器？',
		'fr': 'Afficher les modificateurs d\'astrologie verrouillés ?',
		'de': 'Gesperrte Astrologie-Modifikatoren anzeigen?',
		'it': 'Mostrare i modificatori di astrologia bloccati?',
		'ko': '잠긴 점성술 수정자를 표시하시겠습니까?',
		'ja': 'ロックされた占星術修飾子を表示しますか?',
		'pt': 'Mostrar modificadores astrológicos bloqueados?',
		'pt-br': 'Mostrar modificadores astrológicos bloqueados?',
		'es': '¿Mostrar modificadores de astrología bloqueados?',
		'ru': 'Показать заблокированные модификаторы астрологии?',
		'tr': 'Kilitli Astroloji değiştiricileri gösterilsin mi?',
	},
	'SETTING_HIDE_REDBGS': {
		'en': 'Hide icons with a "red" background?',
		'zh-CN': '隐藏带有“红色”背景的图标？',
		'zh-TW': '隱藏帶有“紅色”背景的圖示？',
		'fr': 'Masquer les icônes avec un fond « rouge » ?',
		'de': 'Icons mit „rotem“ Hintergrund ausblenden?',
		'it': 'Nascondere le icone con uno sfondo "rosso"?',
		'ko': '"빨간색" 배경의 아이콘을 숨기시겠습니까?',
		'ja': '背景が「赤」のアイコンを非表示にしますか?',
		'pt': 'Ocultar ícones com fundo "vermelho"?',
		'pt-br': 'Ocultar ícones com fundo "vermelho"?',
		'es': '¿Ocultar iconos con fondo "rojo"?',
		'ru': 'Скрыть иконки с «красным» фоном?',
		'tr': '"Kırmızı" arka plana sahip simgeler gizlensin mi?',
	},
	'INCLUDE_FILTERED': {
		'en': 'Include Filtered',
		'zh-CN': '包括过滤的',
		'zh-TW': '包括過濾的',
		'fr': 'Inclure filtré',
		'de': 'Gefiltert einschließen',
		'it': 'Includi filtrato',
		'ko': '필터링된 항목 포함',
		'ja': 'フィルタリングされたものを含む',
		'pt': 'Incluir Filtrado',
		'pt-br': 'Incluir Filtrado',
		'es': 'Incluir filtrado',
		'ru': 'Включить отфильтрованное',
		'tr': 'Filtrelenmişleri Dahil Et',
	},
	'INCLUDE_HIDDEN': {
		'en': 'Include Hidden',
		'zh-CN': '包括隐藏',
		'zh-TW': '包括隱藏',
		'fr': 'Inclure masqué',
		'de': 'Versteckt einbeziehen',
		'it': 'Includi nascosti',
		'ko': '숨겨진 항목 포함',
		'ja': '非表示を含む',
		'pt': 'Incluir oculto',
		'pt-br': 'Incluir oculto',
		'es': 'Incluir oculto',
		'ru': 'Включить скрытое',
		'tr': 'Gizliyi Ekle',
	},
	'INCLUDE_REDBG': {
		'en': 'Include "Red" Backgrounds',
		'zh-CN': '包括“红色”背景',
		'zh-TW': '包括“紅色”背景',
		'fr': 'Inclure les arrière-plans « rouges »',
		'de': 'Fügen Sie „rote“ Hintergründe hinzu',
		'it': 'Includi sfondi "rossi".',
		'ko': '"빨간색" 배경 포함',
		'ja': '「赤」の背景を含める',
		'pt': 'Incluir fundos "vermelhos"',
		'pt-br': 'Incluir fundos "vermelhos"',
		'es': 'Incluir fondos "rojos"',
		'ru': 'Включить «красный» фон',
		'tr': '"Kırmızı" Arka Planları Ekle',
	},
	'INCLUDE_REALMS': {
		'en': 'Include All Realms',
		'zh-CN': '包括所有领域',
		'zh-TW': '包括所有領域',
		'fr': 'Inclure tous les domaines',
		'de': 'Alle Bereiche einbeziehen',
		'it': 'Includi tutti i regni',
		'ko': '모든 영역 포함',
		'ja': 'すべてのレルムを含める',
		'pt': 'Incluir todos os reinos',
		'pt-br': 'Incluir todos os reinos',
		'es': 'Incluir todos los reinos',
		'ru': 'Включить все области',
		'tr': 'Tüm Bölgeleri Dahil Et',
	},
	'SETTINGS_MODIFIER_TEXT': {
		'en': 'Which should be included when searching modifier text?',
		'zh-CN': '搜索修饰符文本时应包含哪些内容？',
		'zh-TW': '搜尋修飾符文字時應包含哪些內容？',
		'fr': 'Lequel doit être inclus lors de la recherche de texte de modificateur ?',
		'de': 'Was sollte bei der Suche nach Modifikatortext berücksichtigt werden?',
		'it': 'Quale dovrebbe essere incluso durante la ricerca del testo modificatore?',
		'ko': '수정자 텍스트를 검색할 때 어떤 항목을 포함해야 합니까?',
		'ja': '修飾子テキストを検索する場合はどれを含める必要がありますか?',
		'pt': 'O que deve ser incluído ao pesquisar texto modificador?',
		'pt-br': 'O que deve ser incluído ao pesquisar texto modificador?',
		'es': '¿Qué debería incluirse al buscar texto modificador?',
		'ru': 'Что следует включать при поиске текста модификатора?',
		'tr': 'Değiştirici metin aranırken hangisi dahil edilmelidir?',
	},
	'SETTING_ONLY_USEFUL_MODS': {
		'en': 'Only show useful modifiers in tooltips?',
		'zh-CN': '只在工具提示中显示有用的修饰符？',
		'zh-TW': '只在工具提示中顯示有用的修飾符？',
		'fr': 'Afficher uniquement les modificateurs utiles dans les info-bulles ?',
		'de': 'Nur nützliche Modifikatoren in Tooltips anzeigen?',
		'it': 'Mostrare solo i modificatori utili nei tooltip?',
		'ko': '툴팁에 유용한 수정자만 표시하시겠습니까?',
		'ja': '有用な修飾子のみをツールチップに表示しますか?',
		'pt': 'Mostrar apenas modificadores úteis nas dicas de ferramentas?',
		'pt-br': 'Mostrar apenas modificadores úteis nas dicas de ferramentas?',
		'es': '¿Mostrar sólo modificadores útiles en la información sobre herramientas?',
		'ru': 'Показывать во всплывающих подсказках только полезные модификаторы?',
		'tr': 'Araç ipuçlarında yalnızca yararlı değiştiriciler gösterilsin mi?',
	},
	'SETTING_PRESET_BUTTON': {
		'en': 'Show Presets Button?',
		'zh-CN': '显示预置按钮？',
		'zh-TW': '顯示预置按鈕？',
		'fr': 'Afficher le bouton Préréglages ?',
		'de': 'Schaltfläche „Voreinstellungen anzeigen“?',
		'it': 'Mostra pulsante Preimpostazioni?',
		'ko': '사전 설정 버튼을 표시하시겠습니까?',
		'ja': 'プリセットボタンを表示しますか?',
		'pt': 'Mostrar botão de predefinições?',
		'pt-br': 'Mostrar botão de predefinições?',
		'es': '¿Mostrar botón de ajustes preestablecidos?',
		'ru': 'Показать кнопку предустановок?',
		'tr': 'Ön Ayarlar Düğmesi Gösterilsin mi?',
	},
	'SETTING_PRESET_FILTER': {
		'en': 'Filter by Preset Type',
		'zh-CN': '按预设类型过滤',
		'zh-TW': '按預設類型過濾',
		'fr': 'Filtrer par type de préréglage',
		'de': 'Nach Voreinstellungstyp filtern',
		'it': 'Filtra per tipo di preimpostazione',
		'ko': '사전 설정 유형으로 필터링',
		'ja': 'プリセットタイプによるフィルター',
		'pt': 'Filtrar por tipo predefinido',
		'pt-br': 'Filtrar por tipo predefinido',
		'es': 'Filtrar por tipo preestablecido',
		'ru': 'Фильтровать по типу предустановки',
		'tr': 'Ön Ayar Türüne Göre Filtrele',
	},
	'SETTING_PRESET_FILTER_HINT': {
		'en': 'When using "Only Current Skill", you must enable the skill under Minibar Settings. Combat skills will default to \'Combat\' Presets.',
		'zh-CN': '使用“仅当前技能”时，您必须在迷你栏设置下启用该技能。战斗技能将默认为“战斗”预设。',
		'zh-TW': '使用“僅當前技能”時，您必須在迷你欄設定下啟用該技能。戰鬥技能將預設為「戰鬥」預設。',
		'fr': 'Lorsque vous utilisez « Uniquement la compétence actuelle », vous devez activer la compétence sous Paramètres du minibar. Les compétences de combat seront par défaut sur les préréglages « Combat ».',
		'de': 'Wenn Sie „Nur aktuelle Fertigkeit“ verwenden, müssen Sie die Fertigkeit in den Minibar-Einstellungen aktivieren. Kampffähigkeiten werden standardmäßig auf „Kampf“-Voreinstellungen gesetzt.',
		'it': 'Quando utilizzi "Solo abilità corrente", devi abilitare l\'abilità nelle Impostazioni della barra multifunzione. Le abilità di combattimento verranno impostate per impostazione predefinita su "Combattimento".',
		'ko': '\'현재 스킬만\' 사용 시 미니바 설정에서 해당 스킬을 활성화해야 합니다. 전투 기술은 기본적으로 \'전투\' 사전 설정으로 설정됩니다.',
		'ja': '「現在のスキルのみ」を使用する場合は、ミニバー設定でスキルを有効にする必要があります。戦闘スキルはデフォルトで「戦闘」プリセットになります。',
		'pt': 'Ao usar "Somente Habilidade Atual", você deve ativar a habilidade nas Configurações do Minibar. As habilidades de combate terão como padrão as predefinições de \'Combate\'.',
		'pt-br': 'Ao usar "Somente Habilidade Atual", você deve ativar a habilidade nas Configurações do Minibar. As habilidades de combate terão como padrão as predefinições de \'Combate\'.',
		'es': 'Cuando utilices "Solo habilidad actual", debes habilitar la habilidad en Configuración del minibar. Las habilidades de combate tendrán por defecto los ajustes preestablecidos de \'Combate\'.',
		'ru': 'При использовании «Только текущий навык» необходимо включить этот навык в настройках мини-бара. По умолчанию для боевых навыков будут установлены «боевые» настройки.',
		'tr': '"Yalnızca Mevcut Beceri"yi kullanırken Minibar Ayarları altında beceriyi etkinleştirmeniz gerekir. Savaş becerileri varsayılan olarak \'Savaş\' Ön Ayarlarına ayarlanacaktır.',
	},
	'SETTING_PRESET_FILTER_OPTION_1': {
		'en': 'All + Skill/Combat',
		'zh-CN': '全部+技能/战斗',
		'zh-TW': '全部+技能/戰鬥',
		'fr': 'Tous + Compétence/Combat',
		'de': 'Alle + Geschicklichkeit/Kampf',
		'it': 'Tutto + Abilità/Combattimento',
		'ko': '전체+스킬/전투',
		'ja': 'すべて + スキル/戦闘',
		'pt': 'Todos + Habilidade/Combate',
		'pt-br': 'Todos + Habilidade/Combate',
		'es': 'Todo + Habilidad/Combate',
		'ru': 'Все + Навыки/Бой',
		'tr': 'Hepsi + Beceri/Savaş',
	},
	'SETTING_PRESET_FILTER_OPTION_2': {
		'en': 'Only Skill/Combat',
		'zh-CN': '仅限技能/战斗',
		'zh-TW': '限技能/戰鬥',
		'fr': 'Uniquement Compétence/Combat',
		'de': 'Nur Geschick/Kampf',
		'it': 'Solo Abilità/Combattimento',
		'ko': '스킬/전투만 가능',
		'ja': 'スキル/戦闘のみ',
		'pt': 'Apenas Habilidade/Combate',
		'pt-br': 'Apenas Habilidade/Combate',
		'es': 'Sólo habilidad/combate',
		'ru': 'Только Навыки/Бой',
		'tr': 'Yalnızca Beceri/Savaş',
	},
	'SETTING_PRESET_FILTER_OPTION_3': {
		'en': 'Only Current Skill',
		'zh-CN': '仅当前技能',
		'zh-TW': '僅當前技能',
		'fr': 'Seule la compétence actuelle',
		'de': 'Nur aktuelle Fähigkeit',
		'it': 'Solo abilità attuale',
		'ko': '현재 스킬만',
		'ja': '現在のスキルのみ',
		'pt': 'Apenas habilidade atual',
		'pt-br': 'Apenas habilidade atual',
		'es': 'Sólo habilidad actual',
		'ru': 'Только текущий навык',
		'tr': 'Yalnızca Mevcut Beceri',
	},
	'SETTING_PRESET_NO_PRESET': {
		'en': '(Preset Button) Create Preset if no presets were found?',
		'zh-CN': '（预设按钮）如果没有找到预设，是否创建预设？',
		'zh-TW': '（預設按鈕）如果沒有找到預設，是否建立預設？',
		'fr': '(Bouton Preset) Créer un préréglage si aucun préréglage n\'a été trouvé ?',
		'de': '(Preset-Button) Preset erstellen, wenn keine Presets gefunden wurden?',
		'it': '(Pulsante Preset) Creare preset se non sono stati trovati preset?',
		'ko': '(프리셋 버튼) 프리셋이 없으면 프리셋을 생성하시겠습니까?',
		'ja': '(プリセットボタン) プリセットが見つからない場合はプリセットを作成しますか?',
		'pt': '(Botão Preset) Criar predefinição se nenhuma predefinição for encontrada?',
		'pt-br': '(Botão Preset) Criar predefinição se nenhuma predefinição for encontrada?',
		'es': '(Botón Preset) ¿Crear preset si no se encontraron ajustes preestablecidos?',
		'ru': '(Кнопка «Предустановка») Создать предустановку, если предустановки не найдены?',
		'tr': '(Ön Ayar Düğmesi) Hiçbir ön ayar bulunamazsa Ön Ayar oluşturulsun mu?',
	},
	'SETTING_PRESET_ONE_PRESET': {
		'en': '(Preset Button) Edit Preset if only one preset was found?',
		'zh-CN': '（预设按钮）如果只找到一个预设，请编辑预设？',
		'zh-TW': '（預設按鈕）如果只找到一個預設，請編輯預設？',
		'fr': '(Bouton Preset) Modifier le préréglage si un seul préréglage a été trouvé ?',
		'de': '(Voreinstellungsschaltfläche) Voreinstellung bearbeiten, wenn nur eine Voreinstellung gefunden wurde?',
		'it': '(Pulsante Preset) Modifica la preimpostazione se è stata trovata una sola preimpostazione?',
		'ko': '(프리셋 버튼) 프리셋이 하나만 발견된 경우 프리셋을 편집하시겠습니까?',
		'ja': '(プリセット ボタン) プリセットが 1 つだけ見つかった場合は、プリセットを編集しますか?',
		'pt': '(Botão Preset) Editar predefinição se apenas uma predefinição foi encontrada?',
		'pt-br': '(Botão Preset) Editar predefinição se apenas uma predefinição foi encontrada?',
		'es': '(Botón Preset) ¿Editar preset si solo se encontró un preset?',
		'ru': '(Кнопка «Предустановка») Редактировать предустановку, если найден только один пресет?',
		'tr': '(Ön Ayar Düğmesi) Yalnızca bir ön ayar bulunursa Ön Ayar düzenlensin mi?',
	},
	'SETTING_SHOW_ALL_OBSTACLES': {
		'en': 'Show all Obstacles on the Agility page?',
		'zh-CN': '在敏捷性页面上显示所有障碍？',
		'zh-TW': '在敏捷性頁面上顯示所有障礙？',
		'fr': 'Afficher tous les obstacles sur la page Agilité ?',
		'de': 'Alle Hindernisse auf der Agility-Seite anzeigen?',
		'it': 'Mostrare tutti gli ostacoli nella pagina Agilità?',
		'ko': '민첩성 페이지에 모든 장애물을 표시하시겠습니까?',
		'ja': '「敏捷性」ページにすべての障害物を表示しますか?',
		'pt': 'Mostrar todos os obstáculos na página Agilidade?',
		'pt-br': 'Mostrar todos os obstáculos na página Agilidade?',
		'es': '¿Mostrar todos los obstáculos en la página de Agilidad?',
		'ru': 'Показать все препятствия на странице ловкости?',
		'tr': 'Çeviklik sayfasındaki tüm Engeller gösterilsin mi?',
	},
	'SETTING_SHOW_ALL_OBSTACLES_HINT': {
		'en': 'Search results will include all Positive modifiers from that obstacle.',
		'zh-CN': '搜索结果将包括该障碍物的所有正面修饰符。',
		'zh-TW': '搜尋結果將包括該障礙物的所有正面修飾符。',
		'fr': 'Les résultats de la recherche incluront tous les modificateurs positifs de cet obstacle.',
		'de': 'Die Suchergebnisse umfassen alle positiven Modifikatoren dieses Hindernisses.',
		'it': 'I risultati della ricerca includeranno tutti i modificatori positivi derivanti da quell\'ostacolo.',
		'ko': '검색 결과에는 해당 장애물의 모든 긍정적인 수정자가 포함됩니다.',
		'ja': '検索結果には、その障害物からのすべてのポジティブ修飾子が含まれます。',
		'pt': 'Os resultados da pesquisa incluirão todos os modificadores positivos desse obstáculo.',
		'pt-br': 'Os resultados da pesquisa incluirão todos os modificadores positivos desse obstáculo.',
		'es': 'Los resultados de la búsqueda incluirán todos los modificadores positivos de ese obstáculo.',
		'ru': 'Результаты поиска будут включать все положительные модификаторы этого препятствия.',
		'tr': 'Arama sonuçları, söz konusu engelin tüm Pozitif değiştiricilerini içerecektir.',
	},
	'SETTING_INSTA_BUILD': {
		'en': 'Skip the Obstacle build menu?',
		'zh-CN': '跳过障碍构建菜单？',
		'zh-TW': '跳過障礙建置選單？',
		'fr': 'Ignorer le menu de création d\'obstacles ?',
		'de': 'Das Menü „Hindernisbau“ überspringen?',
		'it': 'Saltare il menu di creazione degli ostacoli?',
		'ko': '장애물 제작 메뉴를 건너뛰시겠습니까?',
		'ja': '障害物構築メニューをスキップしますか?',
		'pt': 'Ignorar o menu de construção de obstáculos?',
		'pt-br': 'Ignorar o menu de construção de obstáculos?',
		'es': '¿Saltar el menú de construcción de obstáculos?',
		'ru': 'Пропустить меню построения препятствий?',
		'tr': 'Engel oluşturma menüsünü atla?',
	},
};